#ifndef _CUSTOMDEFCLI_H_
#define _CUSTOMDEFCLI_H_

#if defined(CUSTOM_CHRISTIE)
// CLI_SOURCE
#define CLI_SOURCE_HDMI1 (3)
#define CLI_SOURCE_HDMI2 (4)
#define CLI_SOURCE_DVI (5)
#define CLI_SOURCE_DP (6)
#define CLI_SOURCE_3GSDI (7)
#define CLI_SOURCE_HDBASET (8)

// CLI_TEST_PATTERN
#define CLI_TEST_PATTERN_OFF (0)
#define CLI_TEST_PATTERN_GRID (1)
#define CLI_TEST_PATTERN_WHITE (2)
#define CLI_TEST_PATTERN_BLACK (3)
#define CLI_TEST_PATTERN_CHECKERBOARD (4)
#define CLI_TEST_PATTERN_COLORBAR (5)

//CLI_SERVICE_TEST_PATTERN
#define CLI_SERVICE_TEST_PATTERN_OFF (0)
#define CLI_SERVICE_TEST_PATTERN_GRID (1)
#define CLI_SERVICE_TEST_PATTERN_WHITE (2)
#define CLI_SERVICE_TEST_PATTERN_BLACK (3)
#define CLI_SERVICE_TEST_PATTERN_CHECKBOARD (4)
#define CLI_SERVICE_TEST_PATTERN_COLORBAR (5)
#define CLI_SERVICE_TEST_PATTERN_RED (6)
#define CLI_SERVICE_TEST_PATTERN_GREEN (7)
#define CLI_SERVICE_TEST_PATTERN_BLUE (8)
#define CLI_SERVICE_TEST_PATTERN_YELLOW (9)
#define CLI_SERVICE_TEST_PATTERN_MAGENTA (10)
#define CLI_SERVICE_TEST_PATTERN_CYAN (11)
#define CLI_SERVICE_TEST_PATTERN_BORESIGHT (12)
#define CLI_SERVICE_TEST_PATTERN_FULL_SCREEN (13)
#define CLI_SERVICE_TEST_PATTERN_13POINTS (14)

//CLI_TWIST_TEST_PATTERN
#define CLI_TWIST_TEST_PATTERN_OFF (0)
#define CLI_TWIST_TEST_PATTERN_GRID (1)
#define CLI_TWIST_TEST_PATTERN_WHITE (2)
#define CLI_TWIST_TEST_PATTERN_BLACK (3)
#define CLI_TWIST_TEST_PATTERN_CHECKERBOARD (4)
#define CLI_TWIST_TEST_PATTERN_COLORBAR (5)
#define CLI_TWIST_TEST_PATTERN_GRAY (6)

//CLI_PICTURE_SETTINGS
#define CLI_PICTURE_SETTINGS_VIDEO 		    (0)
#define CLI_PICTURE_SETTINGS_BRIGHT 		(1)
#define CLI_PICTURE_SETTINGS_ENHANCED 		(2)
#define CLI_PICTURE_SETTINGS_REC709 		(3)
#define CLI_PICTURE_SETTINGS_DICOMSIM 		(4)
#define CLI_PICTURE_SETTINGS_BLENDING 		(5)
#define CLI_PICTURE_SETTINGS_HDR 			(6)
#define CLI_PICTURE_SETTINGS_3D 			(7)
#define CLI_PICTURE_SETTINGS_2D_HIGH_SPEED 	(8)
#define CLI_PICTURE_SETTINGS_USER 			(9)

//CLI_APPLY_USER    //G100_Doulas_0066
#define CLI_PRE_USER_VIDEO 		    (0)
#define CLI_PRE_USER_BRIGHT 		(1)
#define CLI_PRE_USER_ENHANCED 		(2)
#define CLI_PRE_USER_REC709 		(3)
#define CLI_PRE_USER_DICOMSIM 		(4)
#define CLI_PRE_USER_BLENDING 		(5)
#define CLI_PRE_USER_HDR 			(6)
#define CLI_PRE_USER_3D 			(7)
#define CLI_PRE_USER_2D_HIGH_SPEED 	(8)

//CLI_LANGUAGE
#define CLI_LANGUAGE_ENGLISH (0)
#define CLI_LANGUAGE_FRENCH (1)
#define CLI_LANGUAGE_SPANISH (2)
#define CLI_LANGUAGE_GERMAN (3)
#define CLI_LANGUAGE_ITALIAN (4)
#define CLI_LANGUAGE_POLSKI (5)
#define CLI_LANGUAGE_RUSSIAN (6)
#define CLI_LANGUAGE_S_CHINESE (7)
#define CLI_LANGUAGE_T_CHINESE (8)
#define CLI_LANGUAGE_JAPANESE (9)
#define CLI_LANGUAGE_KOREAN (10)

//CLI_SCALING_MODE
#define CLI_SCALING_MODE_AUTO (0)
#define CLI_SCALING_MODE_NATIVE (1)
#define CLI_SCALING_MODE_4_3 (2)
#define CLI_SCALING_MODE_LETTER_BOX (3)
#define CLI_SCALING_MODE_FULL_SIZE (4)
#define CLI_SCALING_MODE_FULL_WIDTH (5)
#define CLI_SCALING_MODE_FULL_HEIGHT (6)
#define CLI_SCALING_MODE_CUSTOM (7)
#define CLI_SCALING_MODE_3D (8)
#define CLI_SCALING_MODE_21_9 (9)

//CLI_HOTKEY_SETTING
#define CLI_HOTKEY_SETTINGS_SIZE_PRESETS (0)
#define CLI_HOTKEY_SETTINGS_PICTURE_SETTINGS (1)
#define CLI_HOTKEY_SETTINGS_DEFAULT_VALUE (2)
#define CLI_HOTKEY_SETTINGS_DETAIL (3)
#define CLI_HOTKEY_SETTINGS_CONTRAST_ENHANCEMENT (4)
#define CLI_HOTKEY_SETTINGS_LIGHT_SOURCE_MODE (5)
#define CLI_HOTKEY_SETTINGS_FREEZE_SCREEN (6)
#define CLI_HOTKEY_SETTINGS_INFORMATION (7)
#define CLI_HOTKEY_SETTINGS_WARPBLEND_DISABLE (8)

//CLI_SCREEN_MODE (PIP/PBP)
#define CLI_SCREEN_MODE_OFF (0)
#define CLI_SCREEN_MODE_PIP (1)
#define CLI_SCREEN_MODE_PBP (2)

//CLI_MENU_LOCATION
#define CLI_MENU_LOCATION_TOP_LEFT (0)
#define CLI_MENU_LOCATION_TOP_RIGHT (1)
#define CLI_MENU_LOCATION_CENTER (2)
#define CLI_MENU_LOCATION_BOTTOM_LEFT (3)
#define CLI_MENU_LOCATION_BOTTOM_RIGHT (4)

//OVERSCAN
#define CLI_OVERSCAN_OFF (0)
#define CLI_OVERSCAN_ZOOM (1)
#define CLI_OVERSCAN_CROP (2)

//COLOR_SPACE
#define CLI_COLOR_SPACE_AUTO (0)
#define CLI_COLOR_SPACE_RGB_FULL (1)
#define CLI_COLOR_SPACE_RGB_LIMITED (2)
#define CLI_COLOR_SPACE_YUV_REC709 (3)
#define CLI_COLOR_SPACE_YUV_REC601 (4)

//3D_MODE
#define CLI_3D_MODE_ACTIVE_3D   (0) //active
#define CLI_3D_MODE_PASSIVE_3D  (1) //passive
//#define CLI_3D_MODE_OFF (2)

//3D_FORMAT
#define CLI_3D_FORMAT_AUTO (0)
#define CLI_3D_FORMAT_FRAME_PACKING (1)
#define CLI_3D_FORMAT_SIDE_BY_SIDE (2)
#define CLI_3D_FORMAT_TOP_AND_BOTTOM (3)
#define CLI_3D_FORMAT_FRAME_SEQUENTIAL (4)
#define CLI_3D_FORMAT_OFF (5)
#define CLI_3D_FORMAT_DUALPIPE (6)
#define CLI_3D_FORMAT_4K3D (7)
#define CLI_3D_FORMAT_4K3D_DUALPIPE (8)

//3D_TECH
#define CLI_3D_TECH_DLP_LINK (0)
#define CLI_3D_TECH_3D_SYNC (1)

//3D_2D
#define CLI_3D_2D_3D (0)
#define CLI_3D_2D_2D_LEFT (1)
#define CLI_3D_2D_2D_RIGHT (2)

//3D_SYNC_OUT
#define CLI_3D_SYNC_OUT_TO_EMITTER (0)
#define CLI_3D_SYNC_OUT_TO_NEXT_PROJECTOR (1)

//3D_LR_REFERENCE
#define CLI_3D_LR_REFERENCE_1ST_FRAME (0)
#define CLI_3D_LR_REFERENCE_FIELD_GPIO (1)

//3D_SYNC_TYPE
#define CLI_3D_SYNC_TYPE_AUTO (0)
#define CLI_3D_SYNC_TYPE_INTERNAL (1)
#define CLI_3D_SYNC_TYPE_EXTERNAL (2)

//CONTRAST_ENHANCEMENT
#define CLI_CONTRAST_ENHANCEMENT_OFF (0)
#define CLI_CONTRAST_ENHANCEMENT_CE1 (1)
#define CLI_CONTRAST_ENHANCEMENT_CE2 (2)

//GAMMA
#define CLI_GAMMA_VIDEO     (0)
#define CLI_GAMMA_FILM      (1)
#define CLI_GAMMA_BRIGHT    (2)
#define CLI_GAMMA_CRT       (3)
#define CLI_GAMMA_DICOM     (4)
#define CLI_GAMMA_HDR       (5)

//EDGE_ENHANCEMENT
#define CLI_EDGE_ENHANCEMENT_OFF (0)
#define CLI_EDGE_ENHANCEMENT_NORMAL (1)
#define CLI_EDGE_ENHANCEMENT_MAXIMUM (2)

//COLOR_WHEEL_SPEED
#define CLI_COLOR_WHEEL_SPEED_2X (0)
#define CLI_COLOR_WHEEL_SPEED_3X (1)

//LENS_TYPE
#define CLI_LENS_TYPE_NA (0)
#define CLI_LENS_TYPE_A20 (1)
#define CLI_LENS_TYPE_A21 (2)
#define CLI_LENS_TYPE_A22 (3)
#define CLI_LENS_TYPE_A23 (4)
#define CLI_LENS_TYPE_A24 (5)
#define CLI_LENS_TYPE_A25 (6)
#define CLI_LENS_TYPE_A26 (7)

//CEILING_MOUNT
#define CLI_CEILING_MOUNT_OFF (0)
#define CLI_CEILING_MOUNT_ON (1)
#define CLI_CEILING_MOUNT_AUTO (2)

//REAR_PROJECTION
#define CLI_REAR_PROJECTION_FRONT (0)
#define CLI_REAR_PROJECTION_REAR (1)

//SPLASH_STARTUP
#define CLI_SPLASH_STARTUP_FACTORY_LOGO (0)
#define CLI_SPLASH_STARTUP_BLUE (1)
#define CLI_SPLASH_STARTUP_BLACK (2)
#define CLI_SPLASH_STARTUP_WHITE (3)

//STANDBY_MODE
#define CLI_STANDBY_MODE_STANDBY (0)
//#define CLI_STANDBY_MODE_NETWORK_STANDBY (1)
#define CLI_STANDBY_MODE_COMMUNICATION (1)

//AUTO_SHUTDOWN
#define CLI_AUTO_SHUTDOWN_OFF (0)
#define CLI_AUTO_SHUTDOWN_5MIN (1)
#define CLI_AUTO_SHUTDOWN_10MIN (2)
#define CLI_AUTO_SHUTDOWN_15MIN (3)
#define CLI_AUTO_SHUTDOWN_20MIN (4)
#define CLI_AUTO_SHUTDOWN_25MIN (5)
#define CLI_AUTO_SHUTDOWN_30MIN (6)

//SLEEP_TIMER
#define CLI_SLEEP_TIMER_OFF (0)
#define CLI_SLEEP_TIMER_2HOURS (1)
#define CLI_SLEEP_TIMER_4HOURS (2)
#define CLI_SLEEP_TIMER_6HOURS (3)

//SERIAL_PORT_BAUD_RATE
#define CLI_SERIAL_PORT_BAUD_RATE_1200 (0)
#define CLI_SERIAL_PORT_BAUD_RATE_2400 (1)
#define CLI_SERIAL_PORT_BAUD_RATE_4800 (2)
#define CLI_SERIAL_PORT_BAUD_RATE_9600 (3)
#define CLI_SERIAL_PORT_BAUD_RATE_19200 (5)
#define CLI_SERIAL_PORT_BAUD_RATE_38400 (6)
#define CLI_SERIAL_PORT_BAUD_RATE_57600 (7)
#define CLI_SERIAL_PORT_BAUD_RATE_115200 (8)

//SERIAL_PORT_PATH
#define CLI_SERIAL_PORT_PATH_RS232 (0)
#define CLI_SERIAL_PORT_PATH_HDBASET (1)
#define CLI_SERIAL_PORT_PATH_SLOT1 (2)
#define CLI_SERIAL_PORT_PATH_SLOT2 (3)

//SERIAL_PORT_PATH_FROM
#define CLI_SERIAL_PORT_PATH_FROM_SLOT1 (0)
#define CLI_SERIAL_PORT_PATH_FROM_SLOT2 (1)

//KEYPAD_BACKLIGHT
#define CLI_KEYPAD_BACKLIGHT_5_SECS (0)
#define CLI_KEYPAD_BACKLIGHT_10_SECS (1)
#define CLI_KEYPAD_BACKLIGHT_20_SECS (2)
#define CLI_KEYPAD_BACKLIGHT_30_SECS (3)
#define CLI_KEYPAD_BACKLIGHT_ALWAYS_ON (4)
#define CLI_KEYPAD_BACKLIGHT_ALWAYS_OFF (5)

//STATUS_LED
#define CLI_STATUS_LED_ALWAYS_ON (0)
#define CLI_STATUS_LED_ALWAYS_OFF (1)
#define CLI_STATUS_LED_WARNING_ERRORS_ONLY (2)

//WALL_COLOR
#define CLI_WALL_COLOR_WHITE (0)
#define CLI_WALL_COLOR_GRAY130 (1)
#define CLI_WALL_COLOR_LIGHT_YELLOW (2)

//POWER_MODE
#define CLI_POWER_MODE_CONSTANT_POWER (0)
#define CLI_POWER_MODE_CONSTANT_INTENSITY (1)
#define CLI_POWER_MODE_ECO1 (2)
#define CLI_POWER_MODE_ECO2 (3)

//PIP_SIZE
#define CLI_PIP_SIZE_SMALL (0)
#define CLI_PIP_SIZE_MEDIUM (1)
#define CLI_PIP_SIZE_LARGE (2)

//MAIN_LAYOUT
#define CLI_MAIN_LAYOUT_PBP_MAIN_LEFT (0)
#define CLI_MAIN_LAYOUT_PBP_MAIN_TOP (1)
#define CLI_MAIN_LAYOUT_PBP_MAIN_RIGHT (2)
#define CLI_MAIN_LAYOUT_PBP_MAIN_BOTTOM (3)
#define CLI_MAIN_LAYOUT_PIP_BOTTOM_RIGHT (4)
#define CLI_MAIN_LAYOUT_PIP_BOTTOM_LEFT (5)
#define CLI_MAIN_LAYOUT_PIP_TOP_LEFT (6)
#define CLI_MAIN_LAYOUT_PIP_TOP_RIGHT (7)

//INPUT_KEY
#define CLI_INPUT_KEY_CHANGE_SOURCE (0)
#define CLI_INPUT_KEY_LIST_ALL_SOURCE (1)
#define CLI_INPUT_KEY_AUTO_SOURCE (2)

//COLOR_TEMPERATURE
#define CLI_COLOR_TEMPERATURE_WARMEST (0)
#define CLI_COLOR_TEMPERATURE_WARM (1)
#define CLI_COLOR_TEMPERATURE_COOL (2)

//BLENDING_GAMMA
#define CLI_BLENDING_GAMMA_1_8 (0)
#define CLI_BLENDING_GAMMA_1_9 (1)
#define CLI_BLENDING_GAMMA_2_0 (2)
#define CLI_BLENDING_GAMMA_2_1 (3)
#define CLI_BLENDING_GAMMA_2_2 (4)
#define CLI_BLENDING_GAMMA_2_3 (5)
#define CLI_BLENDING_GAMMA_2_4 (6)

//BACKGROUND_COLOR
#define CLI_BACKGROUND_COLOR_BLUE (1)
#define CLI_BACKGROUND_COLOR_BLACK (2)
#define CLI_BACKGROUND_COLOR_WHITE (3)
#define CLI_BACKGROUND_COLOR_LOGO (0)

//BACKUPINPUT_AUTOSWITCH
#define CLI_BACKUPINPUT_AUTOSWITCH_SEAMLESS (0)
#define CLI_BACKUPINPUT_AUTOSWITCH_BACKUP (1)
#define CLI_BACKUPINPUT_AUTOSWITCH_SIGNLE (2)

//EDID_TYPE
#define CLI_EDID_TYPE_V14 (0)
#define CLI_EDID_TYPE_V20 (1)
#define CLI_EDID_TYPE_CUSTOMIZED (2)// x35G2_Bruce_0002

//LAN_PATH SWITCH
#define CLI_LAN_PATH_SWITCH_RJ45 (0)
#define CLI_LAN_PATH_SWITCH_HDBASET (1)

//OSD_TIMEOUT
#define CLI_OSD_TIMEOUT_OFF (0)
#define CLI_OSD_TIMEOUT_60_SEC (1)
#define CLI_OSD_TIMEOUT_180_SEC (2)

//BACKGROUND
#define CLI_BACKGROUND_BLUE (0)
#define CLI_BACKGROUND_BLACK (1)
#define CLI_BACKGROUND_WHITE (2)
#define CLI_BACKGROUND_LOGO (3)

//LIGHT_SOURCE_MODE
#define CLI_LIGHT_SOURCE_MODE_NORMAL (0)
#define CLI_LIGHT_SOURCE_MODE_ECO_MODE (1)
#define CLI_LIGHT_SOURCE_MODE_CUSTOM_MODE (2)

//LENS_MEMORY_SAVE
#define CLI_LENS_MEMORY_SAVE_1 (0)
#define CLI_LENS_MEMORY_SAVE_2 (1)
#define CLI_LENS_MEMORY_SAVE_3 (2)
#define CLI_LENS_MEMORY_SAVE_4 (3)
#define CLI_LENS_MEMORY_SAVE_5 (4)

//LENS_MEMORY_APPLY
#define CLI_LENS_MEMORY_APPLY_1 (0)
#define CLI_LENS_MEMORY_APPLY_2 (1)
#define CLI_LENS_MEMORY_APPLY_3 (2)
#define CLI_LENS_MEMORY_APPLY_4 (3)
#define CLI_LENS_MEMORY_APPLY_5 (4)

#define CLI_LOGO_PATTERN_FACTORY_LOGO   (0)
#define CLI_LOGO_PATTERN_BLUE           (1)
#define CLI_LOGO_PATTERN_BLACK          (2)
#define CLI_LOGO_PATTERN_WHITE          (3)

//LOW LATENCY MODE
#define CLI_LOW_LATENCY_MODE_NORMAL     (0)
#define CLI_LOW_LATENCY_MODE_TYPICAL    (1)
#define CLI_LOW_LATENCY_MODE_ULTRA      (2)

//Detail
#define CLI_DETAIL_MAXIMUM    (0)
#define CLI_DETAIL_HIGH       (1)
#define CLI_DETAIL_NORMAL     (2)
#define CLI_DETAIL_LOW        (3)
#define CLI_DETAIL_MINIMUM    (4)

//HDR Level
#define CLI_HDR_LEVEL_1     (0)
#define CLI_HDR_LEVEL_2     (1)
#define CLI_HDR_LEVEL_3     (2)
#define CLI_HDR_LEVEL_4     (3)

//Clock Mode
#define CLI_CLOCK_MODE_USE_NTP_SERVER   (0)
#define CLI_CLOCK_MODE_MANUAL           (1)

//Update Interval
#define CLI_UPDATE_INTERVAL_HOURLY      (0)
#define CLI_UPDATE_INTERVAL_DAILY       (1)

//HDMI Output
#define CLI_HDMI_OUTPUT_HDMI1      (1)
#define CLI_HDMI_OUTPUT_HDMI2      (2)

//Schedule Copy Event To Weekday
#define CLI_COPY_EVENT_TO_MONDAY        (1)
#define CLI_COPY_EVENT_TO_TUESDAY       (2)
#define CLI_COPY_EVENT_TO_WEDNESDAY     (3)
#define CLI_COPY_EVENT_TO_THURSDAY      (4)
#define CLI_COPY_EVENT_TO_FRIDAY        (5)
#define CLI_COPY_EVENT_TO_SATURDAY      (6)
#define CLI_COPY_EVENT_TO_SUNDAY        (0)

//Geo Memory Save
#define CLI_GEO_SAVE_MEMORY1            (0)
#define CLI_GEO_SAVE_MEMORY2            (1)
#define CLI_GEO_SAVE_MEMORY3            (2)
#define CLI_GEO_SAVE_MEMORY4            (3)

//Geo Memory Apply
#define CLI_GEO_APPLY_OFF               (0)
#define CLI_GEO_APPLY_MEMORY1           (1)
#define CLI_GEO_APPLY_MEMORY2           (2)
#define CLI_GEO_APPLY_MEMORY3           (3)
#define CLI_GEO_APPLY_MEMORY4           (4)

//end of defined(CUSTOM_CHRISTIE)

#elif defined(CUSTOM_OPTOMA)

// CLI_SOURCE
#define CLI_SOURCE_HDMI1 (3)
#define CLI_SOURCE_HDMI2 (4)
#define CLI_SOURCE_DP (6)		//A70Gen2_Julie_0003//A70Gen2_Doulas_0004
#define CLI_SOURCE_3GSDI (7)
#define CLI_SOURCE_HDBASET (8)
#define CLI_SOURCE_12GSDI (9)    //HICC2_Doulas_0027


// CLI_TEST_PATTERN
#define CLI_TEST_PATTERN_OFF (0)
#define CLI_TEST_PATTERN_GREEN_GRID (3)
#define CLI_TEST_PATTERN_MAGENTA_GRID (4)
#define CLI_TEST_PATTERN_WHITE_GRID (1)
#define CLI_TEST_PATTERN_WHITE (2)
#define CLI_TEST_PATTERN_BLACK (11)
#define CLI_TEST_PATTERN_RED (5)
#define CLI_TEST_PATTERN_GREEN (6)
#define CLI_TEST_PATTERN_BLUE (7)
#define CLI_TEST_PATTERN_YELLOW (8)
#define CLI_TEST_PATTERN_MAGENTA (9)
#define CLI_TEST_PATTERN_CYAN (10)
#define CLI_TEST_PATTERN_CHECKERBOARD (14)
#define CLI_TEST_PATTERN_COLORBAR (13)
#define CLI_TEST_PATTERN_4K_FULL_SCREEN (16)

//CLI_SERVICE_TEST_PATTERN
#define CLI_SERVICE_TEST_PATTERN_OFF (0)
#define CLI_SERVICE_TEST_PATTERN_GRID (1)
#define CLI_SERVICE_TEST_PATTERN_WHITE (2)
#define CLI_SERVICE_TEST_PATTERN_BLACK (3)
#define CLI_SERVICE_TEST_PATTERN_CHECKBOARD (4)
#define CLI_SERVICE_TEST_PATTERN_COLORBAR (5)
#define CLI_SERVICE_TEST_PATTERN_RED (6)
#define CLI_SERVICE_TEST_PATTERN_GREEN (7)
#define CLI_SERVICE_TEST_PATTERN_BLUE (8)
#define CLI_SERVICE_TEST_PATTERN_YELLOW (9)
#define CLI_SERVICE_TEST_PATTERN_MAGENTA (10)
#define CLI_SERVICE_TEST_PATTERN_CYAN (11)
#define CLI_SERVICE_TEST_PATTERN_BORESIGHT (12)
#define CLI_SERVICE_TEST_PATTERN_FULL_SCREEN (13)
#define CLI_SERVICE_TEST_PATTERN_13POINTS (14)

//CLI_TWIST_TEST_PATTERN
#define CLI_TWIST_TEST_PATTERN_OFF (0)
#define CLI_TWIST_TEST_PATTERN_GRID (1)
#define CLI_TWIST_TEST_PATTERN_WHITE (2)
#define CLI_TWIST_TEST_PATTERN_BLACK (3)
#define CLI_TWIST_TEST_PATTERN_CHECKERBOARD (4)
#define CLI_TWIST_TEST_PATTERN_COLORBAR (5)
#define CLI_TWIST_TEST_PATTERN_GRAY (6)

//CLI_PICTURE_SETTINGS
#define CLI_PICTURE_SETTINGS_NO_SIGNAL      (0)
#define CLI_PICTURE_SETTINGS_PRESENTATION   (16)//(1)
#define CLI_PICTURE_SETTINGS_HDR            (21)
#define CLI_PICTURE_SETTINGS_HLG            (25)
#define CLI_PICTURE_SETTINGS_CINEMA         (3)
#define CLI_PICTURE_SETTINGS_SRGB           (4)
#define CLI_PICTURE_SETTINGS_BRIGHT         (2)
#define CLI_PICTURE_SETTINGS_DICOMSIM       (13)
#define CLI_PICTURE_SETTINGS_BLENDING       (19)
#define CLI_PICTURE_SETTINGS_3D             (9)
#define CLI_PICTURE_SETTINGS_2D_HIGH_SPEED  (18)
#define CLI_PICTURE_SETTINGS_USER           (5)//(10)
#define CLI_PICTURE_SETTINGS_DICOMSIM_READ  (10)		//A65_OPTOMA_Doulas_0074 ////A35G2_Coda_0061

//CLI_APPLY_USER    //G100_Doulas_0066
#define CLI_PRE_USER_PRESENTATION (31)
#define CLI_PRE_USER_BRIGHT (32)
#define CLI_PRE_USER_CINEMA (33)
#define CLI_PRE_USER_HDR (26)
#define CLI_PRE_USER_SRGB (34)
#define CLI_PRE_USER_DICOMSIM (35)
#define CLI_PRE_USER_BLENDING (36)
#define CLI_PRE_USER_3D (6)
#define CLI_PRE_USER_2D_HIGH_SPEED (37)
//#define CLI_PRE_USER_USER (10)
//#define CLI_PRE_USER_SUPER_RED (11)


//CLI_LANGUAGE
#define CLI_LANGUAGE_ENGLISH (1)
#define CLI_LANGUAGE_CZECH (19)
#define CLI_LANGUAGE_DANISH (24)
#define CLI_LANGUAGE_DUTCH (8)
#define CLI_LANGUAGE_FINNISH (11)
#define CLI_LANGUAGE_FRENCH (3)
#define CLI_LANGUAGE_GERMAN (2)
#define CLI_LANGUAGE_GREEK (12)
#define CLI_LANGUAGE_HUNGARIAN (18)
#define CLI_LANGUAGE_INDONESIAN (26)
#define CLI_LANGUAGE_ITALIAN (4)
#define CLI_LANGUAGE_JAPANESE (15)
#define CLI_LANGUAGE_KOREAN (16)
#define CLI_LANGUAGE_NORWEGIAN (10)
#define CLI_LANGUAGE_POLISH (7)
#define CLI_LANGUAGE_PORTUGUESE (6)
#define CLI_LANGUAGE_ROMANIAN (27)
#define CLI_LANGUAGE_RUSSIAN (17)
#define CLI_LANGUAGE_S_CHINESE (14)
#define CLI_LANGUAGE_SPANISH (5)
#define CLI_LANGUAGE_SWEDISH (9)
#define CLI_LANGUAGE_THAI (21)
#define CLI_LANGUAGE_T_CHINESE (13)
#define CLI_LANGUAGE_TURKISH (22)
#define CLI_LANGUAGE_VIETNAMESE (25)


//CLI_SCALING_MODE
#define CLI_SCALING_MODE_4_3 (1)
#define CLI_SCALING_MODE_16_9 (2)
#define CLI_SCALING_MODE_21_9 (16)
#define CLI_SCALING_MODE_LETTER_BOX (5)
#define CLI_SCALING_MODE_AUTO (7)
#define CLI_SCALING_MODE_NATIVE (6)


//CLI_HOTKEY_SETTING
#define CLI_HOTKEY_SETTINGS_HDMI1 (8)
#define CLI_HOTKEY_SETTINGS_HDMI2 (9)
#define CLI_HOTKEY_SETTINGS_COLOR_MATCHING (13)
#define CLI_HOTKEY_SETTINGS_COLOR_TEMPERATURE (4)
#define CLI_HOTKEY_SETTINGS_PROJECTION_ORIENTATION (14)
#define CLI_HOTKEY_SETTINGS_LIGHT_SOURCE_MODE (15)
#define CLI_HOTKEY_SETTINGS_FREEZE_SCREEN (17)
#define CLI_HOTKEY_SETTINGS_NETWORK_SETUP (20)
#define CLI_HOTKEY_SETTINGS_RESET_SELECTIVE (21)

//CLI_SCREEN_MODE (PIP/PBP)
#define CLI_SCREEN_MODE_OFF (0)
#define CLI_SCREEN_MODE_PIP (1)
#define CLI_SCREEN_MODE_PBP (2)

//CLI_MENU_LOCATION
#define CLI_MENU_LOCATION_TOP_LEFT (1)
#define CLI_MENU_LOCATION_TOP_RIGHT (2)
#define CLI_MENU_LOCATION_CENTER (3)
#define CLI_MENU_LOCATION_BOTTOM_LEFT (4)
#define CLI_MENU_LOCATION_BOTTOM_RIGHT (5)

//OVERSCAN
#define CLI_OVERSCAN_OFF (0)
#define CLI_OVERSCAN_ZOOM (1)
#define CLI_OVERSCAN_CROP (2)

//COLOR_SPACE
#define CLI_COLOR_SPACE_AUTO (1)
#define CLI_COLOR_SPACE_RGB_FULL (2)
#define CLI_COLOR_SPACE_RGB_LIMITED (4)
#define CLI_COLOR_SPACE_YUV_REC709 (5)
#define CLI_COLOR_SPACE_YUV_REC601 (6)

//3D_MODE
#define CLI_3D_MODE_OFF (4)
#define CLI_3D_MODE_ON (0)
#define CLI_3D_MODE_AUTO (1)
#define CLI_3D_MODE_PASSIVE_3D (5)

//3D_FORMAT
#define CLI_3D_FORMAT_AUTO (0)
#define CLI_3D_FORMAT_FRAME_PACKING (1)
#define CLI_3D_FORMAT_SIDE_BY_SIDE (2)
#define CLI_3D_FORMAT_TOP_AND_BOTTOM (3)
#define CLI_3D_FORMAT_FRAME_SEQUENTIAL (4)
#define CLI_3D_FORMAT_OFF (5)
#define CLI_3D_FORMAT_DUALPIPE (6)
#define CLI_3D_FORMAT_4K3D (7)
#define CLI_3D_FORMAT_4K3D_DUALPIPE (8)

//3D_TECH
#define CLI_3D_TECH_DLP_LINK (1)
#define CLI_3D_TECH_3D_SYNC (3)

//3D_2D
#define CLI_3D_2D_3D (0)
#define CLI_3D_2D_2D_LEFT (1)
#define CLI_3D_2D_2D_RIGHT (2)

//3D_SYNC_OUT
#define CLI_3D_SYNC_OUT_TO_EMITTER (0)
#define CLI_3D_SYNC_OUT_TO_NEXT_PROJECTOR (1)

//3D_LR_REFERENCE
#define CLI_3D_LR_REFERENCE_1ST_FRAME (0)
#define CLI_3D_LR_REFERENCE_FIELD_GPIO (1)

//3D_SYNC_TYPE
#define CLI_3D_SYNC_TYPE_AUTO (0)
#define CLI_3D_SYNC_TYPE_INTERNAL (1)
#define CLI_3D_SYNC_TYPE_EXTERNAL (2)

//CONTRAST_ENHANCEMENT
#define CLI_CONTRAST_ENHANCEMENT_OFF (0)
#define CLI_CONTRAST_ENHANCEMENT_CE1 (1)
#define CLI_CONTRAST_ENHANCEMENT_CE2 (2)

//GAMMA
#define CLI_GAMMA_FILM (1)
#define CLI_GAMMA_GRAPHICS (3)
#define CLI_GAMMA_1_8 (5)
#define CLI_GAMMA_2_0 (6)
#define CLI_GAMMA_2_2 (7)
#define CLI_GAMMA_2_4 (12)
#define CLI_GAMMA_2_6 (8)
#define CLI_GAMMA_VIVID (21)
#define CLI_GAMMA_3D (9)
#define CLI_GAMMA_BLACKBOARD (10)
#define CLI_GAMMA_DICOM (11)
#define CLI_GAMMA_HDR (22)

//EDGE_ENHANCEMENT
#define CLI_EDGE_ENHANCEMENT_OFF (0)
#define CLI_EDGE_ENHANCEMENT_NORMAL (1)
#define CLI_EDGE_ENHANCEMENT_MAXIMUM (2)

//COLOR_WHEEL_SPEED
#define CLI_COLOR_WHEEL_SPEED_2X (0)
#define CLI_COLOR_WHEEL_SPEED_3X (1)

//LENS_TYPE
#define CLI_LENS_TYPE_NA (0)
#define CLI_LENS_TYPE_A20 (1)
#define CLI_LENS_TYPE_A21 (2)
#define CLI_LENS_TYPE_A22 (3)
#define CLI_LENS_TYPE_A23 (4)
#define CLI_LENS_TYPE_A24 (5)
#define CLI_LENS_TYPE_A25 (6)
#define CLI_LENS_TYPE_A26 (7)

//CEILING_MOUNT
#define CLI_CEILING_MOUNT_AUTO (3)
#define CLI_CEILING_MOUNT_ON (1)
#define CLI_CEILING_MOUNT_OFF (0)

//REAR_PROJECTION
#define CLI_REAR_PROJECTION_FRONT (0)
#define CLI_REAR_PROJECTION_REAR (1)

//SPLASH_STARTUP
#define CLI_SPLASH_STARTUP_FACTORY_LOGO (0)
#define CLI_SPLASH_STARTUP_BLUE (1)
#define CLI_SPLASH_STARTUP_BLACK (2)
#define CLI_SPLASH_STARTUP_WHITE (3)

//STANDBY_MODE
#define CLI_STANDBY_MODE_ECO (0)
#define CLI_STANDBY_MODE_ACTIVE (1)
#define CLI_STANDBY_MODE_COMMUNICATION (3)

//AUTO_SHUTDOWN
#define CLI_AUTO_SHUTDOWN_OFF (0)
#define CLI_AUTO_SHUTDOWN_5MIN (1)
#define CLI_AUTO_SHUTDOWN_10MIN (2)
#define CLI_AUTO_SHUTDOWN_15MIN (3)
#define CLI_AUTO_SHUTDOWN_20MIN (4)
#define CLI_AUTO_SHUTDOWN_25MIN (5)
#define CLI_AUTO_SHUTDOWN_30MIN (6)

//SLEEP_TIMER
#define CLI_SLEEP_TIMER_OFF (0)
#define CLI_SLEEP_TIMER_2HOURS (1)
#define CLI_SLEEP_TIMER_4HOURS (2)
#define CLI_SLEEP_TIMER_6HOURS (3)

//SERIAL_PORT_BAUD_RATE
#define CLI_SERIAL_PORT_BAUD_RATE_1200 (0)
#define CLI_SERIAL_PORT_BAUD_RATE_2400 (1)
#define CLI_SERIAL_PORT_BAUD_RATE_4800 (2)
#define CLI_SERIAL_PORT_BAUD_RATE_9600 (3)
#define CLI_SERIAL_PORT_BAUD_RATE_19200 (5)
#define CLI_SERIAL_PORT_BAUD_RATE_38400 (6)
#define CLI_SERIAL_PORT_BAUD_RATE_57600 (7)
#define CLI_SERIAL_PORT_BAUD_RATE_115200 (8)

//SERIAL_PORT_PATH
#define CLI_SERIAL_PORT_PATH_RS232 (0)
#define CLI_SERIAL_PORT_PATH_HDBASET (1)
#define CLI_SERIAL_PORT_PATH_SLOT1 (2)
#define CLI_SERIAL_PORT_PATH_SLOT2 (3)

//SERIAL_PORT_PATH_FROM
#define CLI_SERIAL_PORT_PATH_FROM_SLOT1 (0)
#define CLI_SERIAL_PORT_PATH_FROM_SLOT2 (1)

//KEYPAD_BACKLIGHT
#define CLI_KEYPAD_BACKLIGHT_5_SECS (0)
#define CLI_KEYPAD_BACKLIGHT_10_SECS (1)
#define CLI_KEYPAD_BACKLIGHT_20_SECS (2)
#define CLI_KEYPAD_BACKLIGHT_30_SECS (3)
#define CLI_KEYPAD_BACKLIGHT_ALWAYS_ON (4)
#define CLI_KEYPAD_BACKLIGHT_ALWAYS_OFF (5)

//STATUS_LED
#define CLI_STATUS_LED_ALWAYS_ON (0)
#define CLI_STATUS_LED_ALWAYS_OFF (1)
#define CLI_STATUS_LED_WARNING_ERRORS_ONLY (2)

//WALL_COLOR
#define CLI_WALL_COLOR_OFF          (0)
#define CLI_WALL_COLOR_BLACKBOARD   (1)
#define CLI_WALL_COLOR_LIGHT_YELLOW (7)
#define CLI_WALL_COLOR_LIGHT_GREEN  (3)
#define CLI_WALL_COLOR_LIGHT_BLUE   (4)
#define CLI_WALL_COLOR_PINK         (5)
#define CLI_WALL_COLOR_GRAY         (6)

//POWER_MODE
#define CLI_POWER_MODE_CONSTANT_POWER   (1)
#define CLI_POWER_MODE_ECO              (2)
#define CLI_POWER_MODE_CUSTOM_MODE      (6)

//PIP_SIZE
#define CLI_PIP_SIZE_SMALL (0)
#define CLI_PIP_SIZE_MEDIUM (1)
#define CLI_PIP_SIZE_LARGE (2)

//MAIN_LAYOUT
#define CLI_MAIN_LAYOUT_PBP_MAIN_LEFT (5)	//HICC2_Sammy_0002
#define CLI_MAIN_LAYOUT_PBP_MAIN_TOP (6)
#define CLI_MAIN_LAYOUT_PBP_MAIN_RIGHT (7)
#define CLI_MAIN_LAYOUT_PBP_MAIN_BOTTOM (8)
#define CLI_MAIN_LAYOUT_PIP_BOTTOM_RIGHT (4)
#define CLI_MAIN_LAYOUT_PIP_BOTTOM_LEFT (3)
#define CLI_MAIN_LAYOUT_PIP_TOP_LEFT (1)
#define CLI_MAIN_LAYOUT_PIP_TOP_RIGHT (2)


//INPUT_KEY
#define CLI_INPUT_KEY_CHANGE_SOURCE (0)
#define CLI_INPUT_KEY_LIST_ALL_SOURCE (1)
#define CLI_INPUT_KEY_AUTO_SOURCE (2)

//COLOR_TEMPERATURE
#define CLI_COLOR_TEMPERATURE_WARM (4)
#define CLI_COLOR_TEMPERATURE_STANDARD (1)
#define CLI_COLOR_TEMPERATURE_COOL (2)
#define CLI_COLOR_TEMPERATURE_COLD (3)

//BLENDING_GAMMA
#define CLI_BLENDING_GAMMA_1_8 (0)
#define CLI_BLENDING_GAMMA_1_9 (1)
#define CLI_BLENDING_GAMMA_2_0 (2)
#define CLI_BLENDING_GAMMA_2_1 (3)
#define CLI_BLENDING_GAMMA_2_2 (4)
#define CLI_BLENDING_GAMMA_2_3 (5)
#define CLI_BLENDING_GAMMA_2_4 (6)

//BACKGROUND_COLOR
#define CLI_BACKGROUND_COLOR_BLACK (0)
#define CLI_BACKGROUND_COLOR_BLUE (1)
#define CLI_BACKGROUND_COLOR_RED (3)
#define CLI_BACKGROUND_COLOR_GREEN (4)
#define CLI_BACKGROUND_COLOR_GRAY (6)
#define CLI_BACKGROUND_COLOR_WHITE (5)
#define CLI_BACKGROUND_COLOR_LOGO (7)

//BACKUPINPUT_AUTOSWITCH
#define CLI_BACKUPINPUT_AUTOSWITCH_SEAMLESS (0)
#define CLI_BACKUPINPUT_AUTOSWITCH_BACKUP (1)
#define CLI_BACKUPINPUT_AUTOSWITCH_SIGNLE (2)

//EDID_TYPE
#define CLI_EDID_TYPE_V14 (0)
#define CLI_EDID_TYPE_V20 (1)
#define CLI_EDID_TYPE_CUSTOMIZED (2) //HICC2_Doulas_0025

//LAN_PATH SWITCH
#define CLI_LAN_PATH_SWITCH_RJ45 (0)
#define CLI_LAN_PATH_SWITCH_HDBASET (1)

//OSD_TIMEOUT
#define CLI_OSD_TIMEOUT_OFF (0)
#define CLI_OSD_TIMEOUT_5_SEC (1)
#define CLI_OSD_TIMEOUT_10_SEC (3)
#define CLI_OSD_TIMEOUT_20_SEC (7)
#define CLI_OSD_TIMEOUT_30_SEC (5)
#define CLI_OSD_TIMEOUT_60_SEC (6)

//BACKGROUND
#define CLI_BACKGROUND_BLUE (0)
#define CLI_BACKGROUND_BLACK (1)
#define CLI_BACKGROUND_WHITE (2)
#define CLI_BACKGROUND_LOGO (3)

//LIGHT_SOURCE_MODE
#define CLI_LIGHT_SOURCE_MODE_NORMAL (0)
#define CLI_LIGHT_SOURCE_MODE_ECO_MODE (1)
#define CLI_LIGHT_SOURCE_MODE_CUSTOM_MODE (2)

//LENS_MEMORY_SAVE
#define CLI_LENS_MEMORY_SAVE_1 (0)
#define CLI_LENS_MEMORY_SAVE_2 (1)
#define CLI_LENS_MEMORY_SAVE_3 (2)
#define CLI_LENS_MEMORY_SAVE_4 (3)
#define CLI_LENS_MEMORY_SAVE_5 (4)

//LENS_MEMORY_APPLY
#define CLI_LENS_MEMORY_APPLY_1 (0)
#define CLI_LENS_MEMORY_APPLY_2 (1)
#define CLI_LENS_MEMORY_APPLY_3 (2)
#define CLI_LENS_MEMORY_APPLY_4 (3)
#define CLI_LENS_MEMORY_APPLY_5 (4)

#define CLI_LOGO_PATTERN_FACTORY_LOGO   (0)
#define CLI_LOGO_PATTERN_BLUE           (1)
#define CLI_LOGO_PATTERN_BLACK          (2)
#define CLI_LOGO_PATTERN_WHITE          (3)

//LOW LATENCY MODE
#define CLI_LOW_LATENCY_MODE_NORMAL     (0)
#define CLI_LOW_LATENCY_MODE_2D_ULTRA   (1)
#define CLI_LOW_LATENCY_MODE_ULTRA      (1)

//Detail
#define CLI_DETAIL_MAXIMUM    (0)
#define CLI_DETAIL_HIGH       (1)
#define CLI_DETAIL_NORMAL     (2)
#define CLI_DETAIL_LOW        (3)
#define CLI_DETAIL_MINIMUM    (4)

//HDR Level
#define CLI_HDR_LEVEL_1     (0)
#define CLI_HDR_LEVEL_2     (1)
#define CLI_HDR_LEVEL_3     (2)
#define CLI_HDR_LEVEL_4     (3)

//Clock Mode
#define CLI_CLOCK_MODE_USE_NTP_SERVER   (0)
#define CLI_CLOCK_MODE_MANUAL           (1)

//Update Interval
#define CLI_UPDATE_INTERVAL_HOURLY      (0)
#define CLI_UPDATE_INTERVAL_DAILY       (1)

//HDMI Output
#define CLI_HDMI_OUTPUT_HDMI1      (1)
#define CLI_HDMI_OUTPUT_HDMI2      (2)

//Schedule Copy Event To Weekday
#define CLI_COPY_EVENT_TO_MONDAY        (1)
#define CLI_COPY_EVENT_TO_TUESDAY       (2)
#define CLI_COPY_EVENT_TO_WEDNESDAY     (3)
#define CLI_COPY_EVENT_TO_THURSDAY      (4)
#define CLI_COPY_EVENT_TO_FRIDAY        (5)
#define CLI_COPY_EVENT_TO_SATURDAY      (6)
#define CLI_COPY_EVENT_TO_SUNDAY        (0)


//Geo Memory Save
#define CLI_GEO_SAVE_MEMORY1            (1)
#define CLI_GEO_SAVE_MEMORY2            (2)
#define CLI_GEO_SAVE_MEMORY3            (3)
#define CLI_GEO_SAVE_MEMORY4            (4)
#define CLI_GEO_SAVE_MEMORY5            (5)

//Geo Memory Apply
#define CLI_GEO_APPLY_OFF               (0)
#define CLI_GEO_APPLY_MEMORY1           (1)
#define CLI_GEO_APPLY_MEMORY2           (2)
#define CLI_GEO_APPLY_MEMORY3           (3)
#define CLI_GEO_APPLY_MEMORY4           (4)
#define CLI_GEO_APPLY_MEMORY5           (5)

// Input Key
#define CLI_SOURCE_KEY_LIST_ALL_SOURCE  (0)
#define CLI_SOURCE_KEY_AUTO_SOURCE      (1)

// Logo Change
#define CLI_CHANGE_LOGO_DEFAULT         (1)
#define CLI_CHANGE_LOGO_NEUTRAL         (3)
#define CLI_CHANGE_LOGO_USER            (4)
#define CLI_CHANGE_LOGO_CAPTURED        (2)

// Digital Zoom Propotional
#define CLI_DIGITAL_ZOOM_PROPORTIONAL_OFF   (0)
#define CLI_DIGITAL_ZOOM_PROPORTIONAL_ON    (1)
#define CLI_DIGITAL_ZOOM_RESET 				(9)	//HICC2_Sammy_0002

// Network Reset / Apply
#define CLI_NETWORK_SETUP_RESET             (1) ////A35G2_Coda_0061
#define CLI_NETWORK_SETUP_APPLY             (9)

//BLACK LEVEL ENABLE
#define CLI_BLACK_LEVEL_TOP_OFF 	(6)
#define CLI_BLACK_LEVEL_BOTTOM_OFF 	(4)
#define CLI_BLACK_LEVEL_TOP_ON 		(5)
#define CLI_BLACK_LEVEL_BOTTOM_ON 	(3)

//BLACK LEVEL BRIGHTNESS
#define CLI_BLACK_LEVEL_BRIGHTNESS_BOTTOM_ADD 	(1)
#define CLI_BLACK_LEVEL_BRIGHTNESS_BOTTOM_DEL 	(2)
#define CLI_BLACK_LEVEL_BRIGHTNESS_TOP_ADD 		(3)
#define CLI_BLACK_LEVEL_BRIGHTNESS_TOP_DEL 		(4)

//Warp Control
#define CLI_WARP_CONTROL_BASIC 		(1)
#define CLI_WARP_CONTROL_ADVANCED 	(5)
#define CLI_WARP_CONTROL_AP 		(2)

//SNMP Control
#define CLI_SNMP_FAN_ERROR_EMAIL 			(1)	
#define CLI_SNMP_FAN_ERROR_OFF 				(2)	
#define CLI_SNMP_POWER_ONOFF_EMAIL 			(3)	
#define CLI_SNMP_POWER_ONOFF_OFF 			(4)	
#define CLI_SNMP_VIDEO_LOSS_EMAIL 			(5)	
#define CLI_SNMP_VIDEO_LOSS_OFF 			(6)
#define CLI_SNMP_LASER_EMAIL 				(7)	
#define CLI_SNMP_LASER_OFF 					(8)

//end of defined(CUSTOM_OPTOMA)

#else
// CLI_SOURCE
#define CLI_SOURCE_HDMI1 (3)
#define CLI_SOURCE_HDMI2 (4)
#define CLI_SOURCE_DVI (5)
#define CLI_SOURCE_DP (6)
#define CLI_SOURCE_3GSDI (7)
#define CLI_SOURCE_HDBASET (8)

// CLI_TEST_PATTERN
#define CLI_TEST_PATTERN_OFF (0)
#define CLI_TEST_PATTERN_GRID (1)
#define CLI_TEST_PATTERN_WHITE (2)
#define CLI_TEST_PATTERN_BLACK (3)
#define CLI_TEST_PATTERN_CHECKERBOARD (4)
#define CLI_TEST_PATTERN_COLORBAR (5)

//CLI_SERVICE_TEST_PATTERN
#define CLI_SERVICE_TEST_PATTERN_OFF (0)
#define CLI_SERVICE_TEST_PATTERN_GRID (1)
#define CLI_SERVICE_TEST_PATTERN_WHITE (2)
#define CLI_SERVICE_TEST_PATTERN_BLACK (3)
#define CLI_SERVICE_TEST_PATTERN_CHECKBOARD (4)
#define CLI_SERVICE_TEST_PATTERN_COLORBAR (5)
#define CLI_SERVICE_TEST_PATTERN_RED (6)
#define CLI_SERVICE_TEST_PATTERN_GREEN (7)
#define CLI_SERVICE_TEST_PATTERN_BLUE (8)
#define CLI_SERVICE_TEST_PATTERN_YELLOW (9)
#define CLI_SERVICE_TEST_PATTERN_MAGENTA (10)
#define CLI_SERVICE_TEST_PATTERN_CYAN (11)
#define CLI_SERVICE_TEST_PATTERN_BORESIGHT (12)
#define CLI_SERVICE_TEST_PATTERN_FULL_SCREEN (13)
#define CLI_SERVICE_TEST_PATTERN_13POINTS (14)

//CLI_TWIST_TEST_PATTERN
#define CLI_TWIST_TEST_PATTERN_OFF (0)
#define CLI_TWIST_TEST_PATTERN_GRID (1)
#define CLI_TWIST_TEST_PATTERN_WHITE (2)
#define CLI_TWIST_TEST_PATTERN_BLACK (3)
#define CLI_TWIST_TEST_PATTERN_CHECKERBOARD (4)
#define CLI_TWIST_TEST_PATTERN_COLORBAR (5)
#define CLI_TWIST_TEST_PATTERN_GRAY (6)

//CLI_PICTURE_SETTINGS
#define CLI_PICTURE_SETTINGS_VIDEO 		    (0)
#define CLI_PICTURE_SETTINGS_BRIGHT 		(1)
#define CLI_PICTURE_SETTINGS_ENHANCED 		(2)
#define CLI_PICTURE_SETTINGS_REC709 		(3)
#define CLI_PICTURE_SETTINGS_DICOMSIM 		(4)
#define CLI_PICTURE_SETTINGS_BLENDING 		(5)
#define CLI_PICTURE_SETTINGS_HDR 			(6)
#define CLI_PICTURE_SETTINGS_3D 			(7)
#define CLI_PICTURE_SETTINGS_2D_HIGH_SPEED 	(8)
#define CLI_PICTURE_SETTINGS_USER 			(9)

//CLI_APPLY_USER    //G100_Doulas_0066
#define CLI_PRE_USER_VIDEO 		    (0)
#define CLI_PRE_USER_BRIGHT 		(1)
#define CLI_PRE_USER_ENHANCED 		(2)
#define CLI_PRE_USER_REC709 		(3)
#define CLI_PRE_USER_DICOMSIM 		(4)
#define CLI_PRE_USER_BLENDING 		(5)
#define CLI_PRE_USER_HDR 			(6)
#define CLI_PRE_USER_3D 			(7)
#define CLI_PRE_USER_2D_HIGH_SPEED 	(8)

//CLI_LANGUAGE
#define CLI_LANGUAGE_ENGLISH (0)
#define CLI_LANGUAGE_FRENCH (1)
#define CLI_LANGUAGE_SPANISH (2)
#define CLI_LANGUAGE_GERMAN (3)
#define CLI_LANGUAGE_ITALIAN (4)
#define CLI_LANGUAGE_POLSKI (5)
#define CLI_LANGUAGE_RUSSIAN (6)
#define CLI_LANGUAGE_S_CHINESE (7)
#define CLI_LANGUAGE_T_CHINESE (8)
#define CLI_LANGUAGE_JAPANESE (9)
#define CLI_LANGUAGE_KOREAN (10)

//CLI_SCALING_MODE
#define CLI_SCALING_MODE_AUTO (0)
#define CLI_SCALING_MODE_NATIVE (1)
#define CLI_SCALING_MODE_4_3 (2)
#define CLI_SCALING_MODE_LETTER_BOX (3)
#define CLI_SCALING_MODE_FULL_SIZE (4)
#define CLI_SCALING_MODE_FULL_WIDTH (5)
#define CLI_SCALING_MODE_FULL_HEIGHT (6)
#define CLI_SCALING_MODE_CUSTOM (7)
#define CLI_SCALING_MODE_3D (8)
#define CLI_SCALING_MODE_21_9 (9)

//CLI_HOTKEY_SETTING
#define CLI_HOTKEY_SETTINGS_SIZE_PRESETS (0)
#define CLI_HOTKEY_SETTINGS_PICTURE_SETTINGS (1)
#define CLI_HOTKEY_SETTINGS_DEFAULT_VALUE (2)
#define CLI_HOTKEY_SETTINGS_DETAIL (3)
#define CLI_HOTKEY_SETTINGS_CONTRAST_ENHANCEMENT (4)
#define CLI_HOTKEY_SETTINGS_LIGHT_SOURCE_MODE (5)
#define CLI_HOTKEY_SETTINGS_FREEZE_SCREEN (6)
#define CLI_HOTKEY_SETTINGS_INFORMATION (7)
#define CLI_HOTKEY_SETTINGS_WARPBLEND_DISABLE (8)

//CLI_SCREEN_MODE (PIP/PBP)
#define CLI_SCREEN_MODE_OFF (0)
#define CLI_SCREEN_MODE_PIP (1)
#define CLI_SCREEN_MODE_PBP (2)

//CLI_MENU_LOCATION
#define CLI_MENU_LOCATION_TOP_LEFT (0)
#define CLI_MENU_LOCATION_TOP_RIGHT (1)
#define CLI_MENU_LOCATION_CENTER (2)
#define CLI_MENU_LOCATION_BOTTOM_LEFT (3)
#define CLI_MENU_LOCATION_BOTTOM_RIGHT (4)

//OVERSCAN
#define CLI_OVERSCAN_OFF (0)
#define CLI_OVERSCAN_ZOOM (1)
#define CLI_OVERSCAN_CROP (2)

//COLOR_SPACE
#define CLI_COLOR_SPACE_AUTO (0)
#define CLI_COLOR_SPACE_RGB_FULL (1)
#define CLI_COLOR_SPACE_RGB_LIMITED (2)
#define CLI_COLOR_SPACE_YUV_REC709 (3)
#define CLI_COLOR_SPACE_YUV_REC601 (4)

//3D_MODE
#define CLI_3D_MODE_ACTIVE_3D   (0) //active
#define CLI_3D_MODE_PASSIVE_3D  (1) //passive
//#define CLI_3D_MODE_OFF (2)

//3D_FORMAT
#define CLI_3D_FORMAT_AUTO (0)
#define CLI_3D_FORMAT_FRAME_PACKING (1)
#define CLI_3D_FORMAT_SIDE_BY_SIDE (2)
#define CLI_3D_FORMAT_TOP_AND_BOTTOM (3)
#define CLI_3D_FORMAT_FRAME_SEQUENTIAL (4)
#define CLI_3D_FORMAT_OFF (5)
#define CLI_3D_FORMAT_DUALPIPE (6)
#define CLI_3D_FORMAT_4K3D (7)
#define CLI_3D_FORMAT_4K3D_DUALPIPE (8)

//3D_TECH
#define CLI_3D_TECH_DLP_LINK (0)
#define CLI_3D_TECH_3D_SYNC (1)

//3D_2D
#define CLI_3D_2D_3D (0)
#define CLI_3D_2D_2D_LEFT (1)
#define CLI_3D_2D_2D_RIGHT (2)

//3D_SYNC_OUT
#define CLI_3D_SYNC_OUT_TO_EMITTER (0)
#define CLI_3D_SYNC_OUT_TO_NEXT_PROJECTOR (1)

//3D_LR_REFERENCE
#define CLI_3D_LR_REFERENCE_1ST_FRAME (0)
#define CLI_3D_LR_REFERENCE_FIELD_GPIO (1)

//3D_SYNC_TYPE
#define CLI_3D_SYNC_TYPE_AUTO (0)
#define CLI_3D_SYNC_TYPE_INTERNAL (1)
#define CLI_3D_SYNC_TYPE_EXTERNAL (2)

//CONTRAST_ENHANCEMENT
#define CLI_CONTRAST_ENHANCEMENT_OFF (0)
#define CLI_CONTRAST_ENHANCEMENT_CE1 (1)
#define CLI_CONTRAST_ENHANCEMENT_CE2 (2)

//GAMMA
#define CLI_GAMMA_VIDEO     (0)
#define CLI_GAMMA_FILM      (1)
#define CLI_GAMMA_BRIGHT    (2)
#define CLI_GAMMA_CRT       (3)
#define CLI_GAMMA_DICOM     (4)
#define CLI_GAMMA_HDR       (5)

//EDGE_ENHANCEMENT
#define CLI_EDGE_ENHANCEMENT_OFF (0)
#define CLI_EDGE_ENHANCEMENT_NORMAL (1)
#define CLI_EDGE_ENHANCEMENT_MAXIMUM (2)

//COLOR_WHEEL_SPEED
#define CLI_COLOR_WHEEL_SPEED_2X (0)
#define CLI_COLOR_WHEEL_SPEED_3X (1)

//LENS_TYPE
#define CLI_LENS_TYPE_NA (0)
#define CLI_LENS_TYPE_A20 (1)
#define CLI_LENS_TYPE_A21 (2)
#define CLI_LENS_TYPE_A22 (3)
#define CLI_LENS_TYPE_A23 (4)
#define CLI_LENS_TYPE_A24 (5)
#define CLI_LENS_TYPE_A25 (6)
#define CLI_LENS_TYPE_A26 (7)

//CEILING_MOUNT
#define CLI_CEILING_MOUNT_OFF (0)
#define CLI_CEILING_MOUNT_ON (1)
#define CLI_CEILING_MOUNT_AUTO (2)

//REAR_PROJECTION
#define CLI_REAR_PROJECTION_FRONT (0)
#define CLI_REAR_PROJECTION_REAR (1)

//SPLASH_STARTUP
#define CLI_SPLASH_STARTUP_FACTORY_LOGO (0)
#define CLI_SPLASH_STARTUP_BLUE (1)
#define CLI_SPLASH_STARTUP_BLACK (2)
#define CLI_SPLASH_STARTUP_WHITE (3)

//STANDBY_MODE
#define CLI_STANDBY_MODE_STANDBY (0)
//#define CLI_STANDBY_MODE_NETWORK_STANDBY (1)
#define CLI_STANDBY_MODE_COMMUNICATION (1)

//AUTO_SHUTDOWN
#define CLI_AUTO_SHUTDOWN_OFF (0)
#define CLI_AUTO_SHUTDOWN_5MIN (1)
#define CLI_AUTO_SHUTDOWN_10MIN (2)
#define CLI_AUTO_SHUTDOWN_15MIN (3)
#define CLI_AUTO_SHUTDOWN_20MIN (4)
#define CLI_AUTO_SHUTDOWN_25MIN (5)
#define CLI_AUTO_SHUTDOWN_30MIN (6)

//SLEEP_TIMER
#define CLI_SLEEP_TIMER_OFF (0)
#define CLI_SLEEP_TIMER_2HOURS (1)
#define CLI_SLEEP_TIMER_4HOURS (2)
#define CLI_SLEEP_TIMER_6HOURS (3)

//SERIAL_PORT_BAUD_RATE
#define CLI_SERIAL_PORT_BAUD_RATE_1200 (0)
#define CLI_SERIAL_PORT_BAUD_RATE_2400 (1)
#define CLI_SERIAL_PORT_BAUD_RATE_4800 (2)
#define CLI_SERIAL_PORT_BAUD_RATE_9600 (3)
#define CLI_SERIAL_PORT_BAUD_RATE_19200 (5)
#define CLI_SERIAL_PORT_BAUD_RATE_38400 (6)
#define CLI_SERIAL_PORT_BAUD_RATE_57600 (7)
#define CLI_SERIAL_PORT_BAUD_RATE_115200 (8)

//SERIAL_PORT_PATH
#define CLI_SERIAL_PORT_PATH_RS232 (0)
#define CLI_SERIAL_PORT_PATH_HDBASET (1)
#define CLI_SERIAL_PORT_PATH_SLOT1 (2)
#define CLI_SERIAL_PORT_PATH_SLOT2 (3)

//SERIAL_PORT_PATH_FROM
#define CLI_SERIAL_PORT_PATH_FROM_SLOT1 (0)
#define CLI_SERIAL_PORT_PATH_FROM_SLOT2 (1)

//KEYPAD_BACKLIGHT
#define CLI_KEYPAD_BACKLIGHT_5_SECS (0)
#define CLI_KEYPAD_BACKLIGHT_10_SECS (1)
#define CLI_KEYPAD_BACKLIGHT_20_SECS (2)
#define CLI_KEYPAD_BACKLIGHT_30_SECS (3)
#define CLI_KEYPAD_BACKLIGHT_ALWAYS_ON (4)
#define CLI_KEYPAD_BACKLIGHT_ALWAYS_OFF (5)

//STATUS_LED
#define CLI_STATUS_LED_ALWAYS_ON (0)
#define CLI_STATUS_LED_ALWAYS_OFF (1)
#define CLI_STATUS_LED_WARNING_ERRORS_ONLY (2)

//WALL_COLOR
#define CLI_WALL_COLOR_WHITE (0)
#define CLI_WALL_COLOR_GRAY130 (1)
#define CLI_WALL_COLOR_LIGHT_YELLOW (2)

//POWER_MODE
#define CLI_POWER_MODE_CONSTANT_POWER (0)
#define CLI_POWER_MODE_CONSTANT_INTENSITY (1)
#define CLI_POWER_MODE_ECO1 (2)
#define CLI_POWER_MODE_ECO2 (3)

//PIP_SIZE
#define CLI_PIP_SIZE_SMALL (0)
#define CLI_PIP_SIZE_MEDIUM (1)
#define CLI_PIP_SIZE_LARGE (2)

//MAIN_LAYOUT
#define CLI_MAIN_LAYOUT_PBP_MAIN_LEFT (0)
#define CLI_MAIN_LAYOUT_PBP_MAIN_TOP (1)
#define CLI_MAIN_LAYOUT_PBP_MAIN_RIGHT (2)
#define CLI_MAIN_LAYOUT_PBP_MAIN_BOTTOM (3)
#define CLI_MAIN_LAYOUT_PIP_BOTTOM_RIGHT (4)
#define CLI_MAIN_LAYOUT_PIP_BOTTOM_LEFT (5)
#define CLI_MAIN_LAYOUT_PIP_TOP_LEFT (6)
#define CLI_MAIN_LAYOUT_PIP_TOP_RIGHT (7)

//INPUT_KEY
#define CLI_INPUT_KEY_CHANGE_SOURCE (0)
#define CLI_INPUT_KEY_LIST_ALL_SOURCE (1)
#define CLI_INPUT_KEY_AUTO_SOURCE (2)

//COLOR_TEMPERATURE
#define CLI_COLOR_TEMPERATURE_WARMEST (0)
#define CLI_COLOR_TEMPERATURE_WARM (1)
#define CLI_COLOR_TEMPERATURE_COOL (2)

//BLENDING_GAMMA
#define CLI_BLENDING_GAMMA_1_8 (0)
#define CLI_BLENDING_GAMMA_1_9 (1)
#define CLI_BLENDING_GAMMA_2_0 (2)
#define CLI_BLENDING_GAMMA_2_1 (3)
#define CLI_BLENDING_GAMMA_2_2 (4)
#define CLI_BLENDING_GAMMA_2_3 (5)
#define CLI_BLENDING_GAMMA_2_4 (6)

//BACKGROUND_COLOR
#define CLI_BACKGROUND_COLOR_BLUE (1)
#define CLI_BACKGROUND_COLOR_BLACK (2)
#define CLI_BACKGROUND_COLOR_WHITE (3)
#define CLI_BACKGROUND_COLOR_LOGO (0)

//BACKUPINPUT_AUTOSWITCH
#define CLI_BACKUPINPUT_AUTOSWITCH_SEAMLESS (0)
#define CLI_BACKUPINPUT_AUTOSWITCH_BACKUP (1)
#define CLI_BACKUPINPUT_AUTOSWITCH_SIGNLE (2)

//EDID_TYPE
#define CLI_EDID_TYPE_V14 (0)
#define CLI_EDID_TYPE_V20 (1)
#define CLI_EDID_TYPE_CUSTOMIZED (2)// x35G2_Bruce_0002

//LAN_PATH SWITCH
#define CLI_LAN_PATH_SWITCH_RJ45 (0)
#define CLI_LAN_PATH_SWITCH_HDBASET (1)

//OSD_TIMEOUT
#define CLI_OSD_TIMEOUT_OFF (0)
#define CLI_OSD_TIMEOUT_60_SEC (1)
#define CLI_OSD_TIMEOUT_180_SEC (2)

//BACKGROUND
#define CLI_BACKGROUND_BLUE (0)
#define CLI_BACKGROUND_BLACK (1)
#define CLI_BACKGROUND_WHITE (2)
#define CLI_BACKGROUND_LOGO (3)

//LIGHT_SOURCE_MODE
#define CLI_LIGHT_SOURCE_MODE_NORMAL (0)
#define CLI_LIGHT_SOURCE_MODE_ECO_MODE (1)
#define CLI_LIGHT_SOURCE_MODE_CUSTOM_MODE (2)

//LENS_MEMORY_SAVE
#define CLI_LENS_MEMORY_SAVE_1 (0)
#define CLI_LENS_MEMORY_SAVE_2 (1)
#define CLI_LENS_MEMORY_SAVE_3 (2)
#define CLI_LENS_MEMORY_SAVE_4 (3)
#define CLI_LENS_MEMORY_SAVE_5 (4)

//LENS_MEMORY_APPLY
#define CLI_LENS_MEMORY_APPLY_1 (0)
#define CLI_LENS_MEMORY_APPLY_2 (1)
#define CLI_LENS_MEMORY_APPLY_3 (2)
#define CLI_LENS_MEMORY_APPLY_4 (3)
#define CLI_LENS_MEMORY_APPLY_5 (4)

#define CLI_LOGO_PATTERN_FACTORY_LOGO   (0)
#define CLI_LOGO_PATTERN_BLUE           (1)
#define CLI_LOGO_PATTERN_BLACK          (2)
#define CLI_LOGO_PATTERN_WHITE          (3)

//LOW LATENCY MODE
#define CLI_LOW_LATENCY_MODE_NORMAL     (0)
#define CLI_LOW_LATENCY_MODE_TYPICAL    (1)
#define CLI_LOW_LATENCY_MODE_ULTRA      (2)

//Detail
#define CLI_DETAIL_MAXIMUM    (0)
#define CLI_DETAIL_HIGH       (1)
#define CLI_DETAIL_NORMAL     (2)
#define CLI_DETAIL_LOW        (3)
#define CLI_DETAIL_MINIMUM    (4)

//HDR Level
#define CLI_HDR_LEVEL_1     (0)
#define CLI_HDR_LEVEL_2     (1)
#define CLI_HDR_LEVEL_3     (2)
#define CLI_HDR_LEVEL_4     (3)

//Clock Mode
#define CLI_CLOCK_MODE_USE_NTP_SERVER   (0)
#define CLI_CLOCK_MODE_MANUAL           (1)

//Update Interval
#define CLI_UPDATE_INTERVAL_HOURLY      (0)
#define CLI_UPDATE_INTERVAL_DAILY       (1)

//HDMI Output
#define CLI_HDMI_OUTPUT_HDMI1      (1)
#define CLI_HDMI_OUTPUT_HDMI2      (2)

//Schedule Copy Event To Weekday
#define CLI_COPY_EVENT_TO_MONDAY        (1)
#define CLI_COPY_EVENT_TO_TUESDAY       (2)
#define CLI_COPY_EVENT_TO_WEDNESDAY     (3)
#define CLI_COPY_EVENT_TO_THURSDAY      (4)
#define CLI_COPY_EVENT_TO_FRIDAY        (5)
#define CLI_COPY_EVENT_TO_SATURDAY      (6)
#define CLI_COPY_EVENT_TO_SUNDAY        (0)

//Geo Memory Save
#define CLI_GEO_SAVE_MEMORY1            (0)
#define CLI_GEO_SAVE_MEMORY2            (1)
#define CLI_GEO_SAVE_MEMORY3            (2)
#define CLI_GEO_SAVE_MEMORY4            (3)

//Geo Memory Apply
#define CLI_GEO_APPLY_OFF               (0)
#define CLI_GEO_APPLY_MEMORY1           (1)
#define CLI_GEO_APPLY_MEMORY2           (2)
#define CLI_GEO_APPLY_MEMORY3           (3)
#define CLI_GEO_APPLY_MEMORY4           (4)

#endif

#endif   //_CUSTOMDEFCLI_H_

