// ===============================================================================
// FILE NAME: dvDDP442x.h
// DESCRIPTION:
//
//
// Modification History
// --------------------
// 2017/05/11, Casper Create
// --------------------
// ===============================================================================

#ifndef DVDDP442X_H_
#define DVDDP442X_H_

#include "Common.h"

typedef enum
{
    /* Hardcoded enum to maintain compatibility with DLP Composer(tm) */
    READ_LENGTH_0 = 0x00,
    READ_LENGTH_1 = 0x01,
    READ_LENGTH_2 = 0x02,
    READ_LENGTH_3 = 0x03,
    READ_LENGTH_4 = 0x04,
    READ_LENGTH_5 = 0x05,
    READ_LENGTH_6 = 0x06,
    READ_LENGTH_7 = 0x07,
    READ_LENGTH_8 = 0x08,
    READ_LENGTH_9 = 0x09,
    READ_LENGTH_A = 0x0a,
    READ_LENGTH_B = 0x0b,
    READ_LENGTH_10 = 0x10,
    READ_CONTROL = 0x15,
    READ_CONTROL_MANID = 0x0C,
    READ_CONTROL_DEVID = 0x0D,
    READ_CONTROL_CS = 0x00,
    CALIBRATION_UNLOCK = 0x20,
    BL_SPECIAL_MODE = 0x23,
    FLASH_DOWNLOAD = 0x25,
    FLASH_CHECKSUM = 0x26,
    FLASH_ERASE = 0x28,
    FLASH_ADDRESS = 0x29,
    FLASH_SIZE = 0x2C,
    FLASH_TYPE = 0x2F,
    PROGRAMMING_MODE = 0x30,

    MAX_LEVEL1          /* last line */
}eDDP_CMD_LEVEL;


/****************************************************************************/
/* Projector control command definitions. DDP4422                           */
/****************************************************************************/
#if defined(PLATFORM_H60_2K) || defined(PLATFORM_R70K)//HICC2_Doulas_0001 //HICC2_AC_0003
typedef enum //sync with DDP API 6.0   (DDP442xHV)
{
    CMDF_STATUS_READ                 = 0x00,
    CMDF_PROJECTIONMODE              = 0x01,
    CMDF_SYSTEMMODE                  = 0x02,
    CMDF_UTLCWINDEX                  = 0x03,
    CMDF_INDEXDELAYFINE              = 0x04,
    CMDF_CWSPEED                     = 0x05,
    CMDF_CWSPINNINGCONTROL           = 0x06,
    CMDF_CWCOASTCONTROL              = 0x07,
    CMDF_CWDEBUGCONTROL              = 0x08,
    CMDF_CWSTATE                     = 0x09,
    CMDF_CWVSYNC                     = 0x0A,
    CMDF_CWINDEXCLOCK                = 0x0B,
    CMDF_HWTESTMUX                   = 0x0C,
    CMDF_SWTESTMUX                   = 0x0D,
    CMDF_APPDEBUG                    = 0x0E,
    CMDF_USBDEBUG                    = 0x0F,
    /**************************************/
    CMDF_VERTICALFLIP                = 0x10,
    CMDF_TPGPATTERN                  = 0x11,
    CMDF_TPGCSIZE                    = 0x12,
    CMDF_SFGCOLOR                    = 0x13,
    CMDF_ALGORITHM                   = 0x14,
    CMDF_I2CREAD                     = 0x15,
    CMDF_IMPBRIGHTNESS               = 0x16,
    CMDF_IMPCONTRAST                 = 0x17,
    CMDF_SHARPNESS                   = 0x18,
    CMDF_SOURCECSC                   = 0x19,
    CMDF_IMAGECCA                    = 0x1A,
    CMDF_IMAGEOFF                    = 0x1B,
    CMDF_IMAPPLYHSG                  = 0x1C,
    CMDF_WHITEPEAKING                = 0x1D,
    CMDF_BGCOLORMODE                 = 0x1E,
    CMDF_HORIZONTALFLIP              = 0x1F,
    /**************************************/
    CMDF_GETSYSMODEFEATURES          = 0x20,
    CMDF_SFGRESOLUTION               = 0x21,
    CMDF_SPLASHLOAD                  = 0x22,
    CMDF_DISPLAY                     = 0x23,
    CMDF_SOURCECONFIG                = 0x24,
    CMDF_SRCOFFSET                   = 0x25,
    CMDF_SRCPORT                     = 0x26,
    CMDF_SGSRCPORT_VSYNCPERIOD       = 0x27,
    CMDF_CHANNELSOURCE               = 0x28,
    CMDF_FREEZE                      = 0x29,
    CMDF_CHANNELCONFIG               = 0x2A,
    CMDF_TPGBORDER                   = 0x2B,
    CMDF_TPGRESOLUTION               = 0x2C,
    CMDF_GAMMACURVES                 = 0x2D,
    CMDF_CALCPIXELCLOCK              = 0x2E,
    CMDF_SRCDESCRIPTION              = 0x2F,
    /**************************************/
    CMDF_UTLPROGRAMMODE              = 0x30,
    CMDF_LAMPENABLE                  = 0x31,
    CMDF_LAMPENABLEDELAY             = 0x32,
    CMDF_STRIKERESET                 = 0x33,
    CMDF_LAMPSTRIKERESETDELAY        = 0x34,
    CMDF_LAMPLIT                     = 0x35,
    CMDF_LAMPLITSTABLE               = 0x36,
    CMDF_SYNCCOUNT                   = 0x37,
    CMDF_LAMPBIN                     = 0x38,
    CMDF_MANUALLAMPBIN               = 0x39,
    CMDF_MANLAMPBIN                  = 0x3A,
    CMDF_COMM                        = 0x3B,
    CMDF_VARLAMPWAVEFORMINDEX        = 0x3C,
    CMDF_VARLAMPWAVEFORMID           = 0x3D,
    CMDF_VARNUMLAMPWAVEFORMS         = 0x3E,
    CMDF_VARLAMPWAVEFORMGAIN         = 0x3F,
    /**************************************/
    CMDF_COLORTEMPPRESET             = 0x40,
    CMDF_HUECOLOR                    = 0x41,
    CMDF_DBENABLE                    = 0x42,
    CMDF_DBPOSITION                  = 0x43,
    CMDF_DBMINMAX                    = 0x44,
    CMDF_DBMANMODE                   = 0x45,
    CMDF_DBAPERTURE                  = 0x46,
    CMDF_DBAPERTUREINDEX             = 0x47,
    CMDF_DBBORDERCONF                = 0x48,
    CMDF_DBBORDERWEIGHT              = 0x49,
    CMDF_DBCLIPPIXELS                = 0x4A,
    CMDF_DBGAIN                      = 0x4B,
    CMDF_DBNUMSTEPS                  = 0x4C,
    CMDF_DBSPEED                     = 0x4D,
    CMDF_DBSTRENGTH                  = 0x4E,
    CMDF_DBHIST                      = 0x4F,
    /**************************************/
    CMDF_VARWAVEFORMMINGAIN          = 0x50,
    CMDF_VARWAVEFORMMAXGAIN          = 0x51,
    CMDF_VARLAMPMANUFACTID           = 0x52,
    CMDF_VARLAMPBLSTID               = 0x53,
    CMDF_VARLAMPBLSTSTATUS           = 0x54,
    CMDF_VARLAMPWAVEFORMSTATUSINFO   = 0x55,
    CMDF_LAMPSYNCTYPE                = 0x56,
    CMDF_LAMPSYNCDELAY               = 0x57,
    CMDF_VARLAMPBLSTWRITE            = 0x58,
    CMDF_VARBLSTMAILBOXSTATUS        = 0x59,
    CMDF_DYNBLSTGAIN                 = 0x5A,
    CMDF_DYNBLSTINTECSMODE           = 0x5B,
    CMDF_DYNBLSTSTATUS               = 0x5C,
    CMDF_DBINITIALIZE                = 0x5D,
    CMDF_DBAVAILABLE                 = 0x5E,
    CMDF_AUTOLOCKSTATUS              = 0x5F,
    /**************************************/
    CMDF_ALGCONTROL                  = 0x60,
    CMDF_3DENABLE                    = 0x61,
    CMDF_FRM                         = 0x62,
    CMDF_VIEWINGMODE                 = 0x63,
    CMDF_3DFREEZE                    = 0x64,
    CMDF_3DDLPLINKPULSE              = 0x65,
    CMDF_3DREFPOLARITY               = 0x66,
    CMDF_3DSOURCECONFIG              = 0x67,
    CMDF_RESYNC                      = 0x68,
    CMDF_3DSYNCINPUTSELECT           = 0x69,
    CMDF_3DSYNCOUTPUTSELECT          = 0x6A,
    CMDF_3DSYNCINPUT_MONITOR         = 0x6B,
    CMDF_3D_FORMAT                   = 0x6C,
    CMDF_LIMIT_BLACK_LEVEL           = 0x6D,
    CMDF_LIMIT_BLACK_TOLERANCE       = 0x6E,
    CMDF_LIMIT_BLACK_STATUS          = 0x6F,
    /**************************************/
    CMDF_BRSDISABLEDC                = 0x70,
    CMDF_BRSDIAGCFG                  = 0x71,
    CMDF_BRSDIAG                     = 0x72,
    CMDF_BRSMAXGAIN                  = 0x73,
    CMDF_BRSMAXDIGGAIN               = 0x74,
    CMDF_BRSCLIPPCT                  = 0x75,
    CMDF_BRSSCENECHGRATE             = 0x76,
    CMDF_BRSMINDC                    = 0x77,
    CMDF_BRSHISTSHIFT                = 0x78,
    CMDF_BRSHISTREST                 = 0x79,
    CMDF_BRSDYNLUMASHIFT             = 0x7A,
    CMDF_BRSDYNLUMASHIFTTHR          = 0x7B,
    CMDF_BRSDYNLUMASHIFTSTATIC       = 0x7C,
    CMDF_BRSDYNLUMASHIFTMOVE         = 0x7D,
    CMDF_BRSDYNLUMASHIFTHISTDELAY    = 0x7E,
    CMDF_DMDSS                       = 0x7F,
    /**************************************/
    CMDF_CMDDMDDEVTYPE               = 0x80,
    CMDF_CMDDMDRESO                  = 0x81,
    CMDF_SYSTEMSTATUS                = 0x82,
    CMDF_SETSLAVEPOWERSTANDBY        = 0x83,
    CMDF_SETPOWER                    = 0x84,
    CMDF_APPVERSIONS                 = 0x85,
    CMDF_DMDPOWER                    = 0x86,
    CMDF_DMDPARK                     = 0x87,
    CMDF_TSKSSTATE                   = 0x88,
    CMDF_GETTSKSTATE                 = 0x89,
    CMDF_SETTSKPRIOR                 = 0x8A,
    CMDF_SETTSKSUSP                  = 0x8B,
    CMDF_SYSSTACK                    = 0x8C,
    CMDF_MEMPOOL                     = 0x8D,
    CMDF_RESOURCE                    = 0x8E,
    CMDF_MEMWRITEREAD                = 0x8F,
    /**************************************/
    CMDF_DDP_SWRESET                 = 0x90,
    CMDF_DDPRESETCOUNT               = 0x91,
    CMDF_DDPRESETCAUSE               = 0x92,
    CMDF_USBCLOCK                    = 0x93,
    CMDF_SETGETDDPCLOCK              = 0x94,
    CMDF_GETDDPCLOCKFREQ             = 0x95,
    CMDF_DDPGETASICCONFIG            = 0x96,
    CMDF_GETDDPASICINFO              = 0x97,
    CMDF_WAP_SETGET                  = 0x98,
    CMDF_WAP                         = 0x99,
    CMDF_SCALARBYPASSMODE            = 0x9A,
    CMDF_FRCBYPASSMODE               = 0x9B,
    CMDF_ACTUATOR_PARAMETER          = 0x9C, //HICC2_AC_0003 //PLATFORM_R70K
    CMDF_WAP_ALLSET_TRPDMD_ESTATUS   = 0x9D, //G50_Casper_0006
    CMDF_APPCMDDELAY                 = 0x9E,
    CMDF_RX24TVERSION                = 0x9F, //HICC2_Doulas_0018
    /**************************************/
    CMDF_FANFREQCYCLE                = 0xA0,
    CMDF_FANPARALLEL                 = 0xA1,
    CMDF_CWDIRECTION                 = 0xA2,
    CMDF_CWDIRECTIONENABLE           = 0xA3,
    CMDF_CWCLOCK                     = 0xA4,
    CMDF_CWBRAKE                     = 0xA5,
    CMDF_CWTYPE                      = 0xA6,
    CMDF_CWMOTORTYPE                 = 0xA7,
    CMDF_DUALCWDELAY                 = 0xA8,
    CMDF_DUALCWSTRENGTH              = 0xA9,
    CMDF_CWSEQUENCER                 = 0xAA,
    CMDF_CWSPOKETEST                 = 0xAB,
    CMDF_CWSPOKECONFIG               = 0xAC,
    CMDF_FANDEVICE                   = 0xAD,
    CMDF_SET_GETDUALCWDELAY          = 0xAE,
    CMDF_FANNUMSELECT                = 0xAF,
    /**************************************/
    CMDF_PWMOUTPUTCONFIG             = 0xB0,
    CMDF_PWMINPUTCONFIG              = 0xB1,
    CMDF_DMDLOCK                     = 0xB2,
    CMDF_DISPOFFSET                  = 0xB3,
    CMDF_COLORPROFILE                = 0xB4,
    CMDF_CWINDEXPOL                  = 0xB5,
    CMDF_DISPKEYENA                  = 0xB6,
    CMDF_DISPKEYANG                  = 0xB7,
    CMDF_DISPKEYPIT                  = 0xB8,
    CMDF_DISPKEYYAW                  = 0xB9,
    CMDF_DISPKEYCORNERS              = 0xBA,
    CMDF_DISPKEYANCHOROVERRIDE       = 0xBB,
    CMDF_RESERVED_BC                 = 0xBC,
    CMDF_ASPECT_RATIO                = 0xBD,
    CMDF_SEQREVISION                 = 0xBE,
    CMDF_EMERGSHUTDOWN               = 0xBF,
    /**************************************/
    CMDF_SSIC1CURRENTS               = 0xC0,
    CMDF_SSIREDCURRENTS              = 0xC1,
    CMDF_SSIGRNCURRENTS              = 0xC2,
    CMDF_SSIBLUCURRENTS              = 0xC3,
    CMDF_SSIDRIVERSTATUS             = 0xC4,
    CMDF_SSIREDDRIVERTIMING          = 0xC5,
    CMDF_SSIGRNDRIVERTIMING          = 0xC6,
    CMDF_SSIBLUDRIVERTIMI            = 0xC7,
    CMDF_SSIEXTSENSORXY              = 0xC8,
    CMDF_SSISENSORCAL                = 0xC9,
    CMDF_SSISENSOR                   = 0xCA,
    CMDF_SSISENSORTIMING             = 0xCB,
    CMDF_CCIMODE                     = 0xCC,
    CMDF_CCIENABLE                   = 0xCD,
    CMDF_SSIPWMDRIVERLEVELS          = 0xCE,
    CMDF_SSIPWMDRIVERLEVELS2         = 0xCF,
    /**************************************/
    CMDF_PWMPARAMS                   = 0xD0,
    CMDF_SSILEDMAXCURRENT            = 0xD1,
    CMDF_RESERVED_D2                 = 0xD2,
    CMDF_RESERVED_D3                 = 0xD3,
    CMDF_SSIDCSEQINDEX               = 0xD4,
    CMDF_SSIDCDUMPUART               = 0xD5,
    CMDF_SSIRAMPENABLE               = 0xD6,
    CMDF_SPICONFIG                   = 0xD7,
    CMDF_ALC_RGB_LEVEL               = 0xD8,
    CMDF_RESERVED_D9                 = 0xD9,
    CMDF_4WAYXPR_PARAM               = 0xDA, //HICC2_AC_0003 //PLATFORM_R70K
    CMDF_ABPINFO                     = 0xDB,
    CMDF_DIMPOWER                    = 0xDC,
    CMDF_REALBLACK_LIGHTSOUTTIMER    = 0xDD,
    CMDF_SMOOTH_ON                   = 0xDE,
    CMDF_RESERVE_DF                  = 0xDF,
    /**************************************/
    CMDF_MEMORYTDUMP                 = 0xE0,
    CMDF_GETMEMORYDUMP               = 0xE1,
    CMDF_MEMBIST                     = 0xE2,
    CMDF_UARTCONFIG                  = 0xE3,
    CMDF_GETUARTPORT                 = 0xE4,
    CMDF_UARTRXDSOURCESELECT         = 0xE5,
    CMDF_AUTOUPDATE                  = 0xE6,
    CMDF_I2CPASS                     = 0xE7,
    CMDF_GETI2CPASS                  = 0xE8,
    CMDF_IMAGERGBGAIN                = 0xE9,
    CMDF_EEPROMVER                   = 0xEA,
    CMDF_RESERVED_EB                 = 0xEB,
    CMDF_BLACKSIGNALSWITCH           = 0xEC,
    CMDF_RESERVED_ED                 = 0xED,
    CMDF_BCCALIBRATE                 = 0xEE,
    CMDF_GAMMATABLE                  = 0xEF,
    /**************************************/
    CMDF_FPGACTRL_WRRD               = 0xF0, //HICC2_AC_0003 //PLATFORM_R70K
    CMDF_RESERVED_F1                 = 0xF1,
    CMDF_RESERVED_F2                 = 0xF2,
    CMDF_FPGACTRL_SETGET             = 0xF3, //HICC2_AC_0003 //PLATFORM_R70K
    CMDF_RESERVED_F4                 = 0xF4,
    CMDF_RGBGAINADJUSTMENTS          = 0xF5,
    CMDF_APCCT                       = 0xF6,
    CMDF_SETCOLOROFFSET              = 0xF7,
    CMDF_SPLASH_SCREEN               = 0xF8,
    CMDF_RESERVED_F9                 = 0xF9,
    CMDF_SRC_AUTODETECT              = 0xFA,
    CMDF_SEQVERSION                  = 0xFB,
    CMDF_IMG_ALGORITHM               = 0xFC,
    CMDF_IMG_ORIENTATION             = 0xFD,
    CMDF_CMPSR_PASSTHRU              = 0xFE,
    CMDF_PARAMETER_SET               = 0xFF,
}eDDP_CMD_ID;
#else
typedef enum //ZU860_John_0013 sync with DDP API 9.0
{
    //    CMDF_VSYNCPERIOD                 = 0x27,
    //    CMDF_3DSYNCSELECTION             = 0x68,
    //    CMDF_RESERVED_69                 = 0x69,
    //    CMDF_3DSYNCOUT                   = 0x6A,
    //    CMDF_3DSYNCINPUTMONITOR          = 0x6B,
    //    CMDF_3DNEWHARDWARE               = 0x6C,
    //    CMDF_3D_FORMAT                   = 0x6D,    //A70LV_Doulas_0154 Modify
    //    CMDF_RESERVED_6E                 = 0x6E,
    //    CMDF_RESERVED_6F                 = 0x6F,
    //    CMDF_ERRORSTATUS                 = 0x83,
    //    CMDF_POWERUP                     = 0x84,
    //    CMDF_RESERVED_9C                 = 0x9C,
    //    CMDF_RESERVED_9D                 = 0x9D,
    //    CMDF_RESERVED_AD                 = 0xAD,
    //    CMDF_RESERVED_AE                 = 0xAE,
    //    CMDF_RESERVED_AF                 = 0xAF,
    //    CMDF_RESERVED_B2                 = 0xB2,
    //    CMDF_RESERVED_B3                 = 0xB3,
    //    CMDF_RESERVED_B4                 = 0xB4,
    //    CMDF_RESERVED_B5                 = 0xB5,
    //    CMDF_RESERVED_B6                 = 0xB6,
    //    CMDF_RESERVED_B7                 = 0xB7,
    //    CMDF_RESERVED_B8                 = 0xB8,
    //    CMDF_RESERVED_B9                 = 0xB9,
    //    CMDF_RESERVED_BA                 = 0xBA,
    //    CMDF_RESERVED_BB                 = 0xBB,
    //    CMDF_RESERVED_BC                 = 0xBC,
    //    CMDF_RESERVED_BD                 = 0xBD,
    //    CMDF_RESERVED_BE                 = 0xBE,
    //    CMDF_RESERVED_C0                 = 0xC0,
    //    CMDF_LIMIT_BLACK_LEVEL           = 0xD0,
    //    CMDF_LIMIT_BLACK_TOLERANCE       = 0xD1,
    //    CMDF_LIMIT_BLACK_STATUS          = 0xD2,
    //    CMDF_RESERVED_D7                 = 0xD7,
    //    CMDF_RESERVE_D9                  = 0xD9,    //A70LV_Doulas_0037
    //    CMDF_RESERVE_DA                  = 0xDA,
    //    CMDF_DB_USE_PWM                  = 0xEA,
    //    CMDF_RESERVED_EB                 = 0xEB,
    //    CMDF_RESERVED_EC                 = 0xEC,
    //    CMDF_RESERVED_ED                 = 0xED,
    //    CMDF_RESERVED_EE                 = 0xEE,
    //    CMDF_RESERVED_EF                 = 0xEF,
    //
    //    /**************************************/
    //    CMDF_BCCALIBRATE                 = 0xF0,
    //    CMDF_SEGMENTCOLOR                = 0xF1,
    //    CMDF_RESERVED_F2                 = 0xF2,
    //    CMDF_GAMMATABLE                  = 0xF3,
    //    CMDF_RESERVED_F4                 = 0xF4,
	CMDF_STATUS_READ                         = 0x00,
	CMDF_PROJECTIONMODE                      = 0x01,
	CMDF_SYSTEMMODE                          = 0x02,
	CMDF_UTLCWINDEX                          = 0x03,
	CMDF_INDEXDELAYFINE                      = 0x04,
	CMDF_CWSPEED                             = 0x05,
	CMDF_CWSPINNINGCONTROL                   = 0x06,
	CMDF_CWCOASTCONTROL                      = 0x07,
	CMDF_CWDEBUGCONTROL                      = 0x08,
	CMDF_CWSTATE                             = 0x09,
	CMDF_CWVSYNC                             = 0x0A,
	CMDF_CWINDEXCLOCK                        = 0x0B,
	CMDF_HWTESTMUX                           = 0x0C,
	CMDF_SWTESTMUX                           = 0x0D,
	CMDF_APPDEBUG                            = 0x0E,
	CMDF_USBDEBUG                            = 0x0F,
	/**********************************************/
	CMDF_VERTICALFLIP                        = 0x10,
	CMDF_TPGPATTERN                          = 0x11,
	CMDF_TPGCSIZE                            = 0x12,
	CMDF_SFGCOLOR                            = 0x13,
	CMDF_ALGORITHM                           = 0x14,
	CMDF_I2CREAD                             = 0x15,
	CMDF_IMPBRIGHTNESS                       = 0x16,
	CMDF_IMPCONTRAST                         = 0x17,
	CMDF_SHARPNESS                           = 0x18,
	CMDF_SOURCECSC                           = 0x19,
	CMDF_IMAGECCA                            = 0x1A,
	CMDF_IMAGEOFF                            = 0x1B,
	CMDF_IMAPPLYHSG                          = 0x1C,
	CMDF_WHITEPEAKING                        = 0x1D,
	CMDF_BGCOLORMODE                         = 0x1E,
	CMDF_HORIZONTALFLIP                      = 0x1F,
	/**********************************************/
	CMDF_GETSYSMODEFEATURES                  = 0x20,
	CMDF_SFGRESOLUTION                       = 0x21,
	CMDF_SPLASHLOAD                          = 0x22,
	CMDF_DISPLAY                             = 0x23,
	CMDF_SOURCECONFIG                        = 0x24,
	CMDF_SRCOFFSET                           = 0x25,
	CMDF_SRCPORT                             = 0x26,
	CMDF_SGSRCPORT_VSYNCPERIOD               = 0x27,
	CMDF_CHANNELSOURCE                       = 0x28,
	CMDF_FREEZE                              = 0x29,
	CMDF_CHANNELCONFIG                       = 0x2A,
	CMDF_TPGBORDER                           = 0x2B,
	CMDF_TPGRESOLUTION                       = 0x2C,
	CMDF_GAMMACURVES                         = 0x2D,
	CMDF_CALCPIXELCLOCK                      = 0x2E,
	CMDF_SRCDESCRIPTION                      = 0x2F,
	/**********************************************/
	CMDF_UTLPROGRAMMODE                      = 0x30,
	CMDF_LAMPENABLE                          = 0x31,
	CMDF_LAMPENABLEDELAY                     = 0x32,
	CMDF_STRIKERESET                         = 0x33,
	CMDF_LAMPSTRIKERESETDELAY                = 0x34,
	CMDF_LAMPLIT                             = 0x35,
	CMDF_LAMPLITSTABLE                       = 0x36,
	CMDF_SYNCCOUNT                           = 0x37,
	CMDF_LAMPBIN                             = 0x38,
	CMDF_MANUALLAMPBIN                       = 0x39,
	CMDF_MANLAMPBIN                          = 0x3A,
	CMDF_COMM                                = 0x3B,
	CMDF_VARLAMPWAVEFORMINDEX                = 0x3C,
	CMDF_VARLAMPWAVEFORMID                   = 0x3D,
	CMDF_VARNUMLAMPWAVEFORMS                 = 0x3E,
	CMDF_VARLAMPWAVEFORMGAIN                 = 0x3F,
	/**********************************************/
	CMDF_COLOR_TEMP_PRESET                   = 0x40,
	CMDF_HUECOLOR                            = 0x41,
	CMDF_DBENABLE                            = 0x42,
	CMDF_DBPOSITION                          = 0x43,
	CMDF_DBMINMAX                            = 0x44,
	CMDF_DBMANMODE                           = 0x45,
	CMDF_DBAPERTURE                          = 0x46,
	CMDF_DBAPERTUREINDEX                     = 0x47,
	CMDF_DBBORDERCONF                        = 0x48,
	CMDF_DBBORDERWEIGHT                      = 0x49,
	CMDF_DBCLIPPIXELS                        = 0x4A,
	CMDF_DBGAIN                              = 0x4B,
	CMDF_DBNUMSTEPS                          = 0x4C,
	CMDF_DBSPEED                             = 0x4D,
	CMDF_DBSTRENGTH                          = 0x4E,
	CMDF_DBHIST                              = 0x4F,
	/**********************************************/
	CMDF_VARWAVEFORMMINGAIN                  = 0x50,
	CMDF_VARWAVEFORMMAXGAIN                  = 0x51,
	CMDF_VARLAMPMANUFACTID                   = 0x52,
	CMDF_VARLAMPBLSTID                       = 0x53,
	CMDF_VARLAMPBLSTSTATUS                   = 0x54,
	CMDF_VARLAMPWAVEFORMSTATUSINFO           = 0x55,
	CMDF_LAMP_SYNC_TYPE                      = 0x56,
	CMDF_LAMP_SYNC_DELAY                     = 0x57,
	CMDF_VARLAMPBLSTWRITE                    = 0x58,
	CMDF_VARBLSTMAILBOXSTATUS                = 0x59,
	CMDF_DYNBLSTGAIN                         = 0x5A,
	CMDF_DYNBLSTINTECSMODE                   = 0x5B,
	CMDF_DYNBLSTSTATUS                       = 0x5C,
	CMDF_DBINITIALIZE                        = 0x5D,
	CMDF_DBAVAILABLE                         = 0x5E,
	CMDF_AUTOLOCKSTATUS                      = 0x5F,
	/**********************************************/
	CMDF_ALGCONTROL                          = 0x60,
	CMDF_3DENABLE                            = 0x61,
	CMDF_FRM                                 = 0x62,
	CMDF_VIEWINGMODE                         = 0x63,
	CMDF_3DFREEZE                            = 0x64,
	CMDF_3DDLPLINKPULSE                      = 0x65,
	CMDF_3DREFPOLARITY                       = 0x66,
	CMDF_3DSOURCECONFIG                      = 0x67,
	CMDF_RESYNC                              = 0x68,
	CMDF_SLAVESYSTEMMODE                     = 0x69,
	CMDF_SLAVEPOWERSTATE                     = 0x6A,
	CMDF_SLAVEAUTOLOCKSTATE                  = 0x6B,
	CMDF_SLAVEPROJECTIONMODE                 = 0x6C,
	CMDF_SLAVEFRM                            = 0x6D,
	CMDF_SLAVEDISPLAY                        = 0x6E,
	CMDF_SETSLAVEDISPLAY                     = 0x6F,
	/**********************************************/
	CMDF_BRSDISABLEDC                        = 0x70,
	CMDF_BRSDIAGCFG                          = 0x71,
	CMDF_BRSDIAG                             = 0x72,
	CMDF_BRSMAXGAIN                          = 0x73,
	CMDF_BRSMAXDIGGAIN                       = 0x74,
	CMDF_BRSCLIPPCT                          = 0x75,
	CMDF_BRSSCENECHGRATE                     = 0x76,
	CMDF_BRSMINDC                            = 0x77,
	CMDF_BRSHISTSHIFT                        = 0x78,
	CMDF_BRSHISTREST                         = 0x79,
	CMDF_BRSDYNLUMASHIFT                     = 0x7A,
	CMDF_BRSDYNLUMASHIFTTHR                  = 0x7B,
	CMDF_BRSDYNLUMASHIFTSTATIC               = 0x7C,
	CMDF_BRSDYNLUMASHIFTMOVE                 = 0x7D,
	CMDF_BRSDYNLUMASHIFTHISTDELAY            = 0x7E,
	CMDF_DMDSS                               = 0x7F,
	/**********************************************/
	CMDF_CMDDMDDEVTYPE                       = 0x80,
	CMDF_CMDDMDRESO                          = 0x81,
	CMDF_SYSTEMSTATUS                        = 0x82,
	CMDF_SETSLAVEPOWERSTANDBY                = 0x83,
	CMDF_SETPOWER                            = 0x84,
	CMDF_APPVERSIONS                         = 0x85,
	CMDF_DMDPOWER                            = 0x86,
	CMDF_DMDPARK                             = 0x87,
	CMDF_TSKSSTATE                           = 0x88,
	CMDF_GETTSKSTATE                         = 0x89,
	CMDF_SETTSKPRIOR                         = 0x8A,
	CMDF_SETTSKSUSP                          = 0x8B,
	CMDF_SYSSTACK                            = 0x8C,
	CMDF_MEMPOOL                             = 0x8D,
	CMDF_RESOURCE                            = 0x8E,
	CMDF_MEMWRITEREAD                        = 0x8F,
	/**********************************************/
	CMDF_DDP_SWRESET                         = 0x90,
	CMDF_DDPRESETCOUNT                       = 0x91,
	CMDF_DDPRESETCAUSE                       = 0x92,
	CMDF_USBCLOCK                            = 0x93,
	CMDF_SETGETDDPCLOCK                      = 0x94,
	CMDF_GETDDPCLOCKFREQ                     = 0x95,
	CMDF_DDPGETASICCONFIG                    = 0x96,
	CMDF_GETDDPASICINFO                      = 0x97,
	CMDF_3DSYNCINPUTSELECT                   = 0x98,
	CMDF_3DSYNCOUTPUTSELECT                  = 0x99,
	CMDF_SCALARBYPASSMODE                    = 0x9A,
	CMDF_FRCBYPASSMODE                       = 0x9B,
	CMDF_TEMPSENSOR                          = 0x9C,
	CMDF_WAP_ALLSET_TRPDMD_ESTATUS           = 0x9D, //G50_Casper_0006 //HICC2_Steven_0019
	CMDF_APPCMD_DELAY                        = 0x9E,
	CMDF_RX24TVERSION                        = 0x9F,
	/**********************************************/
	CMDF_FANFREQCYCLE                        = 0xA0,
	CMDF_FANPARALLEL                         = 0xA1,
	CMDF_CWDIRECTION                         = 0xA2,
	CMDF_CWDIRECTIONENABLE                   = 0xA3,
	CMDF_CWCLOCK                             = 0xA4,
	CMDF_CWBRAKE                             = 0xA5,
	CMDF_CWTYPE                              = 0xA6,
	CMDF_CWMOTORTYPE                         = 0xA7,
	CMDF_DUALCWDELAY                         = 0xA8,
	CMDF_DUALCWSTRENGTH                      = 0xA9,
	CMDF_CWSEQUENCER                         = 0xAA,
	CMDF_CWSPOKETEST                         = 0xAB,
	CMDF_CWSPOKECONFIG                       = 0xAC,
	CMDF_FANDEVICE                           = 0xAD,
	CMDF_SET_GETDUALCWDELAY                  = 0xAE,
	CMDF_3DSYNCINPUT_MONITOR_FANNUMSELECT    = 0xAF,
	/**********************************************/
	CMDF_PWMOUTPUTCONFIG                     = 0xB0,
	CMDF_PWMINPUTCONFIG                      = 0xB1,
	CMDF_DMDLOCK                             = 0xB2,
	CMDF_DISPOFFSET                          = 0xB3,
	CMDF_COLOR_PROFILE                       = 0xB4,
	CMDF_CW_INDEX_POLARITY                   = 0xB5,
	CMDF_DISP_KEY_MINMAX_PIT                 = 0xB6,
	CMDF_DISP_KEY_ENABLE                     = 0xB7,
	CMDF_DISP_KEY_ANGLE                      = 0xB8,
	CMDF_3D_FORMAT                           = 0xB9,
	CMDF_LIMIT_BLACK_LEVEL                   = 0xBA,
	CMDF_LIMIT_BLACK_TOLERANCE               = 0xBB,
	CMDF_LIMIT_BLACK_STATUS                  = 0xBC,
	CMDF_WAP                                 = 0xBD,
	CMDF_SEQREVISION                         = 0xBE,
	CMDF_EMERGSHUTDOWN                       = 0xBF,
	/**********************************************/
	CMDF_SSIC1CURRENTS                       = 0xC0,
	CMDF_SSIREDCURRENTS                      = 0xC1,
	CMDF_SSIGRNCURRENTS                      = 0xC2,
	CMDF_SSIBLUCURRENTS                      = 0xC3,
	CMDF_SSIDRIVERSTATUS                     = 0xC4,
	CMDF_SSIREDDRIVERTIMING                  = 0xC5,
	CMDF_SSIGRNDRIVERTIMING                  = 0xC6,
	CMDF_SSIBLUDRIVERTIMING                  = 0xC7,
	CMDF_SSIEXTSENSORXY                      = 0xC8,
	CMDF_SSISENSORCAL                        = 0xC9,
	CMDF_SSISENSOR                           = 0xCA,
	CMDF_SSISENSORTIMING                     = 0xCB,
	CMDF_CCIMODE                             = 0xCC,
	CMDF_CCIENABLE                           = 0xCD,
	CMDF_SSIPWMDRIVERLEVELS                  = 0xCE,
	CMDF_SSIPWMDRIVERLEVELS2                 = 0xCF,
	/**********************************************/
	CMDF_PWMPARAMS                          = 0xD0,
	CMDF_SSIMAX_CURRENT                      = 0xD1,
	CMDF_REALBLACK_LIGHTSOUTTIMER            = 0xD2,
	CMDF_DIMPOWER                            = 0xD3,
	CMDF_SSIDCSEQINDEX                       = 0xD4,
	CMDF_SSIDCDUMPUART                       = 0xD5,
	CMDF_SSIRAMPENABLE                       = 0xD6,
	CMDF_SPICONFIG                           = 0xD7,
	CMDF_ALC_RGB_LEVEL                       = 0xD8,
	CMDF_4WAYXPR_WVFM                        = 0xD9,
	CMDF_4WAYXPR_PARAM                       = 0xDA,
	CMDF_4WAYXPR_WVFM_UPDATE_MODE            = 0xDB,
	CMDF_4WAYXPR_USER_UPDATE_WVFM            = 0xDC,
	CMDF_4WAYXPR_ACT_INFO                    = 0xDD,
	CMDF_SMOOTH_ON                           = 0xDE,
	CMDF_ABPINFO                             = 0xDF,
	/**********************************************/
	CMDF_MEMORYTDUMP                         = 0xE0,
	CMDF_GETMEMORYDUMP                       = 0xE1,
	CMDF_MEMBIST                             = 0xE2,
	CMDF_UARTCONFIG                          = 0xE3,
	CMDF_GETUARTPORT                         = 0xE4,
	CMDF_UARTRXDSOURCESELECT                 = 0xE5,
	CMDF_AUTOUPDATE                          = 0xE6,
	CMDF_I2CPASS                             = 0xE7,
	CMDF_GETI2CPASS                          = 0xE8,
	CMDF_IMAGERGBGAIN                        = 0xE9,
	CMDF_EEPROMVER                           = 0xEA,
	CMDF_DB_USE_PWM                          = 0xEB,
	CMDF_BLACKSIGNALSWITCH                   = 0xEC,
	CMDF_SEGMENTCOLOR                        = 0xED,
	CMDF_BCCALIBRATE                         = 0xEE,
	CMDF_GAMMATABLE                          = 0xEF,
	/**********************************************/
	CMDF_FPGACTRL_WRRD                       = 0xF0,
	CMDF_FPGAWRITE                           = 0xF1,
	CMDF_FPGAREAD                            = 0xF2,
	CMDF_FPGACTRL_SETGET                     = 0xF3,
	CMDF_FPGAKEYANGLE                        = 0xF4,
	CMDF_RGBGAINADJUSTMENTS                  = 0xF5,
	CMDF_APCCT                               = 0xF6,
	CMDF_SETCOLOROFFSET                      = 0xF7,
	CMDF_IMG_ORIENTATION                     = 0xF8,
	CMDF_COLOR_ENHANCEMENT                   = 0xF9,
	CMDF_SRC_AUTODETECT                      = 0xFA,
	CMDF_SEQVERSION                          = 0xFB,
	CMDF_IMG_ALGORITHM                       = 0xFC,
	CMDF_VX1_FREEZE_STAT                     = 0xFD,
	CMDF_CMPSR_PASSTHRU                      = 0xFE,
	CMDF_PARAMETER_SET                       = 0xFF,
}eDDP_CMD_ID;           //A70LV_Doulas_0028 modify
#endif

typedef struct
{
    UINT8  uiCmd;                     /* Command */
    UINT8  uiWriteNum;                /* The number of bytes associated with a write  command */
    UINT8  ucReadNum;                 /* The Number of bytes associated with a reasd command */
    UINT8  ucSPFlag;                  /* Special Commands indicator */
} I2C_COMMAND_TABLE;


#define dv442x_Read(x,y)   dv442x_Read_log(x,y,__FUNCTION__)
#define dv442x_Write(x,y)  dv442x_Write_log(x,y,__FUNCTION__)
void dv442x_AsicReadySet(BOOL bBnable);
BOOL dv442x_AsicReadGet(void); //HICC2_Doulas_0085
void dv442x_UpgradeSet(BOOL bBnable); //A70LV_Larry_0138
BOOL dv442x_Busy(void);
eRESULT dv442x_Read_log(eDDP_CMD_ID eCmd, UINT8 *pucData, const char *cFuncName);   //A70LV_Doulas_0006 modify
eRESULT dv442x_Write_log(eDDP_CMD_ID eCmd, UINT8 *pucData, const char *cFuncName);
BOOL dvDDP4422_IsAsicReady(void);       //A70LV_Doulas_0072
eRESULT dv442x_BusyPin_Init(void);
eRESULT dv442x_Test(void);

#endif /* DVDDP442X_H_ */
