#ifndef _PALFORMATTERMGR_H_
#define _PALFORMATTERMGR_H_

#include "utilCommon.h"
#include "halFormatter.h"

////////  callback function start  ////////
typedef void (*fpGetPictureModeCallback)(UINT8 *CurrentPictureMode);

typedef struct
{
    fpGetPictureModeCallback fpGetPictureModeCb;
}sFORMATTER_MGR_CALLBACK;

void palFormatter_RegCallback(sFORMATTER_MGR_CALLBACK fpCallback);;
void palFormatterMgr_RegCallback(sFORMATTER_MGR_CALLBACK fpCallback);
eRESULT palFormatterMgr_GetSSIPWMDriverLevels_1(uSSI_DRIVER *uSSI);
eRESULT palFormatterMgr_SetSSIPWMDriverLevels_1(uSSI_DRIVER *uSSI);
eRESULT palFormatterMgr_SetDisplaySFGColor(UINT16 uiSFG_Red,UINT16 uiSFG_Green,UINT16 uiSFG_Blue);
eRESULT palFormatterMgr_GetDisplaySFGColor(UINT16 *uiSFG_Red,UINT16 *uiSFG_Green,UINT16 *uiSFG_Blue);
eRESULT palFormatterMgr_Actuator_Switch_Set(UINT16 ucActuator);
eRESULT palFormatterMgr_PW_Index_Set(UINT16 uiPWIndex);
eRESULT palFormatterMgr_PW_Index_Get(UINT16 *uiPWIndex);
eRESULT palFormatterMgr_FW_Index_Set(UINT16 uiFWIndex);
eRESULT palFormatterMgr_FW_Index_Get(UINT16 *uiFWIndex);
eRESULT palFormatterMgr_PowerMode_Set(UINT8 ucPowerMode);
eRESULT palFormatterMgr_Actuator_Switch(UINT8 ucActuator);
eRESULT palFormatterMgr_Actuator_FixedOut_Set(UINT8 ucCh, UINT8 ucFixedOut);
eRESULT palFormatterMgr_Actuator_FixedOut_Get(UINT8 ucCh, UINT8 *ucFixedOut);
eRESULT palFormatterMgr_Actuator_Gain_Set(UINT8 ucCh, UINT8 ucActuatorGain);
eRESULT palFormatterMgr_Actuator_Gain_Get(UINT8 ucCh, UINT8 *ucActuatorGain);
eRESULT palFormatterMgr_Actuator_Segment_Length_Set(UINT8 ucCh, UINT16 uiSeg);
eRESULT palFormatterMgr_Actuator_Segment_Length_Get(UINT8 ucCh, UINT16 *uiSeg);
eRESULT palFormatterMgr_Actuator_SubFrameDelay_Set(UINT8 ucCh, UINT32 ulDelay);
eRESULT palFormatterMgr_Actuator_SubFrameDelay_Get(UINT8 ucCh, UINT32 *ulDelay);
eRESULT palFormatterMgr_Standby(void);
eRESULT palFormatterMgr_TestPattern(UINT8 ucPattern);
eRESULT palFormatterMgr_HorFlip(BOOL bH_Flip);
eRESULT palFormatterMgr_VerFlip(BOOL bV_Flip);
void palFormatterMgr_AsicReadySet(BOOL bBnable);
eRESULT palFormatterMgr_HorFlipGet(BOOL *bH_Flip);
eRESULT palFormatterMgr_VerFlipGet(BOOL *bV_Flip);
eRESULT palFormatterMgr_GetSSIPWMDriverLevels_2(uSSI_DRIVER *uSSI);
eRESULT palFormatterMgr_SetSSIPWMDriverLevels_2(uSSI_DRIVER *uSSI);
eRESULT palFormatterMgr_SystemModeSet(UINT8 cSystemMode);
eRESULT palFormatterMgr_SystemModeGet(UINT8 *cSystemMode);
eRESULT palFormatterMgr_SplashLoad(UINT8 cNum);
eRESULT palFormatterMgr_dv4422_TestPattern(UINT8 cTestPattern);
eRESULT palFormatterMgr_CW_SpokeTest(UINT8 cEnable);
eRESULT palFormatterMgr_ColorOffsetSet(UINT8 ucColorOffset);
eRESULT palFormatterMgr_IMG_AlgorithmSet(IMG_ALGORITHMS eAlgo, BOOL bState);
eRESULT palFormatterMgr_IMG_GammaLutSet(UINT8 cGamma);
eRESULT palFormatterMgr_IMG_GammaLutGet(UINT8* cGamma);
eRESULT palFormatterMgr_DB_EnableSet(UINT8 cDB);
eRESULT palFormatterMgr_DB_EnableGet(UINT8 *cDB);
eRESULT palFormatterMgr_DB_SetAperture(UINT16 cPosition);
eRESULT palFormatterMgr_DB_GetAperture(UINT16 *cPosition);
eRESULT palFormatterMgr_DB_SetMinMaxAperture(UINT16 ucMinPosition,UINT16 ucMaxPosition);
eRESULT palFormatterMgr_DB_GetMinMaxAperture(UINT16 *ucMinPosition,UINT16 *ucMaxPosition);
eRESULT palFormatterMgr_DB_SetOpenCloseAperture(UINT8 cOpenClose);
eRESULT palFormatterMgr_DB_GetCurrentAperture(UINT16 *ucCurrentAperture);
eRESULT palFormatterMgr_SYS_AppVersionGet(UINT16 *wDDP);
eRESULT palFormatterMgr_VersionSaveGet(UINT8 *pcData);
eRESULT palFormatterMgr_SEQ_RevisionGet(UINT32 *ucData);
eRESULT palFormatterMgr_3D_3DModeSet(BOOL cEnable);
eRESULT palFormatterMgr_3D_3DModeGet(BOOL *pbEnable);
eRESULT palFormatterMgr_IMG_WhitePeakingSet(UINT8 cWhitePeak);
eRESULT palFormatterMgr_IMG_WhitePeakingGet(UINT8 *cWhitePeak);
eRESULT palFormatterMgr_3D_RefPolaritySet( BOOL bRef3D, BOOL bOddEven, BOOL bTopField, BOOL bInvert );
eRESULT palFormatterMgr_3D_RefPolarityGet(BOOL *bRef3D, BOOL *bOddEven, BOOL *bTopField, BOOL *bInvert );
eRESULT palFormatterMgr_3D_DLPLinkPulseSet(BOOL bEnable);
eRESULT palFormatterMgr_3D_DLPLinkPulseGet(BOOL *pbEnable);
eRESULT palFormatterMgr_DISP_FreezeSet(UINT8 cFreeze);
eRESULT palFormatterMgr_DISP_FreezeGet(UINT8 *pcFreeze);
eRESULT palFormatterMgr_DB_SetBorderCfg(UINT16 ucScalerOutHS,UINT16 ucScalerOutVS,UINT16 ucScalerOutHW,UINT16 ucScalerOutVW);
eRESULT palFormatterMgr_DB_SetClipPixels(UINT16 ucClipPixels);
eRESULT palFormatterMgr_IsColorWheelSpinning(BOOL *cSpin);
eRESULT palFormatterMgr_HSGSet(UINT8* hsgdata);
INT16 palFormatterMgr_HSGdata_Trans(INT8 cHSG_OSDvalue, BOOL bHue);
eRESULT palFormatterMgr_HSGValueSet(sHSG_SETTING hsgdata);
eRESULT palFormatterMgr_CCADataSend(UINT8 *data, UINT16 wSize);
eRESULT palFormatterMgr_CCADataGet(UINT8 *data);
eRESULT palFormatterMgr_HSG_UnitGainSet(void);
eRESULT palFormatterMgr_SYS_SystemStatusGet(UINT8 *pcStatus);
eRESULT palFormatterMgr_DISP_BlackLevelSet(UINT8 bValue);
eRESULT palFormatterMgr_DISP_BlackLevelGet(UINT8 *bValue);
eRESULT palFormatterMgr_DISP_BlackLevelThresholdSet(UINT8 bValue);
eRESULT palFormatterMgr_DISP_BlackLevelThresholdGet(UINT8 *bValue);
eRESULT palFormatterMgr_DISP_BlackStatusSet(UINT8 bValue);
eRESULT palFormatterMgr_DISP_BlackPowerStatusGet(UINT8 *bValue);
eRESULT palFormatterMgr_ILL_AuxSyncSet(BOOL bEnable);
eRESULT palFormatterMgr_ILL_AuxSyncGet(BOOL *pbEnable);
eRESULT palFormatterMgr_ILL_AuxSyncTypeSet(UINT8 *pcSyncType);
eRESULT palFormatterMgr_ILL_AuxSyncTypeGet(UINT8 *pcSyncType);
eRESULT palFormatterMgr_ILL_BoostRLDEnableSet(UINT8 cEn);
eRESULT palFormatterMgr_ILL_BoostRLDEnableGet(UINT8 *pcEn);
eRESULT palFormatterMgr_DMD_BGDisplayModeSet(UINT8 cMode);
eRESULT palFormatterMgr_DMD_BGDisplayModeGet(UINT8 *pcMode);
eRESULT palFormatterMgr_SensorTimingGet(UINT16 *SensorStartDelay, UINT16 *RedSensorTiming ,UINT16 *GreenSensorTiming,UINT16 *BlueSensorTiming,UINT16 *YellowSensorTiming);
eRESULT palFormatterMgr_SensorTimingSet(UINT16 SensorStartDelay, UINT16 RedSensorTiming ,UINT16 GreenSensorTiming,UINT16 BlueSensorTiming,UINT16 YellowSensorTiming);
eRESULT palFormatterMgr_SensorDataGet(UINT16 *RedSensorData ,UINT16 *GreenSensorData,UINT16 *BlueSensorData,UINT16 *YellowSensorData);
eRESULT palFormatterMgr_ImageRGBGainGet(UINT16 *CSCRedGain ,UINT16 *CSCGreenGain,UINT16 *CSCBlueGain);
eRESULT palFormatterMgr_ImageRGBGainSet(UINT16 CSCRedGain ,UINT16 CSCGreenGain,UINT16 CSCBlueGain);
eRESULT palFormatterMgr_DynamicBlackUsePWMGet(UINT16 *PWM_FULL, UINT16 *PWM_ECO);
eRESULT palFormatterMgr_DynamicBlackUsePWMSet(UINT16 *PWM_FULL, UINT16 *PWM_ECO);
eRESULT palFormatterMgr_DynamicBlackTableGet(UINT8 *DA_Table);
eRESULT palFormatterMgr_DynamicBlackTableSet(UINT8 DA_Table);
eRESULT palFormatterMgr_BCCalibrateSet(BOOL bEnable,UINT32 dRed,UINT32 dGreen,UINT32 dBlue,UINT32 dYellow);
eRESULT palFormatterMgr_SegmentColorSet(UINT8 cSegmentColorEnabled,UINT8 cSegmentColor);
eRESULT palFormatterMgr_SegmentColorGet(UINT8 *cSegmentColorEnabled,UINT8 *cSegmentColor);
eRESULT palFormatterMgr_DBSpeedSet(UINT16 cDB_Speed);
eRESULT palFormatterMgr_DBSpeedGet(UINT16 *cDB_Speed);
eRESULT palFormatterMgr_ALC_RGB_LevelGet(UINT16 *RGBLevel);
eRESULT palFormatterMgr_CWIndexClockGet(UINT32 *dClockPeriod,UINT32 *dCW1_Frequence);
eRESULT palFormatterMgr_3D_SYNC_SelectionSet(UINT8 c3D_SYNC_Selection);
eRESULT palFormatterMgr_3D_SYNC_SelectionGet(UINT8 *c3D_SYNC_Selection);
eRESULT palFormatterMgr_3D_SYNC_OutSelectionSet(UINT8 c3D_SYNC_Out);
eRESULT palFormatterMgr_3D_SYNC_OutSelectionGet(UINT8 *c3D_SYNC_Out);
eRESULT palFormatterMgr_3D_SYNC_InputMonitorGet(BOOL *b3DSyncAvaliable,BOOL *b3DSyncLost,UINT8 *cdatapath_state);
eRESULT palFormatterMgr_3D_ViewingModeSet(UINT8 cViewingMode);
eRESULT palFormatterMgr_3D_ViewingModeGet(UINT8 *cViewingMode);
eRESULT palFormatterMgr_ConstantPowerSet(UINT8 cPower);
eRESULT palFormatterMgr_PWM_Set(UINT8 cIndex, UINT16 uiValue);
UINT16 palFormatterMgr_PWM_Get(UINT8 cIndex);
eRESULT palFormatterMgr_PWM_Update(void);
UINT16 palFormatterMgr_RLD_PWM_Set(UINT16 uiRValue,UINT16 uiYValue);
BOOL palDDP4422_IsAsicReady(void);
eRESULT palFormatterMgr_ColorEnhancementSet(UINT8 ucColorEnhancement);
eRESULT palFormatterMgr_WallColorSet(UINT8 ucWallColor);
eRESULT palFormatterMgr_ParameterSet(UINT8 ucPowerMode, UINT8 ucPowerModeNumber, UINT8 ucPictureMode, UINT8 ucColorTemperature, UINT8 ucColorWheelSpeed, UINT8 ucInputSource);
eRESULT palFormatterMgr_CeilingMount_RearProjectSet(BOOL bCeilingMount, BOOL bRearProject);
eRESULT palFormatterMgr_CeilingMount_RearProjectGet(UINT8 *pucValue);
eRESULT palFormatterMgr_COLOR_ENHANCEMENT_ValueGet(UINT8 ucDispalyMode, UINT8 ucCE, sHSG_SETTING *sHSG);
eRESULT palFormatterMgr_CE_Add_HSG_Set(UINT8 ucDispalyMode, UINT8 ucCE, sHSG_SETTING sHSG);
eRESULT palFormatterMgr_Upgrade_Set(UINT8 ucEnable);
eRESULT palFormatterMgr_3D_FormatSet(UINT8 c3D_Format);
eRESULT palFormatterMgr_3D_FormatGet(UINT8 *c3D_Format);
eRESULT palFormatterMgr_ChannelSourceSet(UINT8 cSource);
eRESULT palFormatterMgr_LightsOutTimerSet(UINT8 cLightOutTimer);
eRESULT palFormatterMgr_ABPINFOSet(UINT8 ucType, UINT8 *pucData);
eRESULT palFormatterMgr_ABPINFOGet(UINT8 *ucStatus);
eRESULT palFormatterMgr_IMG_AlgorithmEnableSet(UINT8* cAlg);
eRESULT palFormatterMgr_IMG_AlgorithmEnableGet(UINT8* cAlg);
eRESULT palFormatterMgr_Projection_Mode_Set(UINT8 ucProjection_Mode);
eRESULT palFormatterMgr_Projection_Mode_Get(UINT8 *ucProjection_Mode);
eRESULT palFormatterMgr_SlaveProjection_Mode_Get(UINT8 *ucProjection_Mode);
eRESULT palFormatterMgr_APCCT_Set(UINT8* cCCT);
eRESULT palFormatterMgr_APCCT_Get(UINT8* cCCT);
eRESULT palFormatterMgr_WAP_SetGet(UINT8 ucWap_Mode, eWAP_POWERLEVEL eWap_PowerLevel);
eRESULT palFormatterMgr_WAP_AllSet(eWAP_POWERLEVEL eWap_PowerLevel, UINT16 *ucPWM);
eRESULT palFormatterMgr_WAP_Set(UINT8 ucWap_Mode, eWAP_POWERLEVEL eWap_PowerLevel, UINT8 ucWap_LDSeq, UINT16 ucPWM);
eRESULT palFormatterMgr_WAP_Get(UINT16* ucPWM);
eRESULT palFormatterMgr_DB_StrengthSet(UINT8 ucValue);
eRESULT palFormatterMgr_DB_StrengthGet(UINT8 *ucValue);
eRESULT palFormatterMgr_FRC_BypassGet(UINT8 *ucEnable);
UINT8 palFormatterMgr_FRC_Bypass_Flag_Get(void);
eRESULT palFormatterMgr_BlankSignalSwitchSet(UINT8 ucEnable);
eRESULT palFormatterMgr_BlankSignalSwitchGet(UINT8 *ucEnable);
eRESULT palFormatterMgr_AspectRatio_Set(UINT8* ucVAl);
eRESULT palFormatterMgr_AspectRatio_Get(UINT8* ucVAl);
eRESULT palFormatterMgr_Smooth_Enable_Set(BOOL bEnable, UINT8 ucValue);
eRESULT palFormatterMgr_Smooth_Enable_Get(UINT8* ucVAl);
eRESULT palFormatterMgr_GetRLD_Light(UINT16 *RLD_Light);
eRESULT palFormatterMgr_FRCByPassModeSet(BOOL ucVAl);
eRESULT palFormatterMgr_FRCByPassModeGet(UINT8* ucVAl);
eRESULT palFormatterMgr_LDFadeInStartupSet(UINT8 ucShutterStartup, UINT8 ucShutterFadeIn);
eRESULT palFormatterMgr_SplashAtStartupTimeoutSet(UINT8 ucTimeout);
eRESULT palFormatterMgr_ColorOffsetSet(UINT8 cOffset);
eRESULT palFormatterMgr_PowerModeTable(UINT8 ucPowerMode);
eRESULT palFormatter_PowerMode_Set(UINT8 ucPowerMode);
eORIENTATION_STATE palFormatterMgr_OrientationStateGet(void);
eRESULT palFormatterMgr_FRC_BypassSet(UINT8 ucValue);
eRESULT palFormatterMgr_XPR_Set(UINT8 ucEnable);
eRESULT palFormatterMgr_XPR_Filter_Set(UINT8 ucValue);
eRESULT palFormatterMgr_XPR_Filter_Get(UINT8 *ucValue);
eRESULT palFormatterMgr_XPR_Close_Loop_Enable_Axis0_Set(UINT8 ucEnable);
eRESULT palFormatterMgr_XPR_Close_Loop_Enable_Axis0_Get(UINT8 *ucValue);
eRESULT palFormatterMgr_XPR_Close_Loop_Enable_Axis1_Set(UINT8 ucDatax);
eRESULT palFormatterMgr_XPR_Close_Loop_Enable_Axis1_Get(UINT8 *ucValue);
eRESULT palFormatterMgr_XPR_Gain_of_Axis0_Get(UINT32 *ucValue);
eRESULT palFormatterMgr_XPR_Gain_of_Axis1_Get(UINT32 *ucValue);
eRESULT palFormatterMgr_XPR_Segment_Length_of_Axis0_Get(UINT32 *ucValue);
eRESULT palFormatterMgr_XPR_Segment_Length_of_Axis1_Get(UINT32 *ucValue);
eRESULT palFormatterMgr_XPR_SN_Get(UINT8 *ucValue);
eRESULT palFormatterMgr_AutoLockResync(void);
eRESULT palFormatterMgr_GetI2C_Diag(UINT8 *pdata);
eRESULT palFormatterMgr_XPR_EepromTargetAdcAxis0_Get(UINT32 *ulValue);
eRESULT palFormatterMgr_XPR_EepromTargetAdcAxis1_Get(UINT32 *ulValue);
eRESULT palFormatterMgr_XPR_Eeprom_ZData0_Get(UINT32 *ulValue);
eRESULT palFormatterMgr_XPR_Eeprom_ZData1_Get(UINT32 *ulValue);
eRESULT palFormatterMgr_XPR_Eeprom_XData0_Get(UINT32 *ulValue);
eRESULT palFormatterMgr_XPR_Eeprom_XData1_Get(UINT32 *ulValue);
eRESULT palFormatterMgr_XPR_Eeprom_YData0_Get(UINT32 *ulValue);
eRESULT palFormatterMgr_XPR_Eeprom_YData1_Get(UINT32 *ulValue);
eRESULT palFormatterMgr_XPR_CloseLoop_ErrorCode0(UINT32 *ucValue); //HICC2_Steven_0051 start
eRESULT palFormatterMgr_XPR_CloseLoop_ErrorCode1(UINT32 *ucValue);
eRESULT palFormatterMgr_XPR_CloseLoop_Valid(UINT8 *ucValue);
eRESULT palFormatterMgr_XPR_Close_Loop_Error_Reset_Set(UINT8 ucValue); //HICC2_Steven_0051 end
eRESULT palFormatterMgr_XPR_Gain_Write_EEPROM(void);


#endif //_PALFORMATTERMGR_H_

