#ifndef _COMMONDEF_H_
#define _COMMONDEF_H_

#define eCM_ID_INVALID (INT32)(0xFFFFFFFF)

#define VERIFY_SIZE_OF(TYPE, Size) extern UINT8 _VerifySizeof##TYPE[(sizeof(TYPE) == (Size)) / (sizeof(TYPE) == (Size))]
typedef enum
{
    /* 00 */ eCM_SOURCE_RESERVED,
    /* 01 */ eCM_SOURCE_VGA,
    /* 02 */ eCM_SOURCE_BNC,
    /* 03 */ eCM_SOURCE_HDMI1,
    /* 04 */ eCM_SOURCE_HDMI2,
    /* 05 */ eCM_SOURCE_DVI,
    /* 06 */ eCM_SOURCE_DISPLAYPORT,
    /* 07 */ eCM_SOURCE_3GSDI,
    /* 08 */ eCM_SOURCE_HDBASET,
    /* 09 */ eCM_SOURCE_12GSDI, //rename COMPOSITE to 12G SDI
    /* 10 */ eCM_SOURCE_PRESENTER,
    /* 11 */ eCM_SOURCE_CARDREADER,
    /* 12 */ eCM_SOURCE_MINIUSB,
    /* 13 */ eCM_SOURCE_SLOT1,
    /* 14 */ eCM_SOURCE_SLOT2,

    eCM_SOURCE_NUMBER,
}eCM_SOURCE_ID;

typedef enum
{
    /* 00 */ eCM_TEST_PATTERN_OFF,
    /* 01 */ eCM_TEST_PATTERN_GRID,
    /* 02 */ eCM_TEST_PATTERN_WHITE,
    /* 03 */ eCM_TEST_PATTERN_BLACK,
    /* 04 */ eCM_TEST_PATTERN_CHECKERBOARD,
    /* 05 */ eCM_TEST_PATTERN_COLORBAR,
    /* 06 */ eCM_TEST_PATTERN_RED,
    /* 07 */ eCM_TEST_PATTERN_GREEN,
    /* 08 */ eCM_TEST_PATTERN_BLUE,
    /* 09 */ eCM_TEST_PATTERN_YELLOW,
    /* 10 */ eCM_TEST_PATTERN_MAGENTA,
    /* 11 */ eCM_TEST_PATTERN_CYAN,
    /* 12 */ eCM_TEST_PATTERN_FULL_SCREEN,
    /* 13 */ eCM_TEST_PATTERN_GREEN_GRID,
    /* 14 */ eCM_TEST_PATTERN_MAGENTA_GRID,
    /* 15 */ eCM_TEST_PATTERN_WHITE_GRID,
    /* 16 */ eCM_TEST_PATTERN_WHITE_GRID_4CORNER,
    /* 17 */ eCM_TEST_PATTERN_BORESIGHT,
    /* 18 */ eCM_TEST_PATTERN_GRAY,
    /* 19 */ eCM_TEST_PATTERN_13POINTS,
    /* 20 */ eCM_TEST_PATTERN_4K_FULL_SCREEN,     //Full Screen Pattern for Real Panel Resolution, char use 1 pixel width
    /* 21 */ eCM_TEST_PATTERN_4K_GRAY_75_5,
    /* 22 */ eCM_TEST_PATTERN_9POINTS,
    /* 23 */ eCM_TEST_PATTERN_H_RAMP,
    /* 24 */ eCM_TEST_PATTERN_V_RAMP,
    /* 25 */ eCM_TEST_PATTERN_FULL_COLOR,
    /* 26 */ eCM_TEST_PATTERN_CALIBRATION,
    /* 27 */ eCM_TEST_PATTERN_FOCUS,
    /* 28 */ eCM_TEST_PATTERN_4K_FULL_SCREEN_2P,  //Full Screen Pattern for Real Panel Resolution, char use 2 pixel width
    /* 29 */ eCM_TEST_PATTERN_RED_GRID,
    /* 30 */ eCM_TEST_PATTERN_BLUE_GRID,
    /* 31 */ eCM_TEST_PATTERN_CHECKERBOARD_2,
    /* 32 */ eCM_TEST_PATTERN_COLORBAR_2,
    /* 33 */ eCM_TEST_PATTERN_COLORBAR_3,
    /* 34 */ eCM_TEST_PATTERN_ASPECT_FRAME,

    eCM_TEST_PATTERN_NUMBER,
}eCM_TEST_PATTERN_ID;

typedef enum
{
    /* 00 */ eCM_FACTORY_TP_NONE,
    /* 01 */ eCM_FACTORY_TP_WHITE,
    /* 02 */ eCM_FACTORY_TP_BLACK,
    /* 03 */ eCM_FACTORY_TP_RED,
    /* 04 */ eCM_FACTORY_TP_GREEN,
    /* 05 */ eCM_FACTORY_TP_BLUE,
    /* 06 */ eCM_FACTORY_TP_CYAN,
    /* 07 */ eCM_FACTORY_TP_YELLOW,
    /* 08 */ eCM_FACTORY_TP_MAGENTA,
    /* 09 */ eCM_FACTORY_TP_BLUE60,
    /* 10 */ eCM_FACTORY_TP_GRAY10,
    /* 11 */ eCM_FACTORY_TP_WRGB64,
    /* 12 */ eCM_FACTORY_TP_FLARE,
    /* 13 */ eCM_FACTORY_TP_FULL_SREEN_W,
    /* 14 */ eCM_FACTORY_TP_FULL_SREEN_B,
    /* 15 */ eCM_FACTORY_TP_LATERAL_COLOR,
    /* 16 */ eCM_FACTORY_TP_FOCUS_WORD,
    /* 17 */ eCM_FACTORY_TP_13POINTS,
    /* 18 */ eCM_FACTORY_TP_FULL_COLOR,
    /* 19 */ eCM_FACTORY_TP_BORESIGHT,
    /* 20 */ eCM_FACTORY_TP_ACTUATOR,
    /* 21 */ eCM_FACTORY_TP_4K_FULL_SCREEN_1P,
    /* 22 */ eCM_FACTORY_TP_4K_FULL_SCREEN_2P,

    eCM_FACTORY_TP_NUMBER,
}eCM_FACTORY_TP_ID;

typedef enum
{
    /* 00 */ eCM_PICTURE_SETTINGS_PRESENTATION,
    /* 01 */ eCM_PICTURE_SETTINGS_VIDEO,
    /* 02 */ eCM_PICTURE_SETTINGS_BRIGHT,
    /* 03 */ eCM_PICTURE_SETTINGS_ENHANCED,
    /* 04 */ eCM_PICTURE_SETTINGS_REC709,
    /* 05 */ eCM_PICTURE_SETTINGS_REAL,
    /* 06 */ eCM_PICTURE_SETTINGS_DICOMSIM,
    /* 07 */ eCM_PICTURE_SETTINGS_2DHIGHSPEED,
    /* 08 */ eCM_PICTURE_SETTINGS_3D,
    /* 09 */ eCM_PICTURE_SETTINGS_BLENDING,
    /* 10 */ eCM_PICTURE_SETTINGS_USER,
    /* 11 */ eCM_PICTURE_SETTINGS_HDR,
    /* 12 */ eCM_PICTURE_SETTINGS_SRGB,
    /* 13 */ eCM_PICTURE_SETTINGS_SUPER_BRIGHT,
    /* 14 */ eCM_PICTURE_SETTINGS_SUPER_RED,
    /* 15 */ eCM_PICTURE_SETTINGS_3D_PASSIVE,
    /* 16 */ eCM_PICTURE_SETTINGS_HLG,

    eCM_PICTURE_SETTINGS_NUMBER,
}eCM_PICTURE_SETTINGS_ID;

typedef enum
{
    /* 00 */ eCM_LANGUAGE_ENGLISH,
    /* 01 */ eCM_LANGUAGE_FRENCH,
    /* 02 */ eCM_LANGUAGE_SPANISH,
    /* 03 */ eCM_LANGUAGE_GERMAN,
    /* 04 */ eCM_LANGUAGE_ITALIAN,
    /* 05 */ eCM_LANGUAGE_POLSKI,
    /* 06 */ eCM_LANGUAGE_RUSSIAN,
    /* 07 */ eCM_LANGUAGE_S_CHINESE,
    /* 08 */ eCM_LANGUAGE_T_CHINESE,
    /* 09 */ eCM_LANGUAGE_JAPANESE,
    /* 10 */ eCM_LANGUAGE_KOREAN,
    /* 11 */ eCM_LANGUAGE_PORTUGUESE,
    /* 12 */ eCM_LANGUAGE_DUTCH,
    /* 13 */ eCM_LANGUAGE_SWEDISH,
    /* 14 */ eCM_LANGUAGE_DANISH,
    /* 15 */ eCM_LANGUAGE_FINNISH,
    /* 16 */ eCM_LANGUAGE_GREEK,
    /* 17 */ eCM_LANGUAGE_HUNGARIAN,
    /* 18 */ eCM_LANGUAGE_CZECH,
    /* 19 */ eCM_LANGUAGE_THAILAND,
    /* 20 */ eCM_LANGUAGE_TURKISH,
    /* 21 */ eCM_LANGUAGE_VIETNAMESE,
    /* 22 */ eCM_LANGUAGE_INDONESIAN,
    /* 23 */ eCM_LANGUAGE_ROMANIAN,
    /* 24 */ eCM_LANGUAGE_SLOVAK,
    /* 25 */ eCM_LANGUAGE_NORWEGIAN,
    /* 26 */ eCM_LANGUAGE_ARABIC,

    eCM_LANGUAGE_NUMBER,
}eCM_LANGUAGE_ID;

typedef enum
{
    /* 00 */ eCM_SCALING_MODE_AUTO,
    /* 01 */ eCM_SCALING_MODE_NATIVE,
    /* 02 */ eCM_SCALING_MODE_4_3,
    /* 03 */ eCM_SCALING_MODE_LETTER_BOX,
    /* 04 */ eCM_SCALING_MODE_FULL_SIZE,
    /* 05 */ eCM_SCALING_MODE_FULL_WIDTH,
    /* 06 */ eCM_SCALING_MODE_FULL_HEIGHT,
    /* 07 */ eCM_SCALING_MODE_CUSTOM,
    /* 08 */ eCM_SCALING_MODE_3D,
    /* 09 */ eCM_SCALING_MODE_16_9,
    /* 10 */ eCM_SCALING_MODE_16_10,
    /* 11 */ eCM_SCALING_MODE_21_9,

    eCM_SCALING_MODE_NUMBER,
}eCM_SCALING_MODE_ID;

typedef enum
{
    /* 00 */ eCM_HOTKEY_SETTINGS_SIZE_PRESETS,
    /* 01 */ eCM_HOTKEY_SETTINGS_PICTURE_SETTINGS,
    /* 02 */ eCM_HOTKEY_SETTINGS_DEFAULT_VALUE,
    /* 03 */ eCM_HOTKEY_SETTINGS_DETAIL,
    /* 04 */ eCM_HOTKEY_SETTINGS_CONTRAST_ENHANCEMENT,
    /* 05 */ eCM_HOTKEY_SETTINGS_LIGHT_SOURCE_MODE,
    /* 06 */ eCM_HOTKEY_SETTINGS_FREEZE_SCREEN,
    /* 07 */ eCM_HOTKEY_SETTINGS_INFORMATION,
    /* 08 */ eCM_HOTKEY_SETTINGS_WARPBLEND_DISABLE,
    /* 09 */ eCM_HOTKEY_SETTINGS_BLANK_SCREEN,
    /* 10 */ eCM_HOTKEY_SETTINGS_SAVE_TO_USER,
    /* 11 */ eCM_HOTKEY_SETTINGS_PIP_PBP,
    /* 12 */ eCM_HOTKEY_SETTINGS_PC_MODE,
    /* 13 */ eCM_HOTKEY_SETTINGS_SHOW_MESSAGE,
    /* 14 */ eCM_HOTKEY_SETTINGS_USER_DATA,
    /* 15 */ eCM_HOTKEY_SETTINGS_NETWORK_SETUP,
    /* 16 */ eCM_HOTKEY_SETTINGS_PROJECTOR_ID,
    /* 17 */ eCM_HOTKEY_SETTINGS_ORIENTATION,
    /* 18 */ eCM_HOTKEY_SETTINGS_LOGO_CAPTURE,
    /* 19 */ eCM_HOTKEY_SETTINGS_CUSTOM_RGBCYM,
    /* 20 */ eCM_HOTKEY_SETTINGS_MULTI_PROJECTION,
    /* 21 */ eCM_HOTKEY_SETTINGS_RESET_SELECTIVE,
    /* 22 */ eCM_HOTKEY_SETTINGS_QUICK_SWITCH_CODE,
    /* 23 */ eCM_HOTKEY_SETTINGS_AUDIO_MUTE,
    /* 24 */ eCM_HOTKEY_SETTINGS_AUDIO_VOLUME,
    /* 25 */ eCM_HOTKEY_SETTINGS_HDMI1,
    /* 26 */ eCM_HOTKEY_SETTINGS_HDMI2,
    /* 27 */ eCM_HOTKEY_SETTINGS_TEST_PATTERN,
    /* 28 */ eCM_HOTKEY_SETTINGS_COLOR_TEMPERATURE,

    eCM_HOTKEY_SETTINGS_NUMBER,
}eCM_HOTKEY_SETTINGS_ID;

typedef enum
{
    /* 00 */ eCM_SCREEN_MODE_OFF,
    /* 01 */ eCM_SCREEN_MODE_PIP,
    /* 02 */ eCM_SCREEN_MODE_PBP,

    eCM_SCREEN_MODE_NUMBER,
}SCREEN_MODE;

typedef enum
{
    /* 00 */ eCM_MENU_LOCATION_TOP_LEFT,
    /* 01 */ eCM_MENU_LOCATION_TOP_RIGHT,
    /* 02 */ eCM_MENU_LOCATION_CENTER,
    /* 03 */ eCM_MENU_LOCATION_BOTTOM_LEFT,
    /* 04 */ eCM_MENU_LOCATION_BOTTOM_RIGHT,

    eCM_MENU_LOCATION_NUMBER,
}eCM_MENU_LOCATION_ID;

typedef enum
{
    /* 00 */ eCM_OVERSCAN_OFF,
    /* 01 */ eCM_OVERSCAN_ZOOM,
    /* 02 */ eCM_OVERSCAN_CROP,

    eCM_OVERSCAN_NUMBER,
}eCM_OVERSCAN_ID;

typedef enum
{
    /* 00 */ eCM_COLOR_SPACE_AUTO,
    /* 01 */ eCM_COLOR_SPACE_RGB_FULL,
    /* 02 */ eCM_COLOR_SPACE_RGB_LIMITED,
    /* 03 */ eCM_COLOR_SPACE_YUV_REC709,
    /* 04 */ eCM_COLOR_SPACE_YUV_REC601,

    eCM_COLOR_SPACE_NUMBER,
}eCM_COLOR_SPACE_ID;

typedef enum
{
    /* 00 */ eCM_3D_MODE_AUTO,
    /* 01 */ eCM_3D_MODE_ON,
    /* 02 */ eCM_3D_MODE_OFF,
    /* 03 */ eCM_3D_MODE_PASSIVE_3D,

    eCM_3D_MODE_NUMBER,
}eCM_3D_MODE_ID;

typedef enum
{
    /* 00 */ eCM_3D_FORMAT_AUTO,
    /* 01 */ eCM_3D_FORMAT_FRAME_PACKING,
    /* 02 */ eCM_3D_FORMAT_SIDE_BY_SIDE,
    /* 03 */ eCM_3D_FORMAT_TOP_AND_BOTTOM,
    /* 04 */ eCM_3D_FORMAT_FRAME_SEQUENTIAL,
    /* 05 */ eCM_3D_FORMAT_OFF,
    /* 06 */ eCM_3D_FORMAT_DUALPIPE,
    /* 07 */ eCM_3D_FORMAT_DUALPIPE_3D,
    /* 08 */ eCM_3D_FORMAT_4K3D,
    /* 09 */ eCM_3D_FORMAT_4K3D_DUALPIPE,

    eCM_3D_FORMAT_NUMBER,
}eCM_3D_FORMAT_ID;

typedef enum
{
    /* 00 */ eCM_3D_TECH_DLP_LINK,
    /* 01 */ eCM_3D_TECH_3D_SYNC,

    eCM_3D_TECH_NUMBER,
}eCM_3D_TECH_ID;

typedef enum
{
    /* 00 */ eCM_3D_2D_3D,
    /* 01 */ eCM_3D_2D_2D_LEFT,
    /* 02 */ eCM_3D_2D_2D_RIGHT,

    eCM_3D_2D_NUMBER,
}eCM_3D_2D_ID;

typedef enum
{
    /* 00 */ eCM_3D_SYNC_OUT_TO_EMITTER,
    /* 01 */ eCM_3D_SYNC_OUT_TO_NEXT_PROJECTOR,

    eCM_3D_SYNC_OUT_NUMBER,
}eCM_3D_SYNC_OUT_ID;

typedef enum
{
    /* 00 */ eCM_3D_LR_REFERENCE_1ST_FRAME,
    /* 01 */ eCM_3D_LR_REFERENCE_FIELD_GPIO,

    eCM_3D_LR_REFERENCE_NUMBER,
}eCM_3D_LR_REFERENCE_ID;

typedef enum
{
    /* 00 */ eCM_SYSTEM_PROTECT_STATUS_NORMAL,
    /* 01 */ eCM_SYSTEM_PROTECT_STATUS_PIN_LOCK,
    /* 02 */ eCM_SYSTEM_PROTECT_STATUS_FIRST_STARTUP,

    eCM_SYSTEM_PROTECT_STATUS_NUMBERS,
} eCM_SYSTEM_PROTECT_STATUS;

typedef enum
{
    /* 00 */ eCM_3D_SYNC_TYPE_AUTO,
    /* 01 */ eCM_3D_SYNC_TYPE_INTERNAL,
    /* 02 */ eCM_3D_SYNC_TYPE_EXTERNAL,

    eCM_3D_SYNC_TYPE_NUMBER,
}eCM_3D_SYNC_TYPE_ID;

typedef enum
{
    /* 00 */ eCM_CONTRAST_ENHANCEMENT_OFF,
    /* 01 */ eCM_CONTRAST_ENHANCEMENT_DYNAMIC_BLACK,
    /* 02 */ eCM_CONTRAST_ENHANCEMENT_REAL_BLACK,

    eCM_CONTRAST_ENHANCEMENT_NUMBER,
}eCM_CONTRAST_ENHANCEMENT_ID;

typedef enum
{
    /* 00 */ eCM_GAMMA_FILM,
    /* 01 */ eCM_GAMMA_VIDEO,
    /* 02 */ eCM_GAMMA_GRAPHICS,
    /* 03 */ eCM_GAMMA_STANDARD,
    /* 04 */ eCM_GAMMA_3D,
    /* 05 */ eCM_GAMMA_BLACKBOARD,
    /* 06 */ eCM_GAMMA_DICOM,
    /* 07 */ eCM_GAMMA_1_8,
    /* 08 */ eCM_GAMMA_1_9,
    /* 09 */ eCM_GAMMA_2_0,
    /* 10 */ eCM_GAMMA_2_1,
    /* 11 */ eCM_GAMMA_2_2,
    /* 12 */ eCM_GAMMA_2_3,
    /* 13 */ eCM_GAMMA_2_4,
    /* 14 */ eCM_GAMMA_2_5,
    /* 15 */ eCM_GAMMA_2_6,
    /* 16 */ eCM_GAMMA_CRT, //VIVID
    /* 17 */ eCM_GAMMA_ENHANCED,
    /* 18 */ eCM_GAMMA_HDR_STANDARD,
    /* 19 */ eCM_GAMMA_HDR_Film_HC,				//G100_Clare_0040
    /* 20 */ eCM_GAMMA_HDR_Bright_HC,			//G100_Clare_0040
    /* 21 */ eCM_GAMMA_HDR_Detail_HC,			//G100_Clare_0040
    /* 22 */ eCM_GAMMA_HDR_Standard_Optoma,		//G100_Clare_0040
    /* 23 */ eCM_GAMMA_HDR_Film_Optoma,			//G100_Clare_0040
    /* 24 */ eCM_GAMMA_HDR_Bright_Optoma,		//G100_Clare_0040
    /* 25 */ eCM_GAMMA_HDR_Detail_Optoma,		//G100_Clare_0040
    /* 26 */ eCM_GAMMA_HLG_STANDARD,
    /* 27 */ eCM_GAMMA_HLG_Film_HC,
    /* 28 */ eCM_GAMMA_HLG_Bright_HC,
    /* 29 */ eCM_GAMMA_HLG_Detail_HC,
    /* 30 */ eCM_GAMMA_1_6,
    /* 31 */ eCM_GAMMA_1_7,
    /* 32 */ eCM_GAMMA_2_7,
    /* 33 */ eCM_GAMMA_2_8,
    /* 34 */ eCM_GAMMA_2_9,
    /* 35 */ eCM_GAMMA_3_0,
    /* 36 */ eCM_GAMMA_3_1,
    /* 37 */ eCM_GAMMA_3_2,
    /* 38 */ eCM_GAMMA_3_3,

    eCM_GAMMA_NUMBER,
}eCM_GAMMA_ID;

typedef enum
{
    /* 00 */ eCM_EDGE_ENHANCEMENT_OFF,
    /* 01 */ eCM_EDGE_ENHANCEMENT_NORMAL,
    /* 02 */ eCM_EDGE_ENHANCEMENT_MAXIMUM,

    eCM_EDGE_ENHANCEMENT_NUMBER,
}eCM_EDGE_ENHANCEMENT_ID;

typedef enum
{
    /* 00 */ eCM_COLOR_WHEEL_SPEED_2X,
    /* 01 */ eCM_COLOR_WHEEL_SPEED_3X,
    /* 02 */ eCM_COLOR_WHEEL_SPEED_1X,

    eCM_COLOR_WHEEL_SPEED_NUMBER,
}eCM_COLOR_WHEEL_SPEED_ID;

typedef enum
{
    /* 00 */ eCM_LENS_TYPE_NA,
    /* 01 */ eCM_LENS_TYPE_A20,
    /* 02 */ eCM_LENS_TYPE_A21,
    /* 03 */ eCM_LENS_TYPE_A22,
    /* 04 */ eCM_LENS_TYPE_A23,
    /* 05 */ eCM_LENS_TYPE_A24,
    /* 05 */ eCM_LENS_TYPE_A25,
    /* 06 */ eCM_LENS_TYPE_A26,

    eCM_LENS_TYPE_NUMBER,
}eCM_LENS_TYPE_ID;

typedef enum
{
    /* 00 */ eCM_CEILING_MOUNT_OFF,
    /* 01 */ eCM_CEILING_MOUNT_ON,
    /* 02 */ eCM_CEILING_MOUNT_AUTO,

    eCM_CEILING_MOUNT_NUMBER,
}eCM_CEILING_MOUNT_ID;

typedef enum
{
    /* 00 */ eCM_REAR_PROJECTION_FRONT,
    /* 01 */ eCM_REAR_PROJECTION_REAR,

    eCM_REAR_PROJECTION_NUMBER,
}eCM_REAR_PROJECTION_ID;

typedef enum
{
    /* 00 */ eCM_SPLASH_STARTUP_FACTORY_LOGO,
    /* 01 */ eCM_SPLASH_STARTUP_BLUE,
    /* 02 */ eCM_SPLASH_STARTUP_BLACK,
    /* 03 */ eCM_SPLASH_STARTUP_WHITE,

    eCM_SPLASH_STARTUP_NUMBER,
}eCM_SPLASH_STARTUP_ID;

typedef enum
{
    /* 00 */ eCM_STANDBY_MODE_0_5W,
    /* 01 */ eCM_STANDBY_MODE_2W,
    /* 02 */ eCM_STANDBY_MODE_COMMUNICATION,
    /* 03 */ eCM_STANDBY_MODE_2W_20MIN,
    /* 04 */ eCM_STANDBY_MODE_COMMUNICATION_20MIN,

    eCM_STANDBY_MODE_NUMBER
}eCM_STANDBY_MODE_ID;

typedef enum
{
    /* 00 */ eCM_AUTO_SHUTDOWN_OFF,
    /* 01 */ eCM_AUTO_SHUTDOWN_5MIN,
    /* 02 */ eCM_AUTO_SHUTDOWN_10MIN,
    /* 03 */ eCM_AUTO_SHUTDOWN_15MIN,
    /* 04 */ eCM_AUTO_SHUTDOWN_20MIN,
    /* 05 */ eCM_AUTO_SHUTDOWN_25MIN,
    /* 06 */ eCM_AUTO_SHUTDOWN_30MIN,

    eCM_AUTO_SHUTDOWN_NUMBER,
}eCM_AUTO_SHUTDOWN_ID;

typedef enum
{
    /* 00 */ eCM_SLEEP_TIMER_OFF,
    /* 01 */ eCM_SLEEP_TIMER_2HOURS,
    /* 02 */ eCM_SLEEP_TIMER_4HOURS,
    /* 03 */ eCM_SLEEP_TIMER_6HOURS,

    eCM_SLEEP_TIMER_NUMBER,
}eCM_SLEEP_TIMER_ID;

typedef enum
{
    /* 00 */ eCM_SERIAL_PORT_BAUD_RATE_1200,
    /* 01 */ eCM_SERIAL_PORT_BAUD_RATE_2400,
    /* 02 */ eCM_SERIAL_PORT_BAUD_RATE_4800,
    /* 03 */ eCM_SERIAL_PORT_BAUD_RATE_9600,
    /* 04 */ eCM_SERIAL_PORT_BAUD_RATE_14400,
    /* 05 */ eCM_SERIAL_PORT_BAUD_RATE_19200,
    /* 06 */ eCM_SERIAL_PORT_BAUD_RATE_38400,
    /* 07 */ eCM_SERIAL_PORT_BAUD_RATE_57600,
    /* 08 */ eCM_SERIAL_PORT_BAUD_RATE_115200,

    eCM_SERIAL_PORT_BAUD_RATE_NUMBER,
}eCM_SERIAL_PORT_BAUD_RATE_ID;

typedef enum
{
    /* 00 */ eCM_SERIAL_PORT_PATH_RS232,
    /* 01 */ eCM_SERIAL_PORT_PATH_HDBASET,
    /* 02 */ eCM_SERIAL_PORT_PATH_SLOT1,
    /* 03 */ eCM_SERIAL_PORT_PATH_SLOT2,

    eCM_SERIAL_PORT_PATH_NUMBER,
}eCM_SERIAL_PORT_PATH_ID;

typedef enum
{
    /* 00 */ eCM_SERIAL_PORT_PATH_FROM_SLOT1,
    /* 01 */ eCM_SERIAL_PORT_PATH_FROM_SLOT2,

    eCM_SERIAL_PORT_PATH_FROM_NUMBER,
}eCM_SERIAL_PORT_PATH_FROM_ID;

typedef enum
{
    /* 00 */ eCM_KEYPAD_BACKLIGHT_5_SECS,
    /* 01 */ eCM_KEYPAD_BACKLIGHT_10_SECS,
    /* 02 */ eCM_KEYPAD_BACKLIGHT_20_SECS,
    /* 03 */ eCM_KEYPAD_BACKLIGHT_30_SECS,
    /* 04 */ eCM_KEYPAD_BACKLIGHT_ALWAYS_ON,
    /* 05 */ eCM_KEYPAD_BACKLIGHT_ALWAYS_OFF,

    eCM_KEYPAD_BACKLIGHT_NUMBER,
}eCM_KEYPAD_BACKLIGHT_ID;

typedef enum
{
    /* 00 */ eCM_STATUS_LED_ALWAYS_ON,
    /* 01 */ eCM_STATUS_LED_ALWAYS_OFF,
    /* 02 */ eCM_STATUS_LED_WARNING_ERRORS_ONLY,

    eCM_STATUS_LED_NUMBER,
}eCM_STATUS_LED_ID;

typedef enum
{
    /* 00 */ eCM_WALL_COLOR_WHITE,
    /* 01 */ eCM_WALL_COLOR_GRAY130,
    /* 02 */ eCM_WALL_COLOR_LIGHT_YELLOW,
    /* 03 */ eCM_WALL_COLOR_OFF,
    /* 04 */ eCM_WALL_COLOR_BLACKBOARD,
    /* 05 */ eCM_WALL_COLOR_LIGHT_GREEN,
    /* 06 */ eCM_WALL_COLOR_LIGHT_BLUE,
    /* 07 */ eCM_WALL_COLOR_PINK,
    /* 08 */ eCM_WALL_COLOR_GRAY,
    /* 09 */ eCM_WALL_COLOR_AUTO,	//G100_Clare_0035

    eCM_WALL_COLOR_NUMBER,
}eCM_WALL_COLOR_ID;

typedef enum
{
    /* 00 */ eCM_POWER_MODE_CONSTANT_POWER,
    /* 01 */ eCM_POWER_MODE_CONSTANT_INTENSITY,
    /* 02 */ eCM_POWER_MODE_ECO1,
    /* 03 */ eCM_POWER_MODE_ECO2,
    /* 04 */ eCM_POWER_MODE_RENTAL_MODE,
    /* 05 */ eCM_POWER_MODE_QUIET_MODE,
    /* 06 */ eCM_POWER_MODE_CUSTOM_MODE,
    /* 07 */ eCM_POWER_MODE_LOW_BRIGHTNESS_MODE,
    /* 08 */ eCM_POWER_MODE_RESERVE_01,
    /* 09 */ eCM_POWER_MODE_RESERVE_02,
    /* 10 */ eCM_POWER_MODE_100,
    /* 11 */ eCM_POWER_MODE_50,
    /* 12 */ eCM_POWER_MODE_30,
    /* 13 */ eCM_POWER_MODE_20,

    eCM_POWER_MODE_NUMBER,
}eCM_POWER_MODE_ID;

typedef enum
{
    /* 00 */ eCM_PIP_SIZE_SMALL,
    /* 01 */ eCM_PIP_SIZE_MEDIUM,
    /* 02 */ eCM_PIP_SIZE_LARGE,

    eCM_PIP_SIZE_NUMBER,
}eCM_PIP_SIZE_ID;

typedef enum
{
    /* 00 */ eCM_MAIN_LAYOUT_PBP_MAIN_LEFT,
    /* 01 */ eCM_MAIN_LAYOUT_PBP_MAIN_TOP,
    /* 02 */ eCM_MAIN_LAYOUT_PBP_MAIN_RIGHT,
    /* 03 */ eCM_MAIN_LAYOUT_PBP_MAIN_BOTTOM,
    /* 04 */ eCM_MAIN_LAYOUT_PIP_BOTTOM_RIGHT,
    /* 05 */ eCM_MAIN_LAYOUT_PIP_BOTTOM_LEFT,
    /* 06 */ eCM_MAIN_LAYOUT_PIP_TOP_LEFT,
    /* 07 */ eCM_MAIN_LAYOUT_PIP_TOP_RIGHT,

    eCM_MAIN_LAYOUT_NUMBER,
}eCM_MAIN_LAYOUT_ID;

typedef enum
{
    /* 00 */ eCM_INPUT_KEY_CHANGE_SOURCE,
    /* 01 */ eCM_INPUT_KEY_LIST_ALL_SOURCE,
    /* 02 */ eCM_INPUT_KEY_AUTO_SOURCE,

    eCM_INPUT_KEY_NUMBER,
}eCM_INPUT_KEY_ID;

typedef enum
{
    /* 00 */ eCM_COLOR_TEMPERATURE_WARMEST,
    /* 01 */ eCM_COLOR_TEMPERATURE_WARM,
    /* 02 */ eCM_COLOR_TEMPERATURE_COOL,
    /* 03 */ eCM_COLOR_TEMPERATURE_NATIVE,

    eCM_COLOR_TEMPERATURE_NUMBER,
}eCM_COLOR_TEMPERATURE_ID;

typedef enum
{
    /* 00 */ eCM_CUSTOM_CT_DEFAULT,
    /* 01 */ eCM_CUSTOM_CT_3200K,
    /* 02 */ eCM_CUSTOM_CT_4200K,
    /* 03 */ eCM_CUSTOM_CT_5200K,
    /* 04 */ eCM_CUSTOM_CT_6200K,
    /* 05 */ eCM_CUSTOM_CT_6500K,
    /* 06 */ eCM_CUSTOM_CT_8200K,
    /* 07 */ eCM_CUSTOM_CT_9300K,

    eCM_CUSTOM_CT_NUMBER,
}eCM_CUSTOM_COLOR_TEMPERATURE_ID;


typedef enum
{
    /* 00 */ eCM_MULTI_SYNC_MODE_OFF,
    /* 01 */ eCM_MULTI_SYNC_MODE_MASTER,
    /* 02 */ eCM_MULTI_SYNC_MODE_SLAVE,

    eCM_MULTI_SYNC_MODE_NUMBER,
}eCM_MULTI_SYNC_MODE_ID;

typedef enum
{
    /* 00 */ eCM_BLENDING_GAMMA_1_8,
    /* 01 */ eCM_BLENDING_GAMMA_1_9,
    /* 02 */ eCM_BLENDING_GAMMA_2_0,
    /* 03 */ eCM_BLENDING_GAMMA_2_1,
    /* 04 */ eCM_BLENDING_GAMMA_2_2,
    /* 05 */ eCM_BLENDING_GAMMA_2_3,
    /* 06 */ eCM_BLENDING_GAMMA_2_4,

    eCM_BLENDING_GAMMA_NUMBER,
}eCM_BLENDING_GAMMA_ID;

typedef enum
{
    /* 00 */ eCM_BACKUPINPUT_AUTOSWITCH_SEAMLESS,
    /* 01 */ eCM_BACKUPINPUT_AUTOSWITCH_BACKUP,
    /* 02 */ eCM_BACKUPINPUT_AUTOSWITCH_SIGNLE,

    eCM_BACKUPINPUT_AUTOSWITCH_NUMBER,
}eCM_BACKUPINPUT_AUTOSWITCH_ID;

typedef enum
{
    /* 00 */ eCM_EDID_TYPE_V14,
    /* 01 */ eCM_EDID_TYPE_V20,
    /* 02 */ eCM_EDID_TYPE_CUSTOMIZED,

    eCM_EDID_TYPE_NUMBER
}eCM_EDID_TYPE_ID;

typedef enum
{
    /* 00 */ eCM_LAN_PATH_SWITCH_RJ45,
    /* 01 */ eCM_LAN_PATH_SWITCH_HDBASET,

    eCM_LAN_PATH_SWITCH_NUMBER
}eCM_LAN_PATH_SWITCH_ID;

typedef enum
{
    /* 00 */ eCM_OSD_TIMEOUT_OFF,
    /* 01 */ eCM_OSD_TIMEOUT_5_SEC,
    /* 02 */ eCM_OSD_TIMEOUT_10_SEC,
    /* 03 */ eCM_OSD_TIMEOUT_15_SEC,
    /* 04 */ eCM_OSD_TIMEOUT_30_SEC,
    /* 05 */ eCM_OSD_TIMEOUT_60_SEC,
    /* 06 */ eCM_OSD_TIMEOUT_120_SEC,
    /* 07 */ eCM_OSD_TIMEOUT_180_SEC,
    /* 08 */ eCM_OSD_TIMEOUT_20_SEC,

    eCM_OSD_TIMEOUT_NUMBER
}eCM_OSD_TIMEOUT_ID;

typedef enum
{
    /* 00 */ eCM_BACKGROUND_COLOR_BLUE,
    /* 01 */ eCM_BACKGROUND_COLOR_RED,
    /* 02 */ eCM_BACKGROUND_COLOR_GREEN,
    /* 03 */ eCM_BACKGROUND_COLOR_GRAY,
    /* 04 */ eCM_BACKGROUND_COLOR_LOGO,
    /* 05 */ eCM_BACKGROUND_COLOR_WHITE,
    /* 06 */ eCM_BACKGROUND_COLOR_BLACK,

    eCM_BACKGROUND_COLOR_NUMBER,
}eCM_BACKGROUND_COLOR_ID;

typedef enum
{
    /* 00 */ eCM_LIGHT_SOURCE_MODE_NORMAL,
    /* 01 */ eCM_LIGHT_SOURCE_MODE_ECO_MODE,
    /* 02 */ eCM_LIGHT_SOURCE_MODE_CUSTOM_MODE,

    eCM_LIGHT_SOURCE_MODE_NUMBER
}eCM_LIGHT_SOURCE_MODE_ID;

typedef enum
{
    /* 00 */ eCM_LENS_MEMORY_SAVE_1,
    /* 01 */ eCM_LENS_MEMORY_SAVE_2,
    /* 02 */ eCM_LENS_MEMORY_SAVE_3,
    /* 03 */ eCM_LENS_MEMORY_SAVE_4,
    /* 04 */ eCM_LENS_MEMORY_SAVE_5,

    eCM_LENS_MEMORY_SAVE_NUMBER
}eCM_LENS_MEMORY_SAVE_ID;

typedef enum
{
    /* 00 */ eCM_LENS_MEMORY_APPLY_1,
    /* 01 */ eCM_LENS_MEMORY_APPLY_2,
    /* 02 */ eCM_LENS_MEMORY_APPLY_3,
    /* 03 */ eCM_LENS_MEMORY_APPLY_4,
    /* 04 */ eCM_LENS_MEMORY_APPLY_5,

    eCM_LENS_MEMORY_APPLY_NUMBER
}eCM_LENS_MEMORY_APPLY_ID;

typedef enum
{
    /* 00 */ eCM_LENS_MOVE_TOP,
    /* 01 */ eCM_LENS_MOVE_BOTTOM,
    /* 02 */ eCM_LENS_MOVE_CENTER,
    /* 03 */ eCM_LENS_H_MOVE_CENTER,
    /* 04 */ eCM_LENS_V_MOVE_CENTER,
    /* 05 */ eCM_LENS_HV_MOVE_CENTER,

    eCM_LENS_MOVE_NUMBER
}eCM_LENS_MOVE_NUMBER_ID;

typedef enum
{
    /* 00 */ eCM_LOGO_PATTERN_FACTORY_LOGO,
    /* 01 */ eCM_LOGO_PATTERN_BLUE,
    /* 02 */ eCM_LOGO_PATTERN_BLACK,
    /* 03 */ eCM_LOGO_PATTERN_WHITE,

    eCM_LOGO_PATTERN_MAX_NUMBER
} eCM_LOGO_PATTERN_ID;

typedef enum
{
    /* 00 */ eCM_LOW_LATENCY_MODE_OFF,
    /* 01 */ eCM_LOW_LATENCY_MODE_TYPICAL,
    /* 02 */ eCM_LOW_LATENCY_MODE_ULTRA,

    eCM_LOW_LATENCY_MODE_NUMBER,
} eCM_LOW_LATENCY_MODE_ID;

typedef enum
{
    /* 00 */ eCM_SHARPNESS_LEVEL0,
    /* 01 */ eCM_SHARPNESS_LEVEL1,
    /* 02 */ eCM_SHARPNESS_LEVEL2,
    /* 03 */ eCM_SHARPNESS_LEVEL3_MINIMUM,
    /* 04 */ eCM_SHARPNESS_LEVEL4,
    /* 05 */ eCM_SHARPNESS_LEVEL5_LOW,
    /* 06 */ eCM_SHARPNESS_LEVEL6,
    /* 07 */ eCM_SHARPNESS_LEVEL7,
    /* 08 */ eCM_SHARPNESS_LEVEL8_NORMAL,
    /* 09 */ eCM_SHARPNESS_LEVEL9,
    /* 10 */ eCM_SHARPNESS_LEVEL10,
    /* 11 */ eCM_SHARPNESS_LEVEL11_HIGH,
    /* 12 */ eCM_SHARPNESS_LEVEL12,
    /* 13 */ eCM_SHARPNESS_LEVEL13_MAXIMUM,
    /* 14 */ eCM_SHARPNESS_LEVEL14,
    /* 15 */ eCM_SHARPNESS_LEVEL15,

    eCM_SHARPNESS_NUMBER,
} eCM_SHARPNESS_ID;

typedef enum
{
    /* 00 */ eCM_HDR_LEVEL_SDR,
    /* 01 */ eCM_HDR_LEVEL1,
    /* 02 */ eCM_HDR_LEVEL2,
    /* 03 */ eCM_HDR_LEVEL3,
    /* 04 */ eCM_HDR_LEVEL4,

    eCM_HDR_LEVEL_NUMBER,
} eCM_HDR_LEVEL_ID;

typedef enum
{
    /* 00 */ eCM_HDR,
    /* 01 */ eCM_DYANAMIC_CONTRAST,
    /* 02 */ eCM_SDR_CUSTOM,

    eCM_HDR_GAMMA_FUNCTION_NUMBER,
} eCM_HDR_GAMMA_FUNCTION;

typedef enum
{
    /* 00 */ eCM_HDR_AUTO,
    /* 01 */ eCM_HDR_MANUAL,

    eCM_HDR_MODE_NUMBER,
} eCM_HDR_MODE;

typedef enum
{
    /* 00 */ eCM_HDR_500_NIT,
    /* 01 */ eCM_HDR_1000_NIT,
    /* 02 */ eCM_HDR_2000_NIT,
    /* 03 */ eCM_HDR_4000_NIT,
    /* 04 */ eCM_HDR_CUSTOM_NIT,

    eCM_HDR_MANUAL_LEVEL_NUMBER,
} eCM_HDR_MANUAL_LEVEL;

typedef enum
{
    /* 00 */ eCM_SOURCE_KEY_CHANGE_SOURCE,
    /* 01 */ eCM_SOURCE_KEY_LIST_ALL_SOURCE,
    /* 02 */ eCM_SOURCE_KEY_AUTO_SOURCE,

    eCM_SOURCE_KEY_NUMBER,
}eCM_SOURCE_KEY_ID;

typedef enum
{
    /* 00 */ eCM_DATETIME_CLOCK_MODE_NTP_SERVER,
    /* 01 */ eCM_DATETIME_CLOCK_MODE_MANUAL,

    eCM_DATETIME_CLOCK_MODE_NUMBER,
}eCM_DATETIME_CLOCK_MODE_ID;

typedef enum
{
    /* 00 */ eCM_DATETIME_UPDATE_INTERVAL_HOURLY,
    /* 01 */ eCM_DATETIME_UPDATE_INTERVAL_DAILY,

    eCM_DATETIME_UPDATE_INTERVAL_NUMBER,
}eCM_DATETIME_UPDATE_INTERVAL_ID;

typedef enum
{
    /* 00 */ eCM_HDMI_OUTPUT_HDMI1,
    /* 01 */ eCM_HDMI_OUTPUT_HDMI2,
    /* 02 */ eCM_HDMI_OUTPUT_AUTO,
    /* 03 */ eCM_HDMI_OUTPUT_DP,
    /* 04 */ eCM_HDMI_OUTPUT_HDBASET,

    eCM_HDMI_OUTPUT_NUMBER,
}eCM_HDMI_OUTPUT_ID;

typedef enum
{
    /* 00 */ eCM_WEEKDAY_SUNDAY,
    /* 01 */ eCM_WEEKDAY_MONDAY,
    /* 02 */ eCM_WEEKDAY_TUESDAY,
    /* 03 */ eCM_WEEKDAY_WEDNESDAY,
    /* 04 */ eCM_WEEKDAY_THURSDAY,
    /* 05 */ eCM_WEEKDAY_FRIDAY,
    /* 06 */ eCM_WEEKDAY_SATURDAY,
}eCM_WEEKDAY_ID;

//R70G2_David_0096 start
typedef enum
{
    eCM_NATICE_RESOLUTION_1080P,
    eCM_NATICE_RESOLUTION_WUXGA,
    eCM_NATICE_RESOLUTION_1920x816,
    eCM_NATICE_RESOLUTION_1920x1020,
    eCM_NATICE_RESOLUTION_1920x720,

    eCM_NATICE_RESOLUTION_NUMBER,
} eCM_NATICE_RESOLUTION_ID;
//R70G2_David_0096 end

typedef enum
{
    /* 00 */ eCM_USER_LOGO_FAIL, //status for web
    /* 01 */ eCM_USER_LOGO_PASS, //status for web
    /* 02 */ eCM_USER_LOGO_2D,
    /* 03 */ eCM_USER_LOGO_3D,
    /* 04 */ eCM_USER_LOGO_SERVICE_2D,
    /* 05 */ eCM_USER_LOGO_SERVICE_3D,

    eCM_USER_LOGO_NUMBER,
}eCM_USER_LOGO_ID;

typedef enum
{
    /* 00 */ eCM_AUTO_SIGNAL_RESYNC_NORMAL,
    /* 01 */ eCM_AUTO_SIGNAL_RESYNC_ENHANCED,

    eCM_AUTO_SIGNAL_RESYNC_NUMBER,
}eCM_AUTO_SIGNAL_RESYNC_ID;

typedef enum
{
    /* 00 */ eCM_PROJECTION_NORMAL,
    /* 01 */ eCM_PROJECTION_REAR,
    /* 02 */ eCM_PROJECTION_CEILING,
    /* 03 */ eCM_PROJECTION_REAR_CEILING,

    eCM_PROJECTION_NUMBER,
}eCM_PROJECTION_ID;// RICOH Style

typedef enum
{
    /* 00 */ eCM_SIGNAL_DETECT_WIDE_PRIORITY,
    /* 01 */ eCM_SIGNAL_DETECT_4_3_PRIORITY,

    eCM_SIGNAL_DETECT_NUMBER,
}eCM_SIGNAL_DETECT_ID;// RICOH Style

typedef enum
{
    /* 00 */ eCM_CCVTWO_INTERFACE_CONTROL_SYSTEM,
    /* 01 */ eCM_CCVTWO_INTERFACE_VC_FOUR,
    /* 02 */ eCM_CCVTWO_INTERFACE_ROOM_VIEW,
    /* 03 */ eCM_CCVTWO_INTERFACE_FITC,

    eCM_CCVTWO_INTERFACE_NUMBER,
}_eCM_CCVTWO_INTERFACE_ID;

typedef enum
{
    /* 000 */ eCM_NETWORK_STATUS_MESSAGE_IDLE,
    /* 001 */ eCM_NETWORK_STATUS_MESSAGE_SUCCESS,
    /* 002 */ eCM_NETWORK_STATUS_MESSAGE_ERROR_01,//osd trigger error.
    /* 003 */ eCM_NETWORK_STATUS_MESSAGE_ERROR_02,
    /* 004 */ eCM_NETWORK_STATUS_MESSAGE_ERROR_03,
    /* 005 */ eCM_NETWORK_STATUS_MESSAGE_PROCESSING,

    //trigger by lan.
    /* 100 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IP_OUT_OF_RANGE = 100,
    /* 101 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IP_CLASS_FAIL,
    /* 102 */ eCM_NETWORK_STATUS_MESSAGE_LAN_SUBMASK_OUT_OF_RANGE,
    /* 103 */ eCM_NETWORK_STATUS_MESSAGE_LAN_SUBMASK_BIT_FAIL,
    /* 104 */ eCM_NETWORK_STATUS_MESSAGE_LAN_SUBMASK_EMPTY,
    /* 105 */ eCM_NETWORK_STATUS_MESSAGE_LAN_GATEWAY_OUT_OF_RANGE,
    /* 106 */ eCM_NETWORK_STATUS_MESSAGE_LAN_GATEWAY_NOT_MATCH_IP,
    /* 107 */ eCM_NETWORK_STATUS_MESSAGE_LAN_GATEWAY_EMPTY,
    /* 108 */ eCM_NETWORK_STATUS_MESSAGE_LAN_GATEWAY_SUBMASK_EMPTY,

    /* 200 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_INPUT_ERROR = 200,
    /* 201 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_SSID_OUT_OF_RANGE,
    /* 202 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_START_IP_OUT_OF_RANGE,
    /* 203 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_START_IP_CLASS_FAIL,
    /* 204 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_END_IP_OUT_OF_RANGE,
    /* 205 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_END_IP_CLASS_FAIL,
    /* 206 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_START_END_IP_OUT_OF_RANGE,
    /* 207 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_CHECK_IP_FAIL,
    /* 208 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_NETMASK_OUT_OF_RANGE,
    /* 209 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_NETMASK_BIT_FAIL,
    /* 210 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_GATEWAY_OUT_OF_RANGE,
    /* 211 */ eCM_NETWORK_STATUS_MESSAGE_WLAN_GATEWAY_NOT_MATCH_IP,

    /* 300 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IPV6_IP_OUT_OF_RANGE = 300,
    /* 301 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IPV6_IP_CLASS_FAIL,
    /* 302 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IPV6_SUBMASK_OUT_OF_RANGE,
    /* 303 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IPV6_SUBMASK_BIT_FAIL,
    /* 303 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IPV6_SUBMASK_EMPTY,
    /* 304 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IPV6_GATEWAY_OUT_OF_RANGE,
    /* 305 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IPV6_GATEWAY_NOT_MATCH_IP,
    /* 305 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IPV6_GATEWAY_EMPTY,
    /* 305 */ eCM_NETWORK_STATUS_MESSAGE_LAN_IPV6_GATEWAY_SUBMASK_EMPTY,

    eCM_INVALID_WIFI_MESSAGE_NUMBER,
}eCM_NETWORK_STATUS_MESSAGE;

typedef enum
{
    /* 00 */ eCM_GEO_MEMORY_SAVE_NA,
    /* 01 */ eCM_GEO_MEMORY_SAVE_1,
    /* 02 */ eCM_GEO_MEMORY_SAVE_2,
    /* 03 */ eCM_GEO_MEMORY_SAVE_3,
    /* 04 */ eCM_GEO_MEMORY_SAVE_4,
    /* 05 */ eCM_GEO_MEMORY_SAVE_5,

    eCM_GEO_MEMORY_SAVE_NUMBER
}eCM_GEO_MEMORY_SAVE_ID;

typedef enum
{
    /* 00 */ eCM_GEO_MEMORY_APPLY_OFF,
    /* 01 */ eCM_GEO_MEMORY_APPLY_1,
    /* 02 */ eCM_GEO_MEMORY_APPLY_2,
    /* 03 */ eCM_GEO_MEMORY_APPLY_3,
    /* 04 */ eCM_GEO_MEMORY_APPLY_4,
    /* 05 */ eCM_GEO_MEMORY_APPLY_5,

    eCM_GEO_MEMORY_APPLY_NUMBER
}eCM_GEO_MEMORY_APPLY_ID;

typedef enum
{
    /* 00 */ eCM_CHANGE_LOGO_DEFAULT,
    /* 01 */ eCM_CHANGE_LOGO_NEUTRAL,
    /* 02 */ eCM_CHANGE_LOGO_USER,
    /* 03 */ eCM_CHANGE_LOGO_CAPTURED,

    eCM_CHANGE_LOGO_NUMBER,
}eCM_CHANGE_LOGO_ID;

typedef enum
{
    /* 00 */ eCM_AUDIO_OUTPUT_AUTO,
    /* 01 */ eCM_AUDIO_OUTPUT_INTERNAL_SPEAKER,
    /* 02 */ eCM_AUDIO_OUTPUT_LINE_OUT,

    eCM_AUDIO_OUTPUT_NUMBER,
}eCM_AUDIO_OUTPUT_ID;

typedef enum
{
    /* 00 */ eCM_FADE_TIMER_OFF = 1,
    /* 01 */ eCM_FADE_TIMER_0P5 = 5,
    /* 02 */ eCM_FADE_TIMER_1P0 = 10,
    /* 03 */ eCM_FADE_TIMER_1P5 = 15,
    /* 04 */ eCM_FADE_TIMER_2P0 = 20,
    /* 05 */ eCM_FADE_TIMER_2P5 = 25,
    /* 06 */ eCM_FADE_TIMER_3P0 = 30,
    /* 07 */ eCM_FADE_TIMER_3P5 = 35,
    /* 08 */ eCM_FADE_TIMER_4P0 = 40,
    /* 09 */ eCM_FADE_TIMER_4P5 = 45,
    /* 10 */ eCM_FADE_TIMER_5P0 = 50,

    eCM_FADE_TIMER_NUMBER,
}eCM_FADE_TIMER;

typedef enum
{
    /* 00 */ eCM_GRID_COLOR_GREEN,
    /* 01 */ eCM_GRID_COLOR_MAGENTA,
    /* 02 */ eCM_GRID_COLOR_RED,
    /* 03 */ eCM_GRID_COLOR_CYAN,

    eCM_GRID_COLOR_NUMBER,
}eCM_GRID_COLOR;

typedef enum
{
    /* 00 */ eCM_BIST_STATUS_INIT,
    /* 01 */ eCM_BIST_STATUS_BUSY,
    /* 02 */ eCM_BIST_STATUS_PASS,

    eCM_BIST_STATUS_NUMBER,
}eCM_BIST_STATUS;

typedef enum
{
    /* 00 */ eCM_GROUP_STATUS_STANDBY,
    /* 01 */ eCM_GROUP_STATUS_SLAVE,
    /* 02 */ eCM_GROUP_STATUS_MASTER,

    eCM_GROUP_STATUS_NUMBER,
}eCM_GROUP_STATUS;

typedef enum
{
    /* 00 */ eCM_GROUP_ACT_STATUS_SUCCESS,
    /* 01 */ eCM_GROUP_ACT_STATUS_NO_EXECUTE,
    /* 02 */ eCM_GROUP_ACT_STATUS_OVER_LIMIT,
    /* 03 */ eCM_GROUP_ACT_STATUS_DOING,

    eCM_GROUP_ACT_STATUS_NUMBER,
}eCM_GROUP_ACT_STATUS;

typedef enum
{
    /* 00 */ eCM_OMS_SERVICE_MODE_PRODUCTION = 0,
    /* 01 */ eCM_OMS_SERVICE_MODE_TESTING,

    eCM_OMS_SERVICE_MODE_NUMBER,
}eCM_OMS_SERVICE_MODE;


typedef enum
{
    /* 00 */ eCM_ACTUATOR_PATTERN_OFF,
    /* 01 */ eCM_ACTUATOR_PATTERN_0,
    /* 02 */ eCM_ACTUATOR_PATTERN_1,

    eCM_ACTUATOR_PATTERN_NUMBER,
}eCM_ACTUATOR_PATTERN_ID;

typedef enum
{
    /* 00 */ eCM_LOGO_REPLACE_EMPTY,
    /* 01 */ eCM_LOGO_REPLACE_READY,
    /* 02 */ eCM_LOGO_REPLACE_PROCESS,

    eCM_LOGO_REPLACE_NUMBER,
}eCM_LOGO_REPLACE_STATUS;

typedef enum
{
    /* 00 */ eCM_ARTNET_SETUP_MODE_OFF,
    /* 01 */ eCM_ARTNET_SETUP_MODE_ON,
    /* 02 */ eCM_ARTNET_SETUP_MODE_ON_2XXX,
    /* 03 */ eCM_ARTNET_SETUP_MODE_ON_10XXX,

    eCM_ARTNET_SETUP_MODE_NUMBER,
}eCM_ARTNET_SETUP_MODE;

typedef enum
{
    /* 00 */ eCM_ARTNET_CHANNEL_SETTINGS_USER1,
    /* 01 */ eCM_ARTNET_CHANNEL_SETTINGS_USER2,

    eCM_ARTNET_CHANNEL_SETTINGS_NUMBER,
}eCM_ARTNET_CHANNEL_SETTINGS_ID;

typedef enum
{
    /* 00 */ eCM_ARTNET_FUNC_NONE,
    /* 01 */ eCM_ARTNET_FUNC_ARTNET,
    /* 02 */ eCM_ARTNET_FUNC_LIGHT_SOURCE_SETTINGS,
    /* 03 */ eCM_ARTNET_FUNC_INPUT,
    /* 04 */ eCM_ARTNET_FUNC_LENS_SHIFT_H,
    /* 05 */ eCM_ARTNET_FUNC_LENS_SHIFT_V,
    /* 06 */ eCM_ARTNET_FUNC_FOCUS,
    /* 07 */ eCM_ARTNET_FUNC_ZOOM,
    /* 08 */ eCM_ARTNET_FUNC_LENS_FUNCTION,
    /* 09 */ eCM_ARTNET_FUNC_LENS_CONTROL,
    /* 10 */ eCM_ARTNET_FUNC_LENS_MEMORY,
    /* 11 */ eCM_ARTNET_FUNC_KEYSTONE_H,
    /* 12 */ eCM_ARTNET_FUNC_KEYSTONE_V,
    /* 13 */ eCM_ARTNET_FUNC_POWER,
    /* 14 */ eCM_ARTNET_FUNC_SHUTTER,
    /* 15 */ eCM_ARTNET_FUNC_FREEZE,
    /* 16 */ eCM_ARTNET_FUNC_TEST_PATTERN,

    eCM_ARTNET_FUNC_NUMBER,
}eCM_ARTNET_FUNCTION_ID;

typedef enum
{
    /* 00 */ eCM_FILTER_FOG,
    /* 01 */ eCM_FILTER_DUST,

    eCM_FILTER_TYPE_NUMBER,
}eCM_FILTER_TYPE;

typedef enum
{
    /* 00 */ eCM_DUST_REMAINING_TIME_4000,
    /* 01 */ eCM_DUST_REMAINING_TIME_3500,
    /* 02 */ eCM_DUST_REMAINING_TIME_3000,
    /* 03 */ eCM_DUST_REMAINING_TIME_2500,
    /* 04 */ eCM_DUST_REMAINING_TIME_2000,
    /* 05 */ eCM_DUST_REMAINING_TIME_1500,
    /* 06 */ eCM_DUST_REMAINING_TIME_1000,

    eCM_DUST_REMAINING_TIME_NUMBER,
}eCM_DUST_REMAINING_TIME;

typedef enum
{
    /* 00 */ eCM_FOG_REMAINING_TIME_500,
    /* 01 */ eCM_FOG_REMAINING_TIME_400,
    /* 02 */ eCM_FOG_REMAINING_TIME_300,
    /* 03 */ eCM_FOG_REMAINING_TIME_200,
    /* 04 */ eCM_FOG_REMAINING_TIME_100,

    eCM_FOG_REMAINING_TIME_NUMBER,
}eCM_FOG_REMAINING_TIME;

typedef enum
{
    /* 00 */ eCM_NATIVE_TIMING_1920X1080,
    /* 01 */ eCM_NATIVE_TIMING_1920X1200,
    /* 02 */ eCM_NATIVE_TIMING_3840X2160,
    /* 03 */ eCM_NATIVE_TIMING_3840X2400,

    eCM_NATIVE_TIMING_NUMBER,
}eCM_NATIVE_TIMING;

#endif   //_COMMONDEF_H_

