#ifndef _CUSTOMDEF_H_
#define _CUSTOMDEF_H_

typedef enum
{
    /* 00 */ eGUI_SOURCE_ID_HDMI1,
    /* 01 */ eGUI_SOURCE_ID_HDMI2,
    /* 02 */ eGUI_SOURCE_ID_DVI,
    /* 03 */ eGUI_SOURCE_ID_DP,		//A70Gen2_Doulas_0004 Modify
    /* 04 */ eGUI_SOURCE_ID_3GSDI,
    /* 05 */ eGUI_SOURCE_ID_HDBASET,

    eGUI_SOURCE_ID_NUMBER,
}eGUI_SOURCE_ID;

typedef enum
{
    /* 00 */ eGUI_TEST_PATTERN_OFF,
    /* 01 */ eGUI_TEST_PATTERN_GRID,
    /* 02 */ eGUI_TEST_PATTERN_WHITE,
    /* 03 */ eGUI_TEST_PATTERN_BLACK,
    /* 04 */ eGUI_TEST_PATTERN_CHECKERBOARD,
    /* 05 */ eGUI_TEST_PATTERN_COLORBAR,

    eGUI_TEST_PATTERN_NUMBER,
}eGUI_TEST_PATTERN_ID;

typedef enum
{
    /* 00 */ eGUI_SERVICE_TEST_PATTERN_OFF,
    /* 01 */ eGUI_SERVICE_TEST_PATTERN_GRID,
    /* 02 */ eGUI_SERVICE_TEST_PATTERN_WHITE,
    /* 03 */ eGUI_SERVICE_TEST_PATTERN_BLACK,
    /* 04 */ eGUI_SERVICE_TEST_PATTERN_CHECKBOARD,
    /* 05 */ eGUI_SERVICE_TEST_PATTERN_COLORBAR,
    /* 06 */ eGUI_SERVICE_TEST_PATTERN_RED,
    /* 07 */ eGUI_SERVICE_TEST_PATTERN_GREEN,
    /* 08 */ eGUI_SERVICE_TEST_PATTERN_BLUE,
    /* 09 */ eGUI_SERVICE_TEST_PATTERN_YELLOW,
    /* 10 */ eGUI_SERVICE_TEST_PATTERN_MAGENTA,
    /* 11 */ eGUI_SERVICE_TEST_PATTERN_CYAN,
    /* 12 */ eGUI_SERVICE_TEST_PATTERN_BORESIGHT,
    /* 13 */ eGUI_SERVICE_TEST_PATTERN_FULL_SCREEN,
    /* 14 */ eGUI_SERVICE_TEST_PATTERN_13POINTS,

    eGUI_SERVICE_TEST_PATTERN_NUMBER,
}eGUI_SERVICE_TEST_PATTERN_ID;

typedef enum
{
    /* 00 */ eGUI_TWIST_TEST_PATTERN_OFF,
    /* 01 */ eGUI_TWIST_TEST_PATTERN_GRID,
    /* 02 */ eGUI_TWIST_TEST_PATTERN_WHITE,
    /* 03 */ eGUI_TWIST_TEST_PATTERN_BLACK,
    /* 04 */ eGUI_TWIST_TEST_PATTERN_CHECKERBOARD,
    /* 05 */ eGUI_TWIST_TEST_PATTERN_COLORBAR,
    /* 06 */ eGUI_TWIST_TEST_PATTERN_GRAY,

    eGUI_TWIST_TEST_PATTERN_NUMBER,
}eGUI_TWIST_TEST_PATTERN_ID;

typedef enum
{
    /* 00 */ eGUI_PICTURE_SETTINGS_VIDEO,
    /* 01 */ eGUI_PICTURE_SETTINGS_BRIGHT,
    /* 02 */ eGUI_PICTURE_SETTINGS_ENHANCED,
    /* 03 */ eGUI_PICTURE_SETTINGS_REC709,
    /* 04 */ eGUI_PICTURE_SETTINGS_DICOMSIM,
    /* 05 */ eGUI_PICTURE_SETTINGS_BLENDING,
    /* 06 */ eGUI_PICTURE_SETTINGS_HDR,
    /* 07 */ eGUI_PICTURE_SETTINGS_3D,
    /* 08 */ eGUI_PICTURE_SETTINGS_2D_HIGH_SPEED,
    /* 09 */ eGUI_PICTURE_SETTINGS_USER,

    eGUI_PICTURE_SETTINGS_NUMBER,
}eGUI_PICTURE_SETTINGS_ID;

typedef enum
{
    /* 00 */ eGUI_PRE_USER_VIDEO,
    /* 01 */ eGUI_PRE_USER_BRIGHT,
    /* 02 */ eGUI_PRE_USER_ENHANCED,
    /* 03 */ eGUI_PRE_USER_REC709,
    /* 04 */ eGUI_PRE_USER_DICOMSIM,
    /* 05 */ eGUI_PRE_USER_BLENDING,
    /* 06 */ eGUI_PRE_USER_HDR,
    /* 07 */ eGUI_PRE_USER_3D,
    /* 08 */ eGUI_PRE_USER_2D_HIGH_SPEED,

    eGUI_PRE_USERS_NUMBER,
}eGUI_PRE_USER_ID;				//G100_Doulas_0066

//G100_Clare_0001, add, >>>
typedef enum
{
#ifdef PLATFORM_H60_2K//HICC2_Doulas_0014 Modify
	/* 00 */ eFORMATTER_DISPLAY_MODE_PRESENTATION,
	/* 01 */ eFORMATTER_DISPLAY_MODE_VIDEO,
	/* 02 */ eFORMATTER_DISPLAY_MODE_BRIGHT,
	/* 03 */ eFORMATTER_DISPLAY_MODE_ENHANCED,
	/* 04 */ eFORMATTER_DISPLAY_MODE_REC709,
	/* 05 */ eFORMATTER_DISPLAY_MODE_REAL,
	/* 06 */ eFORMATTER_DISPLAY_MODE_DICOMSIM,
	/* 07 */ eFORMATTER_DISPLAY_MODE_2D_HIGH_SPEED,
	/* 08 */ eFORMATTER_DISPLAY_MODE_3D,
	/* 09 */ eFORMATTER_DISPLAY_MODE_BLENDING,
	/* 10 */ eFORMATTER_DISPLAY_MODE_USER,
	/* 11 */ eFORMATTER_DISPLAY_MODE_HDR,
	/* 12 */ eFORMATTER_DISPLAY_MODE_PASSIVE_3D,
	/* 13 */ eFORMATTER_DISPLAY_MODE_OEJIG,
#else
    /* 00 */ eFORMATTER_DISPLAY_MODE_VIDEO,
    /* 01 */ eFORMATTER_DISPLAY_MODE_BRIGHT,
    /* 02 */ eFORMATTER_DISPLAY_MODE_ENHANCED,
    /* 03 */ eFORMATTER_DISPLAY_MODE_REC709,
    /* 04 */ eFORMATTER_DISPLAY_MODE_DICOMSIM,
    /* 05 */ eFORMATTER_DISPLAY_MODE_BLENDING,
    /* 06 */ eFORMATTER_DISPLAY_MODE_HDR,
    /* 07 */ eFORMATTER_DISPLAY_MODE_3D,
    /* 08 */ eFORMATTER_DISPLAY_MODE_PASSIVE_3D,
    /* 09 */ eFORMATTER_DISPLAY_MODE_2D_HIGH_SPEED,
    /* 10 */ eFORMATTER_DISPLAY_MODE_USER,
    /* 11 */ eFORMATTER_DISPLAY_MODE_OEJIG,
#endif
    eFORMATTER_DISPLAY_MODE_NUMBER,
}eFORMATTER_DISPLAY_MODE_ID;			//A70Gen2_Doulas_0003 Modify
//G100_Clare_0001, add, <<<
typedef enum
{
    /* 00 */ eGUI_LANGUAGE_ENGLISH,
    /* 01 */ eGUI_LANGUAGE_FRENCH,
    /* 02 */ eGUI_LANGUAGE_SPANISH,
    /* 03 */ eGUI_LANGUAGE_GERMAN,
    /* 04 */ eGUI_LANGUAGE_ITALIAN,
    /* 05 */ eGUI_LANGUAGE_POLSKI,
    /* 06 */ eGUI_LANGUAGE_RUSSIAN,
    /* 07 */ eGUI_LANGUAGE_S_CHINESE,
    /* 08 */ eGUI_LANGUAGE_T_CHINESE,
    /* 09 */ eGUI_LANGUAGE_JAPANESE,
    /* 10 */ eGUI_LANGUAGE_KOREAN,

    eGUI_LANGUAGE_NUMBER,
}eGUI_LANGUAGE_ID;

typedef enum
{
    /* 00 */ eGUI_SCALING_MODE_AUTO,
    /* 01 */ eGUI_SCALING_MODE_NATIVE,
    /* 02 */ eGUI_SCALING_MODE_4_3,
    /* 03 */ eGUI_SCALING_MODE_LETTER_BOX,
    /* 04 */ eGUI_SCALING_MODE_FULL_SIZE,
    /* 05 */ eGUI_SCALING_MODE_WIDTH,
    /* 06 */ eGUI_SCALING_MODE_HEIGHT,
    /* 07 */ eGUI_SCALING_MODE_CUSTOM,
    /* 08 */ eGUI_SCALING_MODE_3D,
    /* 09 */ eGUI_SCALING_MODE_21_9,  //HICC2_Doulas_0065

    eGUI_SCALING_MODE_NUMBER,
}eGUI_SCALING_MODE_ID;

typedef enum
{
    /* 00 */ eGUI_HOTKEY_SETTINGS_SIZE_PRESETS,
    /* 01 */ eGUI_HOTKEY_SETTINGS_PICTURE_SETTINGS,
    /* 02 */ eGUI_HOTKEY_SETTINGS_DEFAULT_VALUE,
    /* 03 */ eGUI_HOTKEY_SETTINGS_DETAIL,
    /* 04 */ eGUI_HOTKEY_SETTINGS_CONTRAST_ENHANCEMENT,
    /* 05 */ eGUI_HOTKEY_SETTINGS_LIGHT_SOURCE_MODE,
    /* 06 */ eGUI_HOTKEY_SETTINGS_FREEZE_SCREEN,
    /* 07 */ eGUI_HOTKEY_SETTINGS_INFORMATION,
    /* 08 */ eGUI_HOTKEY_SETTINGS_WARPBLEND_DISABLE,

    eGUI_HOTKEY_SETTINGS_NUMBER,
}eGUI_HOTKEY_SETTINGS_ID;

typedef enum
{
    /* 00 */ eGUI_SCREEN_MODE_OFF,
    /* 01 */ eGUI_SCREEN_MODE_PIP,
    /* 02 */ eGUI_SCREEN_MODE_PBP,

    eGUI_SCREEN_MODE_NUMBER,
}eGUI_SCREEN_MODE_ID;

typedef enum
{
    /* 00 */ eGUI_MENU_LOCATION_TOP_LEFT,
    /* 01 */ eGUI_MENU_LOCATION_TOP_RIGHT,
    /* 02 */ eGUI_MENU_LOCATION_CENTER,
    /* 03 */ eGUI_MENU_LOCATION_BOTTOM_LEFT,
    /* 04 */ eGUI_MENU_LOCATION_BOTTOM_RIGHT,

    eGUI_MENU_LOCATION_NUMBER,
}eGUI_MENU_LOCATION_ID;

typedef enum
{
    /* 00 */ eGUI_OVERSCAN_OFF,
    /* 01 */ eGUI_OVERSCAN_ZOOM,
    /* 02 */ eGUI_OVERSCAN_CROP,

    eGUI_OVERSCAN_NUMBER,
}eGUI_OVERSCAN_ID;

typedef enum
{
    /* 00 */ eGUI_COLOR_SPACE_AUTO,
    /* 01 */ eGUI_COLOR_SPACE_RGB_FULL,
    /* 02 */ eGUI_COLOR_SPACE_RGB_LIMITED,
    /* 03 */ eGUI_COLOR_SPACE_YUV_REC709,
    /* 04 */ eGUI_COLOR_SPACE_YUV_REC601,

    eGUI_COLOR_SPACE_NUMBER,
}eGUI_COLOR_SPACE_ID;

typedef enum
{
    /* 00 */ eGUI_3D_MODE_ON,
    /* 01 */ eGUI_3D_MODE_PASSIVE_3D,

    eGUI_3D_MODE_NUMBER,
}eGUI_3D_MODE_ID;		//A70Gen2_Doulas_0054 Modify

typedef enum
{
    /* 00 */ eGUI_3D_FORMAT_AUTO,
    /* 01 */ eGUI_3D_FORMAT_FRAME_PACKING,
    /* 02 */ eGUI_3D_FORMAT_SIDE_BY_SIDE,
    /* 03 */ eGUI_3D_FORMAT_TOP_AND_BOTTOM,
    /* 04 */ eGUI_3D_FORMAT_FRAME_SEQUENTIAL,
    /* 05 */ eGUI_3D_FORMAT_FRAME_OFF,

    eGUI_3D_FORMAT_NUMBER,
}eGUI_3D_FORMAT_ID;

typedef enum
{
    /* 00 */ eGUI_3D_TECH_DLP_LINK,
    /* 01 */ eGUI_3D_TECH_3D_SYNC,

    eGUI_3D_TECH_NUMBER,
}eGUI_3D_TECH_ID;

typedef enum
{
    /* 00 */ eGUI_3D_2D_3D,
    /* 01 */ eGUI_3D_2D_2D_LEFT,
    /* 02 */ eGUI_3D_2D_2D_RIGHT,

    eGUI_3D_2D_NUMBER,
}eGUI_3D_2D_ID;

typedef enum
{
    /* 00 */ eGUI_3D_SYNC_OUT_TO_EMITTER,
    /* 01 */ eGUI_3D_SYNC_OUT_TO_NEXT_PROJECTOR,

    eGUI_3D_SYNC_OUT_NUMBER,
}eGUI_3D_SYNC_OUT_ID;

typedef enum
{
    /* 00 */ eGUI_3D_LR_REFERENCE_1ST_FRAME,
    /* 01 */ eGUI_3D_LR_REFERENCE_FIELD_GPIO,

    eGUI_3D_LR_REFERENCE_NUMBER,
}eGUI_3D_LR_REFERENCE_ID;

typedef enum
{
    /* 00 */ eGUI_3D_SYNC_TYPE_AUTO,
    /* 01 */ eGUI_3D_SYNC_TYPE_INTERNAL,
    /* 02 */ eGUI_3D_SYNC_TYPE_EXTERNAL,

    eGUI_3D_SYNC_TYPE_NUMBER,
}eGUI_3D_SYNC_TYPE_ID;

typedef enum
{
    /* 00 */ eGUI_CONTRAST_ENHANCEMENT_OFF,
    /* 01 */ eGUI_CONTRAST_ENHANCEMENT_CE1,
    /* 02 */ eGUI_CONTRAST_ENHANCEMENT_CE2,

    eGUI_CONTRAST_ENHANCEMENT_NUMBER,
}eGUI_CONTRAST_ENHANCEMENT_ID;

typedef enum   //G100_Simon_0022
{
    /* 00 */ eGUI_GAMMA_VIDEO,
    /* 01 */ eGUI_GAMMA_FILM,
    /* 02 */ eGUI_GAMMA_BRIGHT,
    /* 03 */ eGUI_GAMMA_CRT,
    /* 04 */ eGUI_GAMMA_DICOM,
    /* 05 */ eGUI_GAMMA_HDR,

    eGUI_GAMMA_NUMBER,
}eGUI_GAMMA_ID;

typedef enum
{
    /* 00 */ eGUI_EDGE_ENHANCEMENT_OFF,
    /* 01 */ eGUI_EDGE_ENHANCEMENT_NORMAL,
    /* 02 */ eGUI_EDGE_ENHANCEMENT_MAXIMUM,

    eGUI_EDGE_ENHANCEMENT_NUMBER,
}eGUI_EDGE_ENHANCEMENT_ID;

typedef enum
{
    /* 00 */ eGUI_COLOR_WHEEL_SPEED_2X,
    /* 01 */ eGUI_COLOR_WHEEL_SPEED_3X,

    eGUI_COLOR_WHEEL_SPEED_NUMBER,
}eGUI_COLOR_WHEEL_SPEED_ID;

typedef enum
{
    /* 00 */ eGUI_LENS_TYPE_NA,
    /* 01 */ eGUI_LENS_TYPE_A20,
    /* 02 */ eGUI_LENS_TYPE_A21,
    /* 03 */ eGUI_LENS_TYPE_A22,
    /* 04 */ eGUI_LENS_TYPE_A23,
    /* 05 */ eGUI_LENS_TYPE_A24,
    /* 05 */ eGUI_LENS_TYPE_A25,
    /* 06 */ eGUI_LENS_TYPE_A26,

    eGUI_LENS_TYPE_NUMBER,
}eGUI_LENS_TYPE_ID;

typedef enum
{
    /* 00 */ eGUI_CEILING_MOUNT_OFF,
    /* 01 */ eGUI_CEILING_MOUNT_ON,
    /* 02 */ eGUI_CEILING_MOUNT_AUTO,

    eGUI_CEILING_MOUNT_NUMBER,
}eGUI_CEILING_MOUNT_ID;

typedef enum
{
    /* 00 */ eGUI_REAR_PROJECTION_FRONT,
    /* 01 */ eGUI_REAR_PROJECTION_REAR,

    eGUI_REAR_PROJECTION_NUMBER,
}eGUI_REAR_PROJECTION_ID;

typedef enum
{
    /* 00 */ eGUI_SPLASH_STARTUP_FACTORY_LOGO,
    /* 01 */ eGUI_SPLASH_STARTUP_BLUE,
    /* 02 */ eGUI_SPLASH_STARTUP_BLACK,
    /* 03 */ eGUI_SPLASH_STARTUP_WHITE,

    eGUI_SPLASH_STARTUP_NUMBER,
}eGUI_SPLASH_STARTUP_ID;

typedef enum
{
    /* 00 */ eGUI_STANDBY_MODE_STANDBY,
    ///* 01 */ eGUI_STANDBY_MODE_NETWORK_STANDBY,
    /* 02 */ eGUI_STANDBY_MODE_COMMUNICATION,

    eGUI_STANDBY_MODE_NUMBER,
}eGUI_STANDBY_MODE_ID;

typedef enum
{
    /* 00 */ eGUI_AUTO_SHUTDOWN_OFF,
    /* 01 */ eGUI_AUTO_SHUTDOWN_5MIN,
    /* 02 */ eGUI_AUTO_SHUTDOWN_10MIN,
    /* 03 */ eGUI_AUTO_SHUTDOWN_15MIN,
    /* 04 */ eGUI_AUTO_SHUTDOWN_20MIN,
    /* 05 */ eGUI_AUTO_SHUTDOWN_25MIN,
    /* 06 */ eGUI_AUTO_SHUTDOWN_30MIN,

    eGUI_AUTO_SHUTDOWN_NUMBER,
}eGUI_AUTO_SHUTDOWN_ID;

typedef enum
{
    /* 00 */ eGUI_SLEEP_TIMER_OFF,
    /* 01 */ eGUI_SLEEP_TIMER_2HOURS,
    /* 02 */ eGUI_SLEEP_TIMER_4HOURS,
    /* 03 */ eGUI_SLEEP_TIMER_6HOURS,

    eGUI_SLEEP_TIMER_NUMBER,
}eGUI_SLEEP_TIMER_ID;

typedef enum
{
    /* 00 */ eGUI_SERIAL_PORT_BAUD_RATE_1200,
    /* 01 */ eGUI_SERIAL_PORT_BAUD_RATE_2400,
    /* 02 */ eGUI_SERIAL_PORT_BAUD_RATE_4800,
    /* 03 */ eGUI_SERIAL_PORT_BAUD_RATE_9600,
    /* 04 */ eGUI_SERIAL_PORT_BAUD_RATE_19200,
    /* 05 */ eGUI_SERIAL_PORT_BAUD_RATE_38400,
    /* 06 */ eGUI_SERIAL_PORT_BAUD_RATE_57600,
    /* 07 */ eGUI_SERIAL_PORT_BAUD_RATE_115200,

    eGUI_SERIAL_PORT_BAUD_RATE_NUMBER,
}eGUI_SERIAL_PORT_BAUD_RATE_ID;

typedef enum
{
    /* 00 */ eGUI_SERIAL_PORT_PATH_RS232,
    /* 01 */ eGUI_SERIAL_PORT_PATH_HDBASET,
    /* 02 */ eGUI_SERIAL_PORT_PATH_SLOT1,
    /* 03 */ eGUI_SERIAL_PORT_PATH_SLOT2,

    eGUI_SERIAL_PORT_PATH_NUMBER,
}eGUI_SERIAL_PORT_PATH_ID;

typedef enum
{
    /* 00 */ eGUI_SERIAL_PORT_PATH_FROM_SLOT1,
    /* 01 */ eGUI_SERIAL_PORT_PATH_FROM_SLOT2,

    eGUI_SERIAL_PORT_PATH_FROM_NUMBER,
}eGUI_SERIAL_PORT_PATH_FROM_ID;

typedef enum
{
    /* 00 */ eGUI_KEYPAD_BACKLIGHT_5_SECS,
    /* 01 */ eGUI_KEYPAD_BACKLIGHT_10_SECS,
    /* 00 */ eGUI_KEYPAD_BACKLIGHT_20_SECS,
    /* 03 */ eGUI_KEYPAD_BACKLIGHT_30_SECS,
    /* 04 */ eGUI_KEYPAD_BACKLIGHT_ALWAYS_ON,
    /* 05 */ eGUI_KEYPAD_BACKLIGHT_ALWAYS_OFF,

    eGUI_KEYPAD_BACKLIGHT_NUMBER,
}eGUI_KEYPAD_BACKLIGHT_ID;

typedef enum
{
    /* 00 */ eGUI_STATUS_LED_ALWAYS_ON,
    /* 01 */ eGUI_STATUS_LED_ALWAYS_OFF,
    /* 02 */ eGUI_STATUS_LED_WARNING_ERRORS_ONLY,

    eGUI_STATUS_LED_NUMBER,
}eGUI_STATUS_LED_ID;

typedef enum
{
    /* 00 */ eGUI_WALL_COLOR_WHITE,
    /* 01 */ eGUI_WALL_COLOR_GRAY130,
    /* 02 */ eGUI_WALL_COLOR_LIGHT_YELLOW,

    eGUI_WALL_COLOR_NUMBER,
}eGUI_WALL_COLOR_ID;

typedef enum
{
    /* 00 */ eGUI_POWER_MODE_CONSTANT_POWER,
    /* 01 */ eGUI_POWER_MODE_CONSTANT_INTENSITY,
    /* 02 */ eGUI_POWER_MODE_ECO1,
    /* 03 */ eGUI_POWER_MODE_ECO2,

    eGUI_POWER_MODE_NUMBER,
}eGUI_POWER_MODE_ID;

typedef enum
{
    /* 00 */ eGUI_PIP_SIZE_SMALL,
    /* 01 */ eGUI_PIP_SIZE_MEDIUM,
    /* 02 */ eGUI_PIP_SIZE_LARGE,

    eGUI_PIP_SIZE_NUMBER,
}eGUI_PIP_SIZE_ID;

typedef enum
{
    /* 00 */ eGUI_MAIN_LAYOUT_PBP_MAIN_LEFT,
    /* 01 */ eGUI_MAIN_LAYOUT_PBP_MAIN_TOP,
    /* 02 */ eGUI_MAIN_LAYOUT_PBP_MAIN_RIGHT,
    /* 03 */ eGUI_MAIN_LAYOUT_PBP_MAIN_BOTTOM,
    /* 04 */ eGUI_MAIN_LAYOUT_PIP_BOTTOM_RIGHT,
    /* 05 */ eGUI_MAIN_LAYOUT_PIP_BOTTOM_LEFT,
    /* 06 */ eGUI_MAIN_LAYOUT_PIP_TOP_LEFT,
    /* 07 */ eGUI_MAIN_LAYOUT_PIP_TOP_RIGHT,

    eGUI_MAIN_LAYOUT_NUMBER,
}eGUI_MAIN_LAYOUT_ID;

typedef enum
{
    /* 00 */ eGUI_INPUT_KEY_CHANGE_SOURCE,
    /* 01 */ eGUI_INPUT_KEY_LIST_ALL_SOURCE,
    /* 02 */ eGUI_INPUT_KEY_AUTO_SOURCE,

    eGUI_INPUT_KEY_NUMBER,
}eGUI_INPUT_KEY_ID;

typedef enum
{
    /* 00 */ eGUI_COLOR_TEMPERATURE_WARMEST,
    /* 01 */ eGUI_COLOR_TEMPERATURE_WARM,
    /* 02 */ eGUI_COLOR_TEMPERATURE_COOL,

    eGUI_COLOR_TEMPERATURE_NUMBER,
}eGUI_COLOR_TEMPERATURE_ID;

typedef enum
{
    /* 00 */ eGUI_BLENDING_GAMMA_1_8,
    /* 01 */ eGUI_BLENDING_GAMMA_1_9,
    /* 02 */ eGUI_BLENDING_GAMMA_2_0,
    /* 03 */ eGUI_BLENDING_GAMMA_2_1,
    /* 04 */ eGUI_BLENDING_GAMMA_2_2,
    /* 05 */ eGUI_BLENDING_GAMMA_2_3,
    /* 06 */ eGUI_BLENDING_GAMMA_2_4,

    eGUI_BLENDING_GAMMA_NUMBER,
}eGUI_BLENDING_GAMMA_ID;

typedef enum
{
    /* 00 */ eGUI_BACKGROUND_COLOR_BLUE,
    /* 01 */ eGUI_BACKGROUND_COLOR_BLACK,
    /* 02 */ eGUI_BACKGROUND_COLOR_WHITE,
    /* 03 */ eGUI_BACKGROUND_COLOR_LOGO,

    eGUI_BACKGROUND_COLOR_NUMBER,
}eGUI_BACKGROUND_COLOR_ID;

typedef enum
{
    /* 00 */ eGUI_BACKUPINPUT_AUTOSWITCH_SEAMLESS,
    /* 01 */ eGUI_BACKUPINPUT_AUTOSWITCH_BACKUP,
    /* 02 */ eGUI_BACKUPINPUT_AUTOSWITCH_SIGNLE,

    eGUI_BACKUPINPUT_AUTOSWITCH_NUMBER,
}eGUI_BACKUPINPUT_AUTOSWITCH_ID;

typedef enum
{
    /* 00 */ eGUI_EDID_TYPE_V14,
    /* 01 */ eGUI_EDID_TYPE_V20,
    /* 02 */ eGUI_EDID_TYPE_CUSTOMIZED,  //HICC2_Doulas_0068

    eGUI_EDID_TYPE_NUMBER
}eGUI_EDID_TYPE_ID;

typedef enum
{
    /* 00 */ eGUI_LAN_PATH_SWITCH_RJ45,
    /* 01 */ eGUI_LAN_PATH_SWITCH_HDBASET,

    eGUI_LAN_PATH_SWITCH_NUMBER
}eGUI_LAN_PATH_SWITCH_ID;

typedef enum
{
    /* 00 */ eGUI_OSD_TIMEOUT_OFF,
    /* 01 */ eGUI_OSD_TIMEOUT_60_SEC,
    /* 02 */ eGUI_OSD_TIMEOUT_180_SEC,

    eGUI_OSD_TIMEOUT_NUMBER
}eGUI_OSD_TIMEOUT_ID;

typedef enum
{
    /* 00 */ eGUI_BACKGROUND_BLUE,
    /* 01 */ eGUI_BACKGROUND_BLACK,
    /* 02 */ eGUI_BACKGROUND_WHITE,
    /* 03 */ eGUI_BACKGROUND_LOGO,

    eGUI_BACKGROUND_NUMBER
}eGUI_BACKGROUND_ID;

typedef enum
{
    /* 00 */ eGUI_LIGHT_SOURCE_MODE_NORMAL,
    /* 01 */ eGUI_LIGHT_SOURCE_MODE_ECO_MODE,
    /* 02 */ eGUI_LIGHT_SOURCE_MODE_CUSTOM_MODE,

    eGUI_LIGHT_SOURCE_MODE_NUMBER
}eGUI_LIGHT_SOURCE_MODE_ID;

typedef enum
{
    /* 00 */ eGUI_LENS_MEMORY_SAVE_1,
    /* 01 */ eGUI_LENS_MEMORY_SAVE_2,
    /* 02 */ eGUI_LENS_MEMORY_SAVE_3,
    /* 03 */ eGUI_LENS_MEMORY_SAVE_4,
    /* 04 */ eGUI_LENS_MEMORY_SAVE_5,

    eGUI_LENS_MEMORY_SAVE_NUMBER
}eGUI_LENS_MEMORY_SAVE_ID;

typedef enum
{
    /* 00 */ eGUI_LENS_MEMORY_APPLY_1,
    /* 01 */ eGUI_LENS_MEMORY_APPLY_2,
    /* 02 */ eGUI_LENS_MEMORY_APPLY_3,
    /* 03 */ eGUI_LENS_MEMORY_APPLY_4,
    /* 04 */ eGUI_LENS_MEMORY_APPLY_5,

    eGUI_LENS_MEMORY_APPLY_NUMBER
}eGUI_LENS_MEMORY_APPLY_ID;

typedef enum
{
    /* 00 */ eGUI_LOGO_PATTERN_FACTORY_LOGO,
    /* 01 */ eGUI_LOGO_PATTERN_BLUE,
    /* 02 */ eGUI_LOGO_PATTERN_BLACK,
    /* 03 */ eGUI_LOGO_PATTERN_WHITE,

    eGUI_LOGO_PATTERN_NUMBER
}eGUI_LOGO_PATTERN;

typedef enum
{
    /* 00 */ eGUI_LOW_LATENCY_MODE_NORMAL,
    /* 01 */ eGUI_LOW_LATENCY_MODE_2D_ULTRA,

    eGUI_LOW_LATENCY_MODE_NUMBER
}eGUI_LOW_LATENCY_MODE;

typedef enum
{
    /* 00 */ eGUI_DETAIL_MAXIMUM,
    /* 01 */ eGUI_DETAIL_HIGH,
    /* 02 */ eGUI_DETAIL_NORMAL,
    /* 03 */ eGUI_DETAIL_LOW,
    /* 04 */ eGUI_DETAIL_MINIMUM,

    eGUI_DETAIL_NUMBER
}eGUI_DETAIL_;

typedef enum
{
    /* 00 */ eGUI_HDR_LEVEL_1,
    /* 01 */ eGUI_HDR_LEVEL_2,
    /* 02 */ eGUI_HDR_LEVEL_3,
    /* 03 */ eGUI_HDR_LEVEL_4,

    eGUI_HDR_LEVEL_NUMBER
}eGUI_HDR_LEVEL;

typedef enum
{
    /* 00 */ eGUI_CLOCK_MODE_USE_NTP_SERVER,
    /* 01 */ eGUI_CLOCK_MODE_MANUAL,

    eGUI_CLOCK_MODE_NUMBER
}eGUI_CLOCK_MODE;

typedef enum
{
 /* 00 */   eGUI_UPDATE_INTERVAL_HOURLY,
 /* 01 */   eGUI_UPDATE_INTERVAL_DAILY,

    eGUI_UPDATE_INTERVAL_NUMBER
}eGUI_UPDATE_INTERVAL;

typedef enum
{
 /* 00 */    eGUI_HDMI_OUT_HDMI1,
 /* 01 */    eGUI_HDMI_OUT_HDMI2,

    eGUI_HDMI_OUT_MAX_NUMBER
} eGUI_HDMI_OUT;

typedef enum
{
 /* 00 */    eGUI_COPY_EVENT_TO_MONDAY,
 /* 01 */    eGUI_COPY_EVENT_TO_TUESDAY,
 /* 02 */    eGUI_COPY_EVENT_TO_WEDNESDAY,
 /* 03 */    eGUI_COPY_EVENT_TO_THURSDAY,
 /* 04 */    eGUI_COPY_EVENT_TO_FRIDAY,
 /* 05 */    eGUI_COPY_EVENT_TO_SATURDAY,
 /* 06 */    eGUI_COPY_EVENT_TO_SUNDAY,

             eGUI_COPY_EVENT_TO_NUMBER
} eGUI_COPY_EVENT_TO;



#ifdef CUSTOM_CHRISTIE

typedef enum
{
    /* 00 */ eGUI_GEO_MEMORY_SAVE_1,
    /* 01 */ eGUI_GEO_MEMORY_SAVE_2,
    /* 02 */ eGUI_GEO_MEMORY_SAVE_3,
    /* 03 */ eGUI_GEO_MEMORY_SAVE_4,

    eGUI_GEO_MEMORY_SAVE_NUMBER
}eGUI_GEO_MEMORY_SAVE_ID;

typedef enum
{
    /* 00 */ eGUI_GEO_MEMORY_APPLY_OFF,
    /* 01 */ eGUI_GEO_MEMORY_APPLY_1,
    /* 02 */ eGUI_GEO_MEMORY_APPLY_2,
    /* 03 */ eGUI_GEO_MEMORY_APPLY_3,
    /* 04 */ eGUI_GEO_MEMORY_APPLY_4,

    eGUI_GEO_MEMORY_APPLY_NUMBER
}eGUI_GEO_MEMORY_APPLY_ID;

#else


typedef enum
{
    /* 00 */ eGUI_GEO_MEMORY_SAVE_1,
    /* 01 */ eGUI_GEO_MEMORY_SAVE_2,
    /* 02 */ eGUI_GEO_MEMORY_SAVE_3,
    /* 03 */ eGUI_GEO_MEMORY_SAVE_4,
    /* 04 */ eGUI_GEO_MEMORY_SAVE_5,

    eGUI_GEO_MEMORY_SAVE_NUMBER
}eGUI_GEO_MEMORY_SAVE_ID;

typedef enum
{
    /* 00 */ eGUI_GEO_MEMORY_APPLY_1,
    /* 01 */ eGUI_GEO_MEMORY_APPLY_2,
    /* 02 */ eGUI_GEO_MEMORY_APPLY_3,
    /* 03 */ eGUI_GEO_MEMORY_APPLY_4,
    /* 04 */ eGUI_GEO_MEMORY_APPLY_5,

    eGUI_GEO_MEMORY_APPLY_NUMBER
}eGUI_GEO_MEMORY_APPLY_ID;

#endif


#endif   //_CUSTOMDEF_H_

